### ISSUE TITLE
Pushing large app crashes host / platform

### ISSUE THREAD

**Issue by haf** [deis/deis#3580] opened 2015-04-25 09:17 UTC
Deis v1.4.

I got a hung process; deis-store-metadata. At first only a single metadata node went down; but that made deis-logger crash, which meant I couldn't push deploys anymore to the builder (or maybe the builder requires ceph for something; I don't know) -- this was the effect non the less.

```
$ fleetctl list-units
deis-store-gateway@1.service		1084039b.../10.7	inactive	dead
deis-store-metadata.service		1084039b.../10.7	failed		failed
deis-store-metadata.service		180588fb.../10.6	inactive	dead
deis-store-metadata.service		6a224380.../10.105	inactive	dead
```

How to bring it back up?

Logs from `10.6`:

```
$ journalctl -fu deis-store-metadata.service
Apr 25 02:52:52 deis-2 sh[1149]: 2015-04-25 02:52:52.456929 7ffb77f35700  1 mds.-1.0 handle_mds_map standby
Apr 25 08:30:18 deis-2 sh[1149]: 2015-04-25 08:30:18.926682 7ffb77f35700  1 mds.-1.0 handle_mds_map standby
Apr 25 09:08:08 deis-2 systemd[1]: Stopping deis-store-metadata...
Apr 25 09:08:08 deis-2 sh[1149]: 2015-04-25 09:08:08.262425 7ffb7362b700 -1 mds.-1.0 *** got signal Terminated ***
Apr 25 09:08:08 deis-2 sh[1149]: 2015-04-25 09:08:08.262525 7ffb7362b700  1 mds.-1.0 suicide.  wanted down:dne, now up:standby
Apr 25 09:08:08 deis-2 systemd[1]: Stopped deis-store-metadata.
Apr 25 09:08:08 deis-2 docker[25512]: deis-store-metadata
```

I find it very bad manners for my software to suicide in production, and I think that should be considered a bug!

I also have a terminal program hung on `deisctl restart deis-store-metadata` which gives no intelligible output.

Have you considered implementing something like Zipkin? Because it's really hard to correlate and debug with command line tools inside a cluster. Just an off-the-shelf ELK stack or Greylog2 equivalent would also do just fine.

**Comment by haf** [comment] 2015-04-25 09:29
Ok, so store-metadata is running on all except one, now:

```
deis-store-metadata.service	1084039b.../10.27	not-found	failed		failed
```

How do I start it on that particular machine? It's global unit.

**Comment by carmstrong** [comment] 2015-04-26 00:12
@haf It looked like something on that host terminated all running containers. Does `journalctl -u docker` show anything useful?

**Comment by haf** [comment] 2015-04-27 12:54
Not really, the daemon is running and not all containers are terminated.

The logs of deis-mds:

```
-- Logs begin at Sun 2015-03-29 11:49:17 UTC. --
Apr 25 08:30:02 deis-3 systemd[1]: Stopping deis-store-metadata...
Apr 25 08:30:02 deis-3 sh[972]: 2015-04-25 08:30:02.840625 7f64f57b9700 -1 mds.-1.0 *** got signal Terminated ***
Apr 25 08:30:02 deis-3 sh[972]: 2015-04-25 08:30:02.850464 7f64f57b9700  1 mds.-1.0 suicide.  wanted down:dne, now up:standby
Apr 25 08:30:04 deis-3 docker[11446]: Error response from daemon: No such container: deis-store-metadata
Apr 25 08:30:04 deis-3 docker[11446]: time="2015-04-25T08:30:04Z" level="fatal" msg="Error: failed to stop one or more containers"
Apr 25 08:30:04 deis-3 systemd[1]: deis-store-metadata.service: control process exited, code=exited status=1
Apr 25 08:30:04 deis-3 systemd[1]: Stopped deis-store-metadata.service.
Apr 25 08:30:04 deis-3 systemd[1]: Unit deis-store-metadata.service entered failed state.
```

What's with the 'no such container'?

**Comment by haf** [comment] 2015-04-27 13:10
Probably same as https://github.com/deis/deis/issues/3425

**Comment by haf** [comment] 2015-04-27 13:21
Can I somehow **re-run** the MDS through deis on a single node? Having trouble testing.

**Comment by haf** [comment] 2015-04-27 13:22
This is what 'deisctl help restart` gives:

```
 deisctl help restart
Stops and then starts the specified components.

Usage:
  deisctl restart [<target>...] [options]
```

**Comment by haf** [comment] 2015-04-27 13:28
```
$ sudo systemctl start deis-store-metadata.service
Failed to start deis-store-metadata.service: Unit deis-store-metadata.service failed to load: No such file or directory.
```

**Comment by haf** [comment] 2015-04-27 13:46
Possibly related "not found" error https://github.com/coreos/bugs/issues/8

**Comment by haf** [comment] 2015-04-27 13:48
`systemctl daemon-reload` and then `systemctl start deis-store-metadata` seems to have started it again

**Comment by haf** [comment] 2015-04-27 13:48
Alright. Great! 7h later.

**Comment by haf** [comment] 2015-04-27 13:51
Ok, next yak, this error message is still here:

```
-----> Building Docker image
remote: build context to Docker daemon
time="2015-04-27T13:50:02Z" level="fatal" msg="Cannot connect to the Docker daemon. Is 'docker -d' running on this host?"
-----> Building Docker image
remote: build context to Docker daemon
time="2015-04-27T13:50:02Z" level="fatal" msg="Cannot connect to the Docker daemon. Is 'docker -d' running on this host?"
To ssh://gitrepo
 + d28428a...2a43200 master -> master
``

**Comment by haf** [comment] 2015-04-27 13:53
Restarting builder solved that... Ok, let's see if it deploys.

**Comment by haf** [comment] 2015-04-27 14:57
It deploys again. Eye.

So in summary, possible lessons:

 - sometimes deis services crash without much notification (=> integrate with a messaging/monitoring service off the shelf?)
 - the builder service has some sort of bug in it which makes it unable to talk to dockerd until it's restarted (=> fix bug | react to this error message and restart builder from itself?)
 - fleetctl can't always schedule units (=> document hack `daemon-reload` and follow https://github.com/coreos/fleet/issues/1202)
 - deisctl doesn't provide help for options (=> better docs in deisctl)
 - it seems like a single service going down can bring down all of deis down (=> test deis with something like chaos-monkey?)

**Comment by carmstrong** [comment] 2015-04-28 08:05
> What's with the 'no such container'?

That's a bit confusing, but isn't bad - we tell Docker to clean up the container when the service stops: https://github.com/deis/deis/blob/ded90a8417cfdc19cad56d2a5056b911d30ce5a2/deisctl/units/deis-store-metadata.service#L10

Sometimes, the container is cleaned up when it's queried. No big deal.

I'm honestly not sure what happened with your cluster, @haf. Something definitely caused systemd to tell your containers to stop:
```
Apr 25 09:08:08 deis-2 systemd[1]: Stopping deis-store-metadata...
```

I would investigate `dmesg` or other system-level logs (`journalctl` without any unit filter will show you the journals for all units) right before the time when you started seeing issues. We've seen cases before where high IO will cause systemd to miss a few heartbeats and restart all services, behaving similarly to this.

**Comment by haf** [comment] 2015-04-28 08:31
They failed when I pushed a large container > 2.2 GiB through the system. I'm not sure what bug this exposes though.

**Comment by carmstrong** [comment] 2015-04-28 17:30
> They failed when I pushed a large container > 2.2 GiB through the system.

Interesting. We'll probably want to try to recreate this.

**Comment by bacongobbler** [comment] 2015-05-27 21:23
I was not able to re-create this issue with a 3.4GB container. Threw the same container multiple times at the system without a problem.

```
><> deis create foo
Creating application... done, created foo
Git remote deis added
><> cat Dockerfile 
FROM ubuntu

RUN fallocate -l 3G test.blob

EXPOSE 8000
CMD echo hi
><> git push deis master
```

Obviously it failed to launch because the container exits immediately, but the entire cluster didn't die, which is a good thing.

Proof:

```
core@deis-03 ~ $ docker images | grep foo
REPOSITORY                              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
172.17.8.100:5000/foo                   v2                  b9390dfa5862        59 minutes ago      3.41 GB
```

**Comment by bacongobbler** [comment] 2015-05-27 21:52
@haf if you have any way that reliably reproduces this issue then I'd be happy to take a look at it, but I've tried this on three different deployments (DO, Rackspace, Vagrant) without any surprising suicide calls from Ceph. Maybe this was an issue with Giant but no longer with Hammer?

**Comment by haf** [comment] 2015-05-27 22:58
What was the size of the memory on the machines you tested it on? I was running 4 GiB machines x64.

**Comment by bacongobbler** [comment] 2015-05-27 23:32
The default provision scripts, which IIRC all use 8GB machines. EC2 uses m3.large which have 7.5GB, and Rackspace provides performance1-2 which are 2GB nodes. As for Vagrant, my dev machine has 32GB of memory with an i7-4790K.

If anything the problem should've been apparent on Rackspace, considering that it's below your specs.

**Comment by haf** [comment] 2015-05-27 23:38
Yes, or maybe network corruption of data which is stochastic played a role in the long push of 15 minutes that resulted from the large size for me. These are admittedly hard things to test so thank you for spending the time and effort. I can't reliably reproduce it either, so I suppose that if I were you I would go through the code and ensure it handles all TCP socket states during the long pushes instead, matched perhaps with start-at-offset and retries. Sorry I can't be of more help at the moment.

**Comment by aj-may** [comment] 2015-09-02 20:20
I've seen the same exact issue on a cluster of 3 m4.large instances while pushing a PHP application.  

Compiled slug size: 156M

**Comment by bacongobbler** [comment] 2015-09-02 20:53
@aj-may which issue exactly? Do you have logs? I attempted to re-create this issue [here](https://github.com/deis/deis/issues/3580#issuecomment-106083641) but failed. I'd be interested to see how you set up your application.

**Comment by aj-may** [comment] 2015-09-02 22:46
@bacongobbler we are also experiencing several of the deis components dying during a build process of a specific application. Do you want to set up a call tomorrow after the Plannig meeting?  I can explain our setup and applications, as well as give you access to the box.

**Comment by aj-may** [comment] 2015-09-02 22:48
I also am not convinced it has anything to do with image size

**Comment by mboersma** [comment] 2015-11-02 23:55
I'm closing this since it hasn't seen any activity in two months. Please re-open this or create a new issue if this behavior can be isolated and continues in the current Deis release.

**Closed by mboersma** 2015-11-02 23:55 UTC
Labels: registry
