### ISSUE TITLE
all routers stopped responding

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#3573] opened 2015-04-24 08:34 UTC
I haven't found anything similar tagged with bug / issue / router.

- Deis 1.5.0
- 3 node cluster in DO

About 20:03 CEST yesterday (23.04.2015) all our routers stopped responding. I was able to do nse to router, nginx was running but not accepting anything (timeouts). Ceph was in healthy state (no clock skew). Other components were fine too. After running 'deisctl restart' for each router everything went back to normal state. 

Is it something know? How i can provide you with logs from this time? We're pushing some logs to es, but it isn't whole journal and I didn't found anything suspicious there.

**Comment by Blystad** [comment] 2015-04-24 12:53
If it happens again, `nse` into the container and run `netstat`. Look for `CLOSE_WAIT`.

This is maybe related to #3448 but #3448 is mostly on AWS issues. DO doesn't have a front-facing load balancer, it uses DNS.

I think we need to get #3560 (deis-router error_log should have etcd configurable error level) included so we can get better error logs.

**Comment by szymonpk** [comment] 2015-04-24 13:01
Hmm it looks very similar to #3448, but It happened to me first time since cluster setup (about 2-3 weeks?). This cluster isn't used too much maybe thats why, I hope it won't happen again, if so I'll check for CLOSE_WAIT sockets.

**Comment by bacongobbler** [comment] 2015-04-24 16:29
I have a feeling this is due to https://github.com/deis/deis/issues/3501. @szymonpk can you please update to v1.5.2 and see if you have that problem there?

**Comment by rogerleite** [comment] 2015-04-24 16:52
Look at deis-builder logs ... in my case someone was flooding builder with a lot of ssh login. After i blocked this (via security tcp rule on Amazon), never had this problem again. I'm using 1.5.1 version.

**Comment by szymonpk** [comment] 2015-04-27 06:00
Happened again.

@babarinde netstat output, lots of CLOSE_WAIT - https://gist.github.com/szymonpk/f6bb40102307d2488c8e
@bacongobbler I wanted to wait for 1.6.0, but looks like I'll have to move to 1.5.2 asap, probably tonight.
@rogerleite I think we've discussed this on irc, I've deployed blacklist on ssh few days ago, didn't helped :(

**Comment by bacongobbler** [comment] 2015-04-27 06:20
@szymonpk you can try the router image that @carmstrong posted with https://github.com/deis/deis/issues/3448#issuecomment-95311805. It contains the fix from https://github.com/deis/deis/pull/3554 which will ship in v.1.6.0.

Since other users have confirmed that the same image has fixed the problem for them on top of v1.5.2, I'm going to close this as a duplicate. If the image does not resolve your issue, then we'll be happy to re-open and take another look. Thanks!

**Closed by bacongobbler** 2015-04-27 06:20 UTC
Labels: router
