### ISSUE TITLE
Failed deis builds return 0 exit status

### ISSUE THREAD

**Issue by sstarcher** [deis/deis#4897] opened 2016-02-02 18:42 UTC
Deis 1.12.2
```
Git remote deis added
[master (root-commit) b61a8e6]
 3 files changed, 33 insertions(+)
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 306.46 MiB | 38.12 MiB/s, done.
Total 5 (delta 0), reused 0 (delta 0)

-----> Building Docker image
remote: Sending build context to Docker daemon 331.3 MB
Step 0 : FROM dfjetty:9.3.3
Pulling repository docker.io/library/dfjetty
Error: image library/dfjetty:9.3.3 not found
To ssh://git@deis.cluster.private:2222/app.git
 + d130363...b61a8e6 master -> master (forced update)```

echo $? returns 0

on a git push while a concurrent build is going on or with permission denied both return a 1, but on a build failure git push will return a 0

Tested using a docker build and a nodejs build

**Comment by bacongobbler** [comment] 2016-02-02 19:29
closing as a duplicate of https://github.com/deis/deis/issues/4695

**Closed by bacongobbler** 2016-02-02 19:29 UTC
