### ISSUE TITLE
New nodes should be members, not proxies, on the etcd cluster

### ISSUE THREAD

**Issue by crigor** [deis/deis#4645] opened 2015-10-21 04:05 UTC
When you have a running deis cluster and AWS autoscaling replaces 1 node, etcd will come up as a proxy and not a member on the etcd cluster.

You can promote a proxy to a member but you have to manually do it https://github.com/coreos/etcd/blob/master/Documentation/proxy.md#promote-a-proxy-to-a-member-of-etcd-cluster.

You can also add the node as a member when it boots https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#add-a-new-member but you have to set ETCD_INITIAL_CLUSTER and ETCD_INITIAL_CLUSTER_STATE instead of using a discovery url.

**Comment by krancour** [comment] 2015-10-21 22:35
@crigor the behavior you're seeing is to be expected.  If a host isn't explicitly removed from the etcd cluster, etcd assumes the node is _temporarily_ unreachable due to network issues or reboot and that it's coming back sooner or later.  And if the cluster already had its max number of peers before one machine went offline and was replaced by autoscaling, the new node does indeed become a proxy.

Expected though it may be, there are some things you can do to combat this behavior.  There are instructions [here](http://docs.deis.io/en/latest/managing_deis/add_remove_host/#automatic-host-removal) on how to have Deis automatically remove a node's membership in the ceph and etcd clusters before reboot, shutdown, or halt events.

Alternatively (advanced) you can isolate etcd to a small, fixed number of nodes as described [here](http://docs.deis.io/en/latest/managing_deis/isolating-etcd/) and [here](https://coreos.com/os/docs/latest/cluster-architectures.html#production-cluster-with-central-services).  When doing this, the intent would be to treat the etcd nodes as "pets" instead of "cattle" and invest in their long-term health instead of allowing them to be replaced by the sort of scaling events that may impact all your other ("cattle") nodes.

**Comment by carmstrong** [comment] 2015-10-21 23:14
> There are instructions here on how to have Deis automatically remove a node's membership in the ceph and etcd clusters before reboot, shutdown, or halt events.

We may want to start enabling the graceful removal script by default -- I think it's still billed as "experimental", but it seems to be increasingly important for real clusters. /cc @iancoffey

**Comment by iancoffey** [comment] 2015-10-21 23:31
If we can get #4554 merged, we will be closer for to having graceful etcd and ceph removal ready for prime time.

Regarding the main issue - short of adding something to mechanize the node addition via the etcd membership API (like we did in Deis Pro), there isnt really a solution that wont involve manual etcd wrangling.

**Comment by krancour** [comment] 2015-10-21 23:33
> Regarding the main issue...

I think the OP's issue doesn't happen if nodes that are leaving the cluster deregister properly.  Do I have that wrong?

**Comment by krancour** [comment] 2015-10-21 23:34
But I am +1 on enabling the graceful removal scripts by default.

**Comment by jeff-lee** [comment] 2015-10-21 23:35
This is becoming an issue for us as well.  Thanks for linking the etcd docs - I've become pretty good at fixing ceph, but couldn't find any documentation on dealing with the promotion of the etcd peers and was about to open a ticket.

I haven't investigated this fully yet, but I also believe that the AWS ASG attempts to rebalance the nodes across availability zones when you scale up and then down - leading to additional cleanup headaches.

I was running some tests where I detached and terminated a node and was surprised when a second node was shut down and replaced with one in a different AZ without me doing anything.  Ceph was not happy with that as it was in the middle of recovering from the first shutdown.

**Comment by krancour** [comment] 2015-10-21 23:40
@jeff-lee isolating etcd and/or the control plane to a small, fixed number of nodes can improve both the etcd and ceph situation.  You can put those things in a separate ASG so that those few, important machines always stick around and don't get killed off by scaling events.

**Comment by iancoffey** [comment] 2015-10-21 23:40
@krancour I spent some time testing that, and deleting the old node from the cluster and from the discovery url before adding a new node did not result in a functional new etcd member. Im going to try it again if I get a sec but that is the current underlying issue, right @crigor ?

**Comment by krancour** [comment] 2015-10-21 23:41
@iancoffey I am trying it now as well.

**Comment by jeff-lee** [comment] 2015-10-21 23:51
@krancour The issue I was simulating was re-provisioning with a larger instance type so I needed to replace all the nodes.  I had added in the new nodes, but encountered the unexpected re-scaling after I detached and removed the first node.  I'll see if I can replicate this week.

**Comment by krancour** [comment] 2015-10-22 00:01
> The issue I was simulating was re-provisioning with a larger instance type so I needed to replace all the nodes.

Not to belabor the suggestion of isolating etcd and the control plane, but if you were to do so, you likely can avoid the need to scale those few machines up since they'd be handling a relatively modest workload.  Then you could scale the machines in the data plane (your real workhorses) up, down, out, and in without jeopardizing overall cluster health.  And the latter can be sized differently than the former if you want as well.

**Comment by krancour** [comment] 2015-10-22 00:16
@iancoffey @crigor I'll be a monkey's uncle.  I just tested this in vagrant.  I brought up a three node cluster and used `etcdctl member remove <id>` to remove a node.  I then shut that same node down and promptly replaced it with a new one (with a different IP for good measure).  I fully expected that with room in the cluster for another peer, the new node would become a peer, but @crigor's observation is correct-- it becomes a proxy.

**Comment by jeff-lee** [comment] 2015-10-22 00:18
@krancour we had already gone through the process of isolating our application plane ( prior to the introduction of the dataPlane tags ) through the use of tagging.

Unfortunately, when we started adding in monitoring, logging, etc units into the cluster we realized that the initial instance sizing for the controlPlane units was too small.  We also had issues with Docker leaking memory and the builder using 80 GB of disk space so at the end of the day we just decided to resize.

**Comment by krancour** [comment] 2015-10-22 03:56
@jeff-lee I just went through what you reported.  I shut down a running etcd peer, as if to scale it up (didn't even terminate it), and the ASG was pretty quick to terminate the stopped instance and fully replace it.  And then, as @crigor noted in the OP, the replacement instance joins the cluster as a proxy (_even if I removed the other node properly_).  Only manually promoting the proxy to a peer gets me back to where I want things to be.

Do this to all n of n _original_ peers and then one also runs into #4602-- all the peers listed in the document at the discovery URL are stale.  Also, according to [this etcd doc](https://coreos.com/os/docs/latest/cluster-discovery.html#existing-clusters), the TTL on entries in the doc at the discovery URL is 7 days... so 7 days after bootstrapping a cluster, the document at the discovery URL will enumerate _no_ peers:

> It's also possible that a discovery URL can contain no existing addresses, because they were all removed after 7 days. This represents a dead cluster and the discovery URL won't work any more and should be discarded.

(fwiw, I think it's inaccurate to describe this as a "dead cluster."  The discovery URL may no longer be useful, but I don't think that is any reflection on the cluster's health.)

Etcd is working exactly as it was designed, but it's also clear that discovery URLs aren't indefinitely reliable.  We _have_ previously contemplated not relying on them anymore.  See #4268.  (I think this remains outstanding because of the great difficulty in making this work for all cluster sizes and all cloud providers.)

Re-reading my favorite etcd doc on [production cluster architecture](https://coreos.com/os/docs/latest/cluster-architectures.html#production-cluster-with-central-services), I'm now spotting this bit that I've previously overlooked:

> Our Central Services machines will run services that support the rest of the cluster. *__etcd is configured with static networking and a peers list.__*

Pretty much what this amounts to is _not_ using ASGs and discovery URLs to manage the isolated etcd peers.  One could create a custom CloudFormation template that creates, individually, 3 or 5 etcd peers with each at a _specific_ IP.  Each would also be configured to know the IPs of its peers.  Such a setup would be very stable.

**Comment by jeff-lee** [comment] 2015-10-22 04:30
@krancour Yeah, as I discovered while digging for documentation on how to promote a proxy, it seems that the discovery url was only ever intended to be used for initial bootstrapping.  All subsequent cluster changes are meant to be done through runtime reconfiguration.  See [here](https://github.com/coreos/etcd/issues/2807) and [here](https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#lifetime-of-a-discovery-url).
<quote>
>Lifetime of a Discovery URL
> A discovery URL identifies a unique etcd cluster. Instead of reusing a discovery URL, you should always create discovery URLs for new clusters.
>
>Moreover, discovery URLs should ONLY be used for the initial bootstrapping of a cluster. To change cluster membership after the cluster is already running, see the runtime reconfiguration guide.
</quote>

Although the idea of the ASG is nice, having that second node disappear moments after ceph has started to recover from the removal of the first node is surprising and painful.

**Comment by krancour** [comment] 2015-10-28 18:56
Trying to put some closure on this.  Collectively, I think we have established and agree that etcd is behaving just as intended and as its own documentation describes.  etcd documentation further recommends (and I believe this recommendation ought to be taken seriously) that etcd peers run on a small, fixed number of nodes that use static configuration instead of the etcd discovery service.  A corollary to this is that these few nodes should not be managed in an auto-scaling group.

While Deis' existing provisioning processes do not account for this, etcd and Deis are both sufficiently documented such that anyone wanting to run such a configuration should be able to provision infrastructure to that end, albeit not without some effort.

We're currently investigating options for a more production-grade provisioning process (on AWS only to start), but I do believe the OP's proposal that "New nodes should be members, not proxies, on the etcd cluster," has been adequately dispelled as something we should not do, favoring instead to _not_ autoscale etcd peers.  Based on that I'm going to close this.

**Closed by krancour** 2015-10-28 18:56 UTC
Labels: contrib and provisioning, etcd/fleet, production-team

**Comment by crigor** [comment] 2015-10-29 08:38
@krancour we need to document this if it isn't documented yet. I agree that etcd2 behaves as expected. Before deis 1.9.0, we were using etcd 0.4. New nodes replaced by the autoscaling group joins the cluster as members since etcd 0.4 didn't have proxies then.

With deis 1.9.0 and etcd2, the behavior changed. So with deis 1.9.0 and above, you have to promote proxies to members. Otherwise, when 2 nodes are replaced (on a 3-node cluster), etcd loses its quorum.

Currently, by using autoscaling group on AWS, my assumption (and probably most people too) is etcd can recover on its own. We probably just need to add a warning that it's not the case anymore starting deis 1.9.0.

I agree on using a separate etcd cluster. That increases the minimum number of servers needed but might be the best option in production. This is for a different ticket though.

**Comment by krancour** [comment] 2015-10-29 10:32
@crigor that's a good point about this behavior having changed when we jumped to etcd2.  I'll open a separate issue for amending the docs.
