### ISSUE TITLE
deis create fails on remote non-atomically

### ISSUE THREAD

**Issue by haf** [deis/deis#3696] opened 2015-05-15 13:06 UTC
Run deis create with a remote named 'deis'. Watch it fail. Try to redo it. Fails 'non unique'.

**Comment by Joshua-Anderson** [comment] 2015-05-15 13:13
What behavior do you expect in this situation?

**Comment by haf** [comment] 2015-05-15 13:17
Either the create command fails or doesn't. It doesn't succeed in interacting with the controller but fail locally. Transactions or Compensatory Action on failure. A tiny HSM/Saga.

**Comment by bacongobbler** [comment] 2015-05-15 21:43
sounds like a duplicate of https://github.com/deis/deis/issues/3005.

**Comment by bacongobbler** [comment] 2015-07-16 18:32
this has been fixed in https://github.com/deis/deis/pull/3767.

**Closed by bacongobbler** 2015-07-16 18:32 UTC
Labels: client, controller
