### ISSUE TITLE
login and register hangs

### ISSUE THREAD

**Issue by ineu** [deis/deis#3291] opened 2015-03-13 13:52 UTC
Hi guys.
I've built new cluster of 3 bare metal machines living in Hetzner. CoreOS beta (607), Deis 1.4.1.
Immediately after setup I was able to register, but few hours later both `deis register` and `deis login` hangs after entering all values. If I interrupt it with `C-c`, I see
```
^CTraceback (most recent call last):
  File "<string>", line 2113, in <module>
  File "<string>", line 2109, in main
  File "<string>", line 2052, in _dispatch_cmd
  File "<string>", line 801, in auth_login
  File "/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/requests.sessions", line 504, in post
  File "<string>", line 158, in request
  File "/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/requests.sessions", line 461, in request
  File "/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/requests.sessions", line 573, in send
  File "/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/requests.adapters", line 370, in send
  File "/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/requests.packages.urllib3.connectionpool", line 518, in urlopen
  File "/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/requests.packages.urllib3.connectionpool", line 353, in _make_request
  File "/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/httplib", line 1045, in getresponse
  File "/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/httplib", line 409, in begin
  File "/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/httplib", line 365, in _read_status
  File "/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/socket", line 476, in readline
KeyboardInterrupt
```
I've checked etcd logs on all servers, two are fine, one emits errors:
```
Mar 13 13:43:24 staging-coreos-2 etcd[625]: [etcd] Mar 13 13:43:24.551 INFO      | a6efd505a1c5420f8ab1c11af55571b3: warning: heartbeat time out peer="2fdc33aa2bb347aaa1da0d742d41190c" missed=1 backoff="2s"
Mar 13 13:44:08 staging-coreos-2 etcd[625]: [etcd] Mar 13 13:44:08.551 INFO      | a6efd505a1c5420f8ab1c11af55571b3: warning: heartbeat time out peer="2fdc33aa2bb347aaa1da0d742d41190c" missed=1 backoff="2s"
Mar 13 13:44:24 staging-coreos-2 etcd[625]: [etcd] Mar 13 13:44:24.761 INFO      | a6efd505a1c5420f8ab1c11af55571b3: warning: heartbeat time out peer="2fdc33aa2bb347aaa1da0d742d41190c" missed=1 backoff="2s"
Mar 13 13:44:34 staging-coreos-2 etcd[625]: [etcd] Mar 13 13:44:34.051 INFO      | a6efd505a1c5420f8ab1c11af55571b3: warning: heartbeat time out peer="2fdc33aa2bb347aaa1da0d742d41190c" missed=1 backoff="2s"
```
Time is the same on all three servers (up to seconds), though `ceph -s` reports
```
     health HEALTH_WARN clock skew detected on mon.staging-coreos-2, mon.staging-coreos-3
```
Though maybe ceph requires more precise time. Ntpd is running on all servers.
What can I do to further investigate the issue? Thank you.

**Comment by ineu** [comment] 2015-03-13 14:16
deis-controller logs:
```
Mar 13 14:06:55 staging-coreos-1 sh[23009]: 2015-03-13T14:06:55Z b338afdb5f45 confd[84]: ERROR Config check failed: exit status 1
Mar 13 14:09:01 staging-coreos-1 sh[23009]: [2015-03-13 14:09:00 +0000] [90] [CRITICAL] WORKER TIMEOUT (pid:119)
Mar 13 14:09:01 staging-coreos-1 sh[23009]: [2015-03-13 14:09:00 +0000] [119] [INFO] Worker exiting (pid: 119)
Mar 13 14:09:01 staging-coreos-1 sh[23009]: [2015-03-13 14:09:01 +0000] [3049] [INFO] Booting worker with pid: 3049
Mar 13 14:09:01 staging-coreos-1 sh[23009]: 2015-03-13T14:09:01Z b338afdb5f45 confd[84]: ERROR Config check failed: exit status 1
Mar 13 14:10:29 staging-coreos-1 sh[23009]: 2015-03-13T14:10:29Z b338afdb5f45 confd[84]: ERROR Config check failed: exit status 1
Mar 13 14:13:21 staging-coreos-1 sh[23009]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Mar 13 14:13:23 staging-coreos-1 sh[23009]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Mar 13 14:13:23 staging-coreos-1 sh[23009]: 2015-03-13T14:13:22Z b338afdb5f45 confd[84]: ERROR 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Mar 13 14:13:27 staging-coreos-1 sh[23009]: 2015-03-13T14:13:27Z b338afdb5f45 confd[84]: ERROR Config check failed: exit status 1

```

**Comment by ineu** [comment] 2015-03-13 15:32
Finally it worked. I had to restart controller and, more strange, routers.

**Comment by bacongobbler** [comment] 2015-03-13 15:36
that does sound odd. Those confd errors from the controller are etcd connection errors (could be network latency, bad connection etc.) but nothing else stands out to me.

As for the clock skew, would you mind checking to see if https://github.com/deis/deis/pull/3222 works for you? Thanks!

**Comment by ineu** [comment] 2015-03-13 15:58
@bacongobbler 
Time shift is not really that much for me. Please see how it differs:
```
core@staging-coreos-1 ~ $ sudo systemctl stop ntpd && sudo ntpdate pool.ntp.org && sudo systemctl start ntpd
13 Mar 15:47:22 ntpdate[13973]: adjust time server 176.9.40.142 offset -0.125435 sec

core@staging-coreos-2 ~ $ sudo systemctl stop ntpd && sudo ntpdate pool.ntp.org && sudo systemctl start ntpd
13 Mar 15:47:41 ntpdate[5138]: adjust time server 5.9.49.12 offset 0.002371 sec

core@staging-coreos-3 ~ $ sudo systemctl stop ntpd && sudo ntpdate pool.ntp.org && sudo systemctl start ntpd
13 Mar 15:47:51 ntpdate[22860]: adjust time server 46.4.28.205 offset 0.000287 sec
```
So nothing is more than 0.12 second. Is it too much for Ceph?

**Comment by bacongobbler** [comment] 2015-03-13 15:59
that should be completely fine. I guess then the main issue would be the network latency with etcd that occurred. If you get logs, I'd check with upstream to see if there's a potential issue there.

**Comment by ineu** [comment] 2015-03-13 16:02
That's weird as servers are connected via switch in the same rack, so no possible routing latency. Which logs should I try to gather?

**Comment by bacongobbler** [comment] 2015-03-13 16:13
I'd gather etcd logs from all hosts, traffic logs, maybe monitoring data if you have it available

**Comment by aledbf** [comment] 2015-03-13 16:17
@ineu the threshold to show the warning is 0.05 seconds
http://ceph.com/docs/master/rados/troubleshooting/troubleshooting-mon/#clock-skews

**Comment by ineu** [comment] 2015-03-16 15:45
@aledbf 
Thank you, good to know. ATM ceph health is ok, so no time difference.

@bacongobbler 
etcd is fine now, no errors, but still 503. nginx config returns 503 because of https://github.com/deis/deis/blob/master/router/image/templates/nginx.conf#L91.
For some reason etcd doesn't containt 'host' key:
```
core@staging-coreos-1 ~ $ etcdctl ls --recursive /deis/controller
/deis/controller/webEnabled
/deis/controller/builderKey
/deis/controller/protocol
/deis/controller/registrationEnabled
/deis/controller/secretKey
/deis/controller/unitHostname
```

though deis-controller is running:
```
core@staging-coreos-1 ~ $ fleetctl status deis-controller
● deis-controller.service - deis-controller
   Loaded: loaded (/run/fleet/units/deis-controller.service; linked-runtime; vendor preset: disabled)
   Active: active (running) since Mon 2015-03-16 13:40:12 UTC; 2h 2min ago
  Process: 18973 ExecStartPre=/bin/sh -c docker inspect deis-controller >/dev/null && docker rm -f deis-controller || true (code=exited, status=0/SUCCESS)
  Process: 18949 ExecStartPre=/bin/sh -c IMAGE=`/run/deis/bin/get_image /deis/controller` && docker history $IMAGE >/dev/null || docker pull $IMAGE (code=exited, status=0/SUCCESS)
 Main PID: 18982 (sh)
   CGroup: /system.slice/deis-controller.service
           ├─18982 /bin/sh -c IMAGE=`/run/deis/bin/get_image /deis/controller` && docker run --name deis-controller --rm -p 8000:8000 -e EXTERNAL_PORT=8000 -e HOST=$COREOS_PRIVATE_IPV4 -v /var/run/fleet.sock:/var/run/fleet.sock -v /var/lib/deis/store:/data $IMAGE
           └─18999 docker run --name deis-controller --rm -p 8000:8000 -e EXTERNAL_PORT=8000 -e HOST=192.168.0.1 -v /var/run/fleet.sock:/var/run/fleet.sock -v /var/lib/deis/store:/data deis/controller:v1.4.1

Mar 16 15:42:21 staging-coreos-1 sh[18982]: controller: waiting for confd to write initial templates...
Mar 16 15:42:26 staging-coreos-1 sh[18982]: controller: waiting for confd to write initial templates...
Mar 16 15:42:31 staging-coreos-1 sh[18982]: controller: waiting for confd to write initial templates...
```

Don't know if this 'waiting for confd' lines is normal.

**Comment by bacongobbler** [comment] 2015-03-16 15:55
those lines are not normal. What's happening here is that the controller's waiting on some other component to come up. Could you please dump `etcdctl ls / --recursive` for me?

**Comment by ineu** [comment] 2015-03-17 06:12
@bacongobbler Here it is: https://gist.github.com/ineu/22ad40dcf4d1ece1deb7 (skipped users and services sections).

**Comment by aledbf** [comment] 2015-03-17 11:42
@ineu from your output the database is not running (deis-database)
```
/deis/database
/deis/database/adminUser
/deis/database/engine
/deis/database/adminPass
/deis/database/name
/deis/database/password
/deis/database/user
/deis/database/bucketName
```

(host and port are missing)

you can restart the component running `fleetctl stop deis-database && fleetctl start database` from any node in the cluster.

**Comment by ineu** [comment] 2015-03-17 12:39
well, it is running:
```
core@staging-coreos-1 ~ $ fleetctl list-units | grep database
deis-database.service						2fdc33aa.../192.168.0.1	active	running
```
```
core@staging-coreos-1 ~ $ systemctl status deis-database
● deis-database.service - deis-database
   Loaded: loaded (/run/fleet/units/deis-database.service; linked-runtime; vendor preset: disabled)
   Active: active (running) since Fri 2015-03-13 07:55:40 UTC; 4 days ago
  Process: 1708 ExecStartPre=/bin/sh -c docker inspect deis-database >/dev/null 2>&1 && docker rm -f deis-database >/dev/null 2>&1 || true (code=exited, status=0/SUCCESS)
  Process: 1679 ExecStartPre=/bin/sh -c IMAGE=`/run/deis/bin/get_image /deis/database` && docker history $IMAGE >/dev/null || docker pull $IMAGE (code=exited, status=0/SUCCESS)
  Process: 1672 ExecStartPre=/bin/sh -c docker inspect deis-database-data >/dev/null 2>&1 || docker run --name deis-database-data -v /var/lib/postgresql ubuntu-debootstrap:14.04 /bin/true (code=exited, status=0/SUCCESS)
 Main PID: 1721 (sh)
   CGroup: /system.slice/deis-database.service
           ├─1721 /bin/sh -c IMAGE=`/run/deis/bin/get_image /deis/database` && docker run --name deis-database --volumes-from=deis-database-data -p 5432:5432 -e EXTERNAL_PORT=5432 -e HOST...
           └─1739 docker run --name deis-database --volumes-from=deis-database-data -p 5432:5432 -e EXTERNAL_PORT=5432 -e HOST=192.168.0.1 deis/database:v1.4.1
```
But there are errors in the journal indeed:
```
Mar 17 12:35:49 staging-coreos-1 sh[1721]: wal_e.retries WARNING  MSG: retrying after encountering exception
Mar 17 12:35:49 staging-coreos-1 sh[1721]: DETAIL: Exception information dump:
Mar 17 12:35:49 staging-coreos-1 sh[1721]: Traceback (most recent call last):
Mar 17 12:35:49 staging-coreos-1 sh[1721]: File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 62, in shim
Mar 17 12:35:49 staging-coreos-1 sh[1721]: return f(*args, **kwargs)
Mar 17 12:35:49 staging-coreos-1 sh[1721]: File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/s3/s3_deleter.py", line 27, in _delete_batch
Mar 17 12:35:49 staging-coreos-1 sh[1721]: bucket.delete_keys([key.name for key in page])
Mar 17 12:35:49 staging-coreos-1 sh[1721]: File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 726, in delete_keys
Mar 17 12:35:49 staging-coreos-1 sh[1721]: while delete_keys2(headers):
Mar 17 12:35:49 staging-coreos-1 sh[1721]: File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 714, in delete_keys2
Mar 17 12:35:49 staging-coreos-1 sh[1721]: data=data)
Mar 17 12:35:49 staging-coreos-1 sh[1721]: File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
Mar 17 12:35:49 staging-coreos-1 sh[1721]: retry_handler=retry_handler
Mar 17 12:35:49 staging-coreos-1 sh[1721]: File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1070, in make_request
Mar 17 12:35:49 staging-coreos-1 sh[1721]: retry_handler=retry_handler)
Mar 17 12:35:49 staging-coreos-1 sh[1721]: File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1029, in _mexe
Mar 17 12:35:49 staging-coreos-1 sh[1721]: raise ex
Mar 17 12:35:49 staging-coreos-1 sh[1721]: timeout: timed out
```
`ceph -s` shows `HEALTH OK`

**Comment by ineu** [comment] 2015-03-17 12:40
Restart helped indeed. Any idea why it could be failing and what should I do to prevent it in the future?

**Comment by aledbf** [comment] 2015-03-17 12:43
@ineu you saw this issue https://github.com/deis/deis/issues/2741

**Comment by ineu** [comment] 2015-03-17 12:53
@aledbf Ok, I see. Any way to avoid it before #2701 is merged?

**Comment by carmstrong** [comment] 2015-03-20 17:42
> Ok, I see. Any way to avoid it before #2701 is merged?

The root here is that the database component can no longer communicate with `store-gateway`. However, there are a few different causes of gateway troubles. Can you get the gateway logs and `ceph -s` output the next time this happens?

**Comment by ineu** [comment] 2015-03-23 09:14
@carmstrong I've posted logs here: https://github.com/deis/deis/issues/2741#issuecomment-83932022
`ceph -s` and `journalctl -u etcd` are fine.

**Comment by ineu** [comment] 2015-03-27 18:38
As a workaround I've implemented simple guard and wrapped it into systemd unit:
```bash
#!/bin/bash

while true; do
    if ! etcdctl get /deis/database/host >/dev/null 2>&1; then
        echo "Key not found, restarting deis-database"
        fleetctl stop deis-database
        sleep 5
        fleetctl start deis-database
    fi
    sleep 60
done
```

And looking at its logs for today:
```
Mar 27 06:59:48 staging-coreos-3 systemd[1]: Started Simple guard for deis-database.
Mar 27 10:32:54 staging-coreos-3 deis-database-guard.sh[26972]: Key not found, restarting deis-database
Mar 27 10:32:55 staging-coreos-3 deis-database-guard.sh[26972]: Unit deis-database.service loaded on 2fdc33aa.../192.168.0.1
Mar 27 10:33:02 staging-coreos-3 deis-database-guard.sh[26972]: Unit deis-database.service launched on 2fdc33aa.../192.168.0.1
Mar 27 14:11:08 staging-coreos-3 deis-database-guard.sh[26972]: Key not found, restarting deis-database
Mar 27 14:11:10 staging-coreos-3 deis-database-guard.sh[26972]: Unit deis-database.service loaded on 2fdc33aa.../192.168.0.1
Mar 27 14:11:17 staging-coreos-3 deis-database-guard.sh[26972]: Unit deis-database.service launched on 2fdc33aa.../192.168.0.1
Mar 27 17:50:30 staging-coreos-3 deis-database-guard.sh[26972]: Key not found, restarting deis-database
Mar 27 17:50:32 staging-coreos-3 deis-database-guard.sh[26972]: Unit deis-database.service loaded on 2fdc33aa.../192.168.0.1
Mar 27 17:50:39 staging-coreos-3 deis-database-guard.sh[26972]: Unit deis-database.service launched on 2fdc33aa.../192.168.0.1
```
So this problem appeared three times for me today.

Output of `journalctl -u etcd` on every machine in the cluster is ok, no network splits, no quorum losses.
Time difference on servers is tiny:
```
> $ pssh -i -H 'coreos-1 coreos-2 coreos-3' ntpdate -q 0.coreos.pool.ntp.org | grep adjust                                                                   
27 Mar 18:35:54 ntpdate[4808]: adjust time server 5.9.122.148 offset 0.001519 sec
27 Mar 18:35:54 ntpdate[6859]: adjust time server 46.4.39.238 offset -0.000423 sec
27 Mar 18:35:55 ntpdate[15398]: adjust time server 85.10.246.226 offset 0.000806 sec
```

Output of `journalctl -u deis-store-gateway@1 --since today`
```
-- Logs begin at Thu 2015-03-19 06:04:17 UTC, end at Fri 2015-03-27 18:25:48 UTC. --
Mar 27 01:31:58 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [24121533]
Mar 27 01:35:17 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [24125633]
Mar 27 02:30:33 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [24194551]
Mar 27 02:42:20 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [24209201]
Mar 27 04:30:45 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [24344258]
Mar 27 04:58:00 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [24378136]
Mar 27 06:32:33 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [24496002]
Mar 27 06:39:36 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [24504737]
Mar 27 08:18:52 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [24631109]
Mar 27 11:44:43 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [24892189]
Mar 27 13:48:41 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25048751]
Mar 27 14:10:50 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25077019]
Mar 27 14:11:52 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25078328]
Mar 27 14:25:42 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25095924]
Mar 27 14:43:25 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25119153]
Mar 27 14:47:20 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25124349]
Mar 27 14:54:36 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25133927]
Mar 27 15:01:57 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25143589]
Mar 27 15:04:09 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25146526]
Mar 27 15:23:57 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25172637]
Mar 27 16:17:51 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25243469]
Mar 27 16:26:34 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25254503]
Mar 27 16:42:52 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25275051]
Mar 27 17:52:30 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [25363857]
```

Ceph is ok:
```
root@30e039d6b63f:/app# ceph -s
    cluster 3964dde2-a9c2-49b2-b490-dea0655da56b
     health HEALTH_OK
```

**Comment by gabrtv** [comment] 2015-03-27 19:07
@ineu thanks for the detailed debug output.  Extremely helpful.  

I have a strong suspicion the issue is caused by the database publishing logic.  The `/deis/database/host` key is written with a TTL inside a loop that can potentially be interrupted by periodic backups.  If backups take longer than the TTL, the keys can disappear from etcd.  I suspect that's what is happening here.

To resolve this, we need to decouple _publishing_ from _period backups_.  The best way to do this is to rewrite the database init in Go and use goroutines for background tasks, as we do elsewhere.

**Comment by ngbinh** [comment] 2015-04-22 17:33
We got hit by this issue today.

**Comment by carmstrong** [comment] 2015-04-25 00:30
Closing - we're tracking the root issue in #2741.

**Closed by carmstrong** 2015-04-25 00:30 UTC
