### ISSUE TITLE
Errors from platform

### ISSUE THREAD

**Issue by haf** [deis/deis#3596] opened 2015-04-29 15:06 UTC
Hi,

I started an earlier thread, but it got filled up with other production issues related to the upgrade and now I've had time to stabilise and take another deeper look.

Are these benign:?

```
 Apr 29 17:00:54 deis-1 sh: 2015-04-29T15:00:54Z fceb2accfbf5 confd[1484]: ERROR template: builder:59:47: executing "builder" at <getv "/deis/registry...>: error calling getv: key does not exist
Apr 29 17:00:54 deis-1 sh: 2015-04-29T15:00:54Z fceb2accfbf5 confd[1484]: ERROR template: check-repos:15:49: executing "check-repos" at <getv "/deis/registry...>: error calling getv: key does not exist
Apr 29 17:00:54 deis-1 sh: 2015-04-29T15:00:54Z fceb2accfbf5 confd[1484]: ERROR template: push-images:9:70: executing "push-images" at <getv "/deis/registry...>: error calling getv: key does not exist
Apr 29 17:00:55 deis-3 sh: Error:  100: Key not found (/deis/registry/masterLock) [48873069] 
```

**Comment by bacongobbler** [comment] 2015-04-29 15:09
Could you please check if your registry is up? This looks like a duplicate of https://github.com/deis/deis/issues/3563

**Comment by bacongobbler** [comment] 2015-04-29 15:17
Could you also please tell me which version of Deis you're running as well as on what platform?

**Comment by haf** [comment] 2015-04-29 15:22
Deis 1.5.2. CoreOS 633.1.0 (there was no mention of how *not* to upgrade to the *very latest* CoreOS release in the Upgrade docs, just how to temporarily enable it)

Here's the registry's output:

```
● deis-registry@1.service - deis-registry
   Loaded: loaded (/run/fleet/units/deis-registry@1.service; linked-runtime; vendor preset: disabled)
   Active: active (running) since Tue 2015-04-28 22:27:04 UTC; 16h ago
  Process: 15680 ExecStartPre=/bin/sh -c docker inspect deis-registry >/dev/null 2>&1 && docker rm -f deis-registry || true (code=exited, status=0/SUCCESS)
  Process: 14973 ExecStartPre=/bin/sh -c IMAGE=`/run/deis/bin/get_image /deis/registry` && docker history $IMAGE >/dev/null 2>&1 || docker pull $IMAGE (code=exited, status=0/SUCCESS)
  Process: 14897 ExecStartPre=/usr/bin/etcdctl mkdir /deis/cache >/dev/null 2>&1 (code=exited, status=4)
 Main PID: 15698 (sh)
   CGroup: /system.slice/system-deis\x2dregistry.slice/deis-registry@1.service
           ├─15698 /bin/sh -c IMAGE=`/run/deis/bin/get_image /deis/registry` && docker run --name deis-registry --rm -p 5000:5000 -e EXTERNAL_PORT=5000 -e HOST=$COREOS_PRIVATE_IPV4 $IMAGE
           └─15715 docker run --name deis-registry --rm -p 5000:5000 -e EXTERNAL_PORT=5000 -e HOST=10.133.186.27 deis/registry:v1.5.2

Apr 29 13:39:03 deis-3 sh[15698]: Error:  100: Key not found (/deis/registry/masterLock) [48810102]
Apr 29 13:49:55 deis-3 sh[15698]: Error:  100: Key not found (/deis/registry/masterLock) [48818455]
Apr 29 14:11:44 deis-3 sh[15698]: Error:  100: Key not found (/deis/registry/masterLock) [48835212]
Apr 29 14:28:07 deis-3 sh[15698]: Error:  100: Key not found (/deis/registry/masterLock) [48847867]
Apr 29 14:49:58 deis-3 sh[15698]: Error:  100: Key not found (/deis/registry/masterLock) [48864627]
Apr 29 14:55:31 deis-3 sh[15698]: Error:  100: Key not found (/deis/registry/masterLock) [48868931]
Apr 29 15:00:55 deis-3 sh[15698]: Error:  100: Key not found (/deis/registry/masterLock) [48873069]
Apr 29 15:06:28 deis-3 sh[15698]: Error:  100: Key not found (/deis/registry/masterLock) [48877321]
Apr 29 15:11:57 deis-3 sh[15698]: Error:  100: Key not found (/deis/registry/masterLock) [48881549]
Apr 29 15:17:25 deis-3 sh[15698]: Error:  100: Key not found (/deis/registry/masterLock) [48885767]
```

**Comment by bacongobbler** [comment] 2015-04-29 15:27
Yes, those errors definitely look like your master lock is expiring as per #3563.

Which cloud platform is this? DO? EC2? Azure?

**Comment by haf** [comment] 2015-04-29 15:33
DigitalOcean.

**Comment by bacongobbler** [comment] 2015-04-30 20:37
Closing as a duplicate of #3563. I checked and confirmed that is the root issue at hand here, so I'd be interested to see if the fix in https://github.com/deis/deis/pull/3592 works for you.

**Closed by bacongobbler** 2015-04-30 20:37 UTC
