### ISSUE TITLE
restarting builder requires app destroy

### ISSUE THREAD

**Issue by lorieri** [deis/deis#3903] opened 2015-06-19 01:49 UTC
if you stop and start builder by deisctl you can't rebuild the app

```
lorieri@local:~/git/myhack 1 $ git push deis master
/usr/local/bin/gitreceive: line 33: /home/git/myhack.git/hooks/pre-receive: No such file or directory
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
lorieri@local:~/git/myhack 128 $ deis destroy

 !    WARNING: Potentially Destructive Action
 !    This command will destroy the application: myhack
 !    To proceed, type "myhack" or re-run this command with --confirm=myhack

> myhack
Destroying myhack...
done in 0s
Git remote deis removed
lorieri@local:~/git/myhack 0 $ deis create myhack
Creating application... done, created myhack
Git remote deis added
lorieri@local:~/git/myhack 0 $ git push deis master
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 731 bytes | 0 bytes/s, done.
Total 5 (delta 0), reused 0 (delta 0)
```

**Comment by lorieri** [comment] 2015-06-19 02:28
it happened only with heroku build

**Comment by szymonpk** [comment] 2015-06-19 05:18
I've encountered this once, when my cluster moved builder from one node to another. As quick workaround (if you don't want to destroy app), it's sufficient to log to builder instance and execute `rm -rf /home/git/myhack.git`. It will be recreated with next push.

**Comment by lorieri** [comment] 2015-06-19 06:38
Thanks :) Very useful!
It didn't migrate.

**Comment by bacongobbler** [comment] 2015-07-16 19:36
closing as a duplicate of #3458

**Closed by bacongobbler** 2015-07-16 19:36 UTC
Labels: builder
