### ISSUE TITLE
"enabling proxy protocol failed"

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#4835] opened 2016-01-06 08:40 UTC
I got this when running provision-aws-cluster.sh:

```
Enabling proxy protocol
Error: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Unexpected HTTP status code]) [0]
# WARNING: Enabling proxy protocol failed.
# Ensure that the private key in cloudformation.json is added to
# your ssh-agent, then enable proxy protocol before continuing:
#
# deisctl config router set proxyProtocol=1

Your Deis cluster was deployed to AWS CloudFormation as stack deis0.

Now run this command in your shell:
export DEISCTL_TUNNEL=XX.XX.XX.XX
and continue to follow the documentation for "Installing the Deis Platform."
```

Running it manually does:

```
 deis/contrib/aws — master • →  deisctl config router set proxyProtocol=1
Error: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Put http://127.0.0.1:4001/v2/keys/deis/router/proxyProtocol: dial tcp 127.0.0.1:4001: getsockopt: connection refused]) [0]
```

**Comment by rstacruz** [comment] 2016-01-06 08:53
oh man, i think i screwed up by having a different `deisctl` version than what I was provisioning with.

**Comment by krancour** [comment] 2016-01-06 14:49
The error message is telling you the likely cause-- that the private key for ssh'ing to nodes (required for tunneling) is not in your ssh agent.

I'll assume you have the correct .pem laying around somewhere.  If so:

```
$ ssh-add path/to/your.pem
```

**Comment by rstacruz** [comment] 2016-01-07 03:33
I already did, and it shows up in my `ssh-add -l`. Lemme try again and paste any more debug info when I have them.

**Comment by krancour** [comment] 2016-01-07 04:30
If the key is already in your agent, you can attempt troubleshooting the connection like so:

```
$ ssh -vvv core@XX.XX.XX.XX
```

**Comment by rstacruz** [comment] 2016-01-07 04:46
Alright. At the surface it seems like the problem might be the inability to connect to http://127.0.0.1:4001, but I'll let you know in a few hours :-)

**Comment by bacongobbler** [comment] 2016-01-07 06:08
@rstacruz since `deisctl` works through an SSH tunnel, that would be fleet attempting to connect to etcd. You might want to SSH into your cluster and troubleshoot why etcd is down. :)

**Comment by rstacruz** [comment] 2016-01-07 06:09
Neat. Will there be a more polished provision-aws-cluster.sh tool in the
works?

**Comment by bacongobbler** [comment] 2016-01-07 06:15
> Will there be a more polished provision-aws-cluster.sh tool in the works?

First we need to determine how etcd failed to bootstrap, then we can figure out how to fix this problem (or if it's a duplicate of previous troubleshooting problems). Can you do a `ssh core@xx.xx.xx.xx`, then a `sudo journalctl -u --no-pager etcd`, where xx.xx.xx.xx is the node used you censored as the target for DEISCTL_TUNNEL in the logs?

**Comment by rstacruz** [comment] 2016-01-07 06:17
Ah, sorry, the question was a bit of a lateral thought—I meant, would there
be a separate AWS provisioning/maintenance tool released in the future that
doesn't require fetching the entire source tree to work?

Because that sounds pretty cool and Id love to help out.

**Comment by bacongobbler** [comment] 2016-01-07 06:20
We have one tool for that called `rigger`: https://github.com/deis/rigger

In v2 we have a tool called [helm](http://helm.sh/) to provision Deis.

**Comment by rstacruz** [comment] 2016-01-07 07:06
Okay, I got this:

```
Waiting for instances to pass initial health checks (460s) ...
Waiting for instances to pass initial health checks (450s) ...
Instances are available:
i-7fdeexxx      52.62.XX.XX     m3.medium       ap-southeast-2b running
i-78deeyyy      52.62.YY.YY    m3.medium       ap-southeast-2b running
i-9f155zzz      52.62.ZZ.ZZ    m3.medium       ap-southeast-2a running
```

and after `ssh -vvv core@52.62.XX.XX`:

```
Welcome to Deis                 Powered by CoreOS
core@ip-10-21-2-187 ~ $
```

doing `ps aux | grep etcd` says its running. Then:

```
$ sudo journalctl -u --no-pager etcd
Failed to add match 'etcd': Invalid argument
```

**Comment by rstacruz** [comment] 2016-01-07 07:07
but `journalctl` has these:

```
Jan 07 07:07:08 ip-10-21-2-187.ap-southeast-2.compute.internal sdnotify-proxy[1373]: E0107 07:07:08.117594 00001 network.go:53] Failed to retrieve network config: client: etcd cluster is unavai
Jan 07 07:07:08 ip-10-21-2-187.ap-southeast-2.compute.internal etcd2[797]: proxy: zero endpoints currently available
Jan 07 07:07:09 ip-10-21-2-187.ap-southeast-2.compute.internal etcd2[797]: proxy: zero endpoints currently available
Jan 07 07:07:09 ip-10-21-2-187.ap-southeast-2.compute.internal etcd2[797]: proxy: zero endpoints currently available
```

**Comment by rstacruz** [comment] 2016-01-07 07:09
`etcdctl` output:

```
$ etcdctl get
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: etcd member http://127.0.0.1:2379 has no leader
error #1: client: etcd member http://127.0.0.1:4001 has no leader
```

**Comment by rstacruz** [comment] 2016-01-07 07:12
From another node:

> Jan 07 07:11:40 ip-10-21-XX-XX.ap-southeast-2.compute.internal sdnotify-proxy[1473]: E0107 07:11:40.361605 00001 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
> Jan 07 07:11:40 ip-10-21-XX-XX.ap-southeast-2.compute.internal etcd2[800]: could not get cluster response from http://10.21.XX.XX:2380: Get http://10.21.XX.XX:2380/members: dial tcp 10.21.XX.XX:2380: i/o timeout

**Comment by rstacruz** [comment] 2016-01-07 07:18
I'm trying again now with 3 x `m3.large` and with a new discovery URL and seeing if that changes anything.

**Comment by rstacruz** [comment] 2016-01-07 07:39
Okay, it turns out fine now! I guess m3.medium was a bad idea?

**Comment by krancour** [comment] 2016-01-07 15:45
m3.medium is fine.  Since you have just explicitly mentioned creating a new discovery URL... were previous attempts all made without creating a new discovery URL each time?  That would definitely stop etcd from coming up clean.  Without etcd, fleet also fails, and thus so does deisctl.

**Comment by rstacruz** [comment] 2016-01-07 15:46
ah, right. no, i didn't make a new discovery url. perhaps I should've ;)

**Closed** 2016-01-07 18:12 UTC
