### ISSUE TITLE
Cli tool for release process

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4038] opened 2015-07-15 17:09 UTC
Right now our deis release process involves following steps on a spreadsheet. That's spreadsheet-driven-deployment! And it makes me :cry:.

@mboersma had the idea of creating a cli tool that could automate most of the steps:
- git process (tags, pushes, etc.)
- jenkins process (kicking off builds, waiting for them, etc.)
- doc process (wait for a human to add release notes, configure human readable docs where appropriate)

We could eventually move this (or part of it) into a Jenkins job to benefit from being kicked off by an upstream part of a release pipeline, but we gotta start somewhere to codify our release process in a more concrete fashion.

**Comment by carmstrong** [comment] 2015-07-15 17:18
Dupe of #4002 - that should be closed in favor of this one, methinks

**Comment by mboersma** [comment] 2015-07-15 19:57
:+1:

**Comment by bacongobbler** [comment] 2016-06-09 22:42
see https://github.com/deis/deisrel

**Closed by bacongobbler** 2016-06-09 22:42 UTC
Labels: test-infrastructure
