### ISSUE TITLE
deis releases:destroy 

### ISSUE THREAD

**Issue by udragon** [deis/deis#4780] opened 2015-12-06 22:53 UTC
Hello guys,

I deployed a medium-size DEIS environment, containing 7 CoreOS nodes with about 40 apps. I have 120GB x 7 ~ 1TB of storage and it's just not enough. So I decided to delete the old releases to free space (each of the apps has some), but there isn't such option.

I would like to have something like:
$ deis releases:destroy --app=myapp --release=v1

I have to say it seems to me rather weird to have my images 7 times around the cluster (replica in each node). If you think about large clusters (lets say 100 nodes) it is such a waste. what would happen if I share /var/lib/docker via nfs between all nodes in the cluster ? will it work?
 
Thanks,
Ido

**Comment by Joshua-Anderson** [comment] 2015-12-07 03:29
I recommend looking at the techniques listed in #3675, which will help cleanup unused images.

I think a better cleanup solution is something that would be nice to have, because I agree you're unlikely to want to roll back to really old releases. Another proposed solution is to only save the last few releases, with older releases being deleted. Something that has been hampering this is that the docker image registry didn't have a delete option, so it's hard to implement a delete option in deis.

It's not nearly as wasteful in large clusters as you might think though. The image registry stores 3 replicas of the images. Then, the app is only downloaded onto containers that are running it, which in a large cluster is a small subset of machines.

**Comment by udragon** [comment] 2015-12-07 16:22
Thank you for the comment, I'll try using the docker cleanup service mentioned there.
How about using a centralized storage and mounting /var/lib/docker of all nodes via nfs (same directory for all)? Do you have an experience with such architectures?

**Comment by bacongobbler** [comment] 2016-01-22 00:59
closing as a duplicate of #3698.

**Closed by bacongobbler** 2016-01-22 00:59 UTC
