### ISSUE TITLE
Azure: Investigate Router "[emerg] 16#0: bind() to 0.0.0.0:2222 failed (98: Address already in use)"

### ISSUE THREAD

**Issue by chrisgeo** [deis/deis#3466] opened 2015-04-13 14:12 UTC
On Azure, and sometimes on Vagrant, I see the error:

``` [emerg] 16#0: bind() to 0.0.0.0:2222 failed (98: Address already in use) ```

on the router process.

With a multiple router setup (3 for 5 boxes for example), one failing causes certain processes e.g. ``` deis ps:list ``` to return ```503``.

Right now, I haven't found any other processes using port 2222 aside from Azure opening port 2222 to the public, I'm unsure what else is using this point on the host.

My best guess currently is that another instance of router attempted to start up and caused the collision - but I have no actual proof of that yet.

Logs of two recent malfunctioning router issues in a three router cluster:
[router@1](https://www.dropbox.com/s/h4k45xd4633s5bk/router_1.log?dl=0)
[router@2](https://www.dropbox.com/s/udva3li48wq0i3b/router_2.log?dl=0)

I'm going to try and carve out some time to look into this more deeply.

**Comment by carmstrong** [comment] 2015-04-13 15:39
@chrisgeo should we close #3442 in favor of this issue?

**Comment by chrisgeo** [comment] 2015-04-13 16:55
@carmstrong Yes please

**Comment by carmstrong** [comment] 2015-04-17 21:50
> I'm going to try and carve out some time to look into this more deeply.

Please let us know if you find any more information on this. My only thought is that the Docker daemon isn't immediately releasing the listening ports upon a container exit, and you're hitting a race condition with the new router process not being able to use the port.

**Comment by chrisgeo** [comment] 2015-04-19 03:40
@carmstrong Sorry about that - I'll close it out until it hits again as I haven't had time to investigate the logs I've collected. Like the other issue similar to this though, I haven't seen anything in them.

**Comment by eax** [comment] 2015-04-29 08:47
I'm having this issue, too. I also see in `deisctl status router@<1,2,3>`
 `confd[41]: ERROR Config check failed: exit status 1`

here is the header for status output:

`● deis-router@2.service - deis-router`
   `Loaded: loaded (/run/fleet/units/deis-router@2.service; linked-runtime; vendor preset: disabled)`
   `Active: active (running) since Tue 2015-04-28 15:10:17 UTC; 17h ago`
  `Process: 57722 ExecStopPost=/usr/bin/docker rm -f deis-router (code=exited, status=0/SUCCESS)
  Process: 57836 ExecStartPre=/bin/sh -c docker inspect deis-router >/dev/null 2>&1 && docker rm -f `
`deis-router || true (code=exited, status=0/SUCCESS)`
  `Process: 57790 ExecStartPre=/bin/sh -c IMAGE=`/run/deis/bin/get_image /deis/router` && docker 
history $IMAGE >/dev/null 2>&1 || docker pull $IMAGE (code=exited, status=0/SUCCESS)
 Main PID: 57907 (sh)`
   `CGroup: /system.slice/system-deis\x2drouter.slice/deis-router@2.service
           ├─57907 /bin/sh -c IMAGE=`/run/deis/bin/get_image /deis/router` && docker run --name deis-router --rm -p 80:80 -p 2222:2222 -p 443:443 -e EXTERNAL_PORT=80 -e HOST=$COREOS_PRIVATE_IPV4 $IMAGE`
           `└─57953 docker run --name deis-router --rm -p 80:80 -p 2222:2222 -p 443:443 -e EXTERNAL_PORT=80 -e HOST=100.72.204.91 deis/router:v1.5.2`
`

**Comment by carmstrong** [comment] 2015-04-29 16:31
@eax Are you also  on Azure? Trying to find the common thread here.

**Comment by eax** [comment] 2015-04-29 18:23
Yes I'm running Deis 1.5.2 on Azure. I'm also looking for a clue for this problem. AFAIG, the problem is about 2222/tcp connection, but I can't find the root cause...

**Comment by bacongobbler** [comment] 2015-04-29 18:54
Hmm... Could Azure somehow be starting some other service on port 2222? What does `netstat` on the host show?

**Comment by eax** [comment] 2015-04-29 22:16
Actually that comes to my mind at first place. Checked (both in host and in
router container), but it seems only deis-router container gets this
port...

**Comment by carmstrong** [comment] 2015-04-30 05:12
@timfpark Do you know of anything Azure-specific that we'd hit here?

**Comment by eax** [comment] 2015-04-30 08:25
I might get it wrong but does this problem might be related to the `-p 2222:2222` and from the header log

` ├─57907 /bin/sh -c IMAGE=/run/deis/bin/get_image /deis/router&& docker run --name deis-router --rm -p 80:80 -p 2222:2222 -p 443:443 -e EXTERNAL_PORT=80 -e HOST=$COREOS_PRIVATE_IPV4 $IMAGE
└─57953 docker run --name deis-router --rm -p 80:80 -p 2222:2222 -p 443:443 -e EXTERNAL_PORT=80 -e HOST=100.72.204.91 deis/router:v1.5.2`

Is it possible to use `-p 22:2222` ? or something similar..

**Comment by carmstrong** [comment] 2015-04-30 16:18
> Is it possible to use -p 22:2222 ? or something similar..

This isn't the issue - it seems like something else is listening on 2222, or ports are remaining open longer than they should. We use `-p 2222:2222` because port 22 on the CoreOS host is the SSH daemon for the machine, which we certainly need access to.

**Comment by mboersma** [comment] 2015-06-17 16:51
Has anyone seen the `address already in use` router error on Azure in Deis v1.6.1 or v1.7.3?

**Comment by timfpark** [comment] 2015-06-17 17:01
I haven't with 1.6.1 or 1.7.2.

Tim

**Comment by mboersma** [comment] 2015-07-25 16:41
I'm closing this since it hasn't had an update in six weeks, and there doesn't look to be anything that Deis can fix. Please re-open this issue if this persists in the current [Deis v1.8](https://github.com/deis/deis/releases/tag/v1.8.0).

**Closed by mboersma** 2015-07-25 16:41 UTC
Labels: router
