### ISSUE TITLE
503 service unavailable when running `deis pull drone/drone:latest`

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4021] opened 2015-07-14 01:17 UTC
```zsh
$ deis pull drone/drone:latest -a drone
Creating build... 503 SERVICE UNAVAILABLE
Detail:
GET Image Error (404: {"error": "Invalid image ID"})
```

Deis 1.7.3

**Comment by bacongobbler** [comment] 2015-07-14 05:55
closing as a duplicate of https://github.com/deis/deis/issues/3550.

**Closed by bacongobbler** 2015-07-14 05:55 UTC
