### ISSUE TITLE
deisctl list Fails with Vagrant/Virtualbox

### ISSUE THREAD

**Issue by Californian** [deis/deis#3219] opened 2015-03-06 20:53 UTC
I have followed the steps in the installation guide to set up Deis on Vagrant (in fact, I have done so before on a different machine and been successful), but after I `export DEISCTL_TUNNEL=172.17.8.100` and run `deisctl list`, I get: `Error: failed initializing SSH client: timed out while initiating SSH connection`. I tried deleting the deis folder and removing all VMs and starting from the top, but to no avail. The only major difference between this machine and the one on which I was successful (that I can think of) is that I am `ssh`-ing into the one on which I am receiving the error.
Attempts to `ssh core@172.17.8.100` hang. `ssh-add -L` returns (what I assume is) the correct key.
Steps:
1. Install VirtualBox.
2. Install Vagrant (and vagrant-triggers plugin).
3. Clone the repository.
4. `make discovery-url`
5. `vagrant up`
6. Install deisctl.
7. `eval $(ssh-agent -s)` (I actually used backticks instead of $() but I can't figure out this markdown escaping nonsense).
8. `ssh-add ~/.vagrant.d/insecure_private_key`
9. `export DEISCTL_TUNNEL=172.17.8.100`
10. `deisctl list`
11. `Error: failed initializing SSH client: timed out while initiating SSH connection`

**Comment by bacongobbler** [comment] 2015-03-06 21:25
Considering that ssh-ing directly to the box fails, something could be up with the VMs or the network. What's the output of `vagrant status`?

**Comment by Californian** [comment] 2015-03-06 21:33
deis-01 running (virtualbox)
deis-02 running (virtualbox)
deis-03 running (virtualbox)

**Comment by mboersma** [comment] 2015-03-06 21:37
Try `vagrant ssh-config deis-01`. Probably it allocated a different port.

**Comment by Californian** [comment] 2015-03-06 22:01
So now I can ssh into deis-01 (you were correct, it was a different port and I had to use 127.0.0.1 for the IP address). I still get an error when I try to `deisctl list` though, any ideas there?

**Comment by mboersma** [comment] 2015-03-06 22:04
`export DEISCTL_TUNNEL=127.0.0.1:2222` (or whatever port was assigned for SSH) might get `deisctl` working. Although note that if the vagrant boxes didn't get assigned 172.17.8.100-102 as IPs, then the test domain `local3.deisapp.com` won't work.

**Comment by haf** [comment] 2015-03-07 14:54
You should ensure that vagrant says that is creates a `host` network and a `nat` network when you first start. You can then do `vagrant ssh deis-01 ip addr` to see what IP the first node has, that starts with `172`. Use this as the tunnel IP.

I also had to accept through my firewall, the connection outbound to the 172-network.

**Comment by Californian** [comment] 2015-03-07 18:58
It says `Adapter 1: nat` and `Adapter 2: hostonly` when booting. After `vagrant ssh deis-01` and `ip a`, I get two network adapters: `eth0` has an `inet` address of `10.0.2.15`, and `eth1` has an `inet` the `172.~~~

**Comment by haf** [comment] 2015-03-07 19:56
I'd say the next step is to run [`vagrant ssh-config`](http://docs.vagrantup.com/v2/cli/ssh_config.html) and then try `ssh -t ~/.vagrant/insecure_key vagrant@172.17.8.100` or whichever key the `ssh-config` command specifies is being used. If that doesn't work, you have a general connectivity problem to virtual machines on you machine. If it works, then you should seek a way to in detail log the ssh command that deisctl actually runs and ensure you have the identical version to your deis version. You can also read https://github.com/deis/deis/issues/2727 which comes up with having a too-low vagrant version being the issue.

**Comment by haf** [comment] 2015-03-07 19:57
10.x network doesn't work because it's a private network with VirtualBox and not exposed to your host machine. The NAT network is used to download things from the internet and it's natted at the host kernel level.

**Comment by Californian** [comment] 2015-03-07 23:23
`vagrant ssh-config` tells me `HostName 127.0.0.1`; is that the expected output?
`ssh -t ~/.vagrant.d/insecure_private_key vagrant@172.17.8.100` doesn't seem like the correct syntax; it complains that it can't resolve the hostname, but the hostname it says it can't resolve is the private key.

**Comment by haf** [comment] 2015-03-08 10:42
Let me test this locally.

**Comment by haf** [comment] 2015-03-08 10:43
Here's `vagrant ssh-config`

```
vagrant ssh-config
Host deis-01
  HostName 127.0.0.1
  User core
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/henrik.feldt/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

**Comment by haf** [comment] 2015-03-08 10:46
I can reproduce your local error, here's what I did to make it work:

```
➜  deis-vagrant git:(docs/cadvisor) ✗ ssh -t /Users/henrik.feldt/.vagrant.d/insecure_private_key vagrant@127.0.0.1 -p 2222
ssh: Could not resolve hostname /Users/henrik.feldt/.vagrant.d/insecure_private_key: nodename nor servname provided, or not known
➜  deis-vagrant git:(docs/cadvisor) ✗ ssh -i /Users/henrik.feldt/.vagrant.d/insecure_private_key vagrant@127.0.0.1 -p 2222
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
89:90:6d:99:45:f2:1c:cf:9e:b6:b5:45:74:df:27:15.
Please contact your system administrator.
Add correct host key in /Users/henrik.feldt/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/henrik.feldt/.ssh/known_hosts:54
RSA host key for [127.0.0.1]:2222 has changed and you have requested strict checking.
Host key verification failed.
➜  deis-vagrant git:(docs/cadvisor) ✗ vim /Users/henrik.feldt/.ssh/known_hosts
➜  deis-vagrant git:(docs/cadvisor) ✗ sed -i '' 54d /Users/henrik.feldt/.ssh/known_hosts
➜  deis-vagrant git:(docs/cadvisor) ✗ ssh -i /Users/henrik.feldt/.vagrant.d/insecure_private_key vagrant@127.0.0.1 -p 2222
The authenticity of host '[127.0.0.1]:2222 ([127.0.0.1]:2222)' can't be established.
RSA key fingerprint is 89:90:6d:99:45:f2:1c:cf:9e:b6:b5:45:74:df:27:15.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.
vagrant@127.0.0.1's password:

➜  deis-vagrant git:(docs/cadvisor) ✗ ssh -i /Users/henrik.feldt/.vagrant.d/insecure_private_key core@127.0.0.1 -p 2222
Last login: Sat Mar  7 21:40:19 2015 from 10.0.2.2
 * *    *   *****    ddddd   eeeeeee iiiiiii   ssss
*   *  * *  *   *     d   d   e    e    i     s    s
 * *  ***** *****     d    d  e         i    s
*****  * *    *       d     d e         i     s
*   * *   *  * *      d     d eee       i      sss
*****  * *  *****     d     d e         i         s
  *   *****  * *      d    d  e         i          s
 * *  *   * *   *     d   d   e    e    i    s    s
***** *****  * *     ddddd   eeeeeee iiiiiii  ssss

Welcome to Deis			Powered by CoreOS
core@deis-01 ~ $ exit
logout
Connection to 127.0.0.1 closed.
➜  deis-vagrant git:(docs/cadvisor) ✗
```

**Comment by Californian** [comment] 2015-03-09 15:09
So `ssh`-ing into coreos wasn't my problem (I can do that with `vagrant ssh deis-01`), my problem is not being able to run `deisctl list`. Given that I can `ssh` in to the coreos vm, do you have any ideas for how I can go about logging the `ssh` command that `deisctl` runs? I tried finding commands in the source but to no avail.

**Comment by mboersma** [comment] 2015-03-09 15:52
@Californian, what do you have set for `DEISCTL_TUNNEL`?

**Comment by Californian** [comment] 2015-03-09 16:01
`172.17.8.100`

**Comment by mboersma** [comment] 2015-03-09 16:10
Did you try adding the key to `ssh-agent` and setting `DEISCTL_TUNNEL` to the host and port specified by vagrant?
```console
$ eval $(ssh-agent)
$ ssh-add ~/.vagrant.d/insecure_private_key
$ export DEISCTL_TUNNEL=127.0.0.1:2222
$ deisctl list
```

**Comment by Californian** [comment] 2015-03-09 16:30
So that gets `deisctl list` working, but when I try to install it hangs after `deis-router@2.service: loaded`. I assume this is because it is not using `172.17.8.100` for the tunnel address, so any thoughts on how to debug why using that address is not working (or how to resolve the hanging another way)?

**Comment by mboersma** [comment] 2015-03-09 16:41
> I assume this is because it is not using 172.17.8.100 for the tunnel address

Probably not--if `deisctl` is able to talk to a node in the cluster, then `deisctl start platform` doesn't care about addressing. If `start platform` hangs, it often indicates a fleet/etcd error internal to the cluster. I would ensure that `fleetctl list-machines` from one of the nodes shows all 3 to be healthy, try the command again, and then look through `journalctl` logs for fleet to see if errors show up.

As far as why vagrant didn't allocate our preferred IP address range, I've seen this happen in the case of collisions, where I already had a vagrant / VirtualBox VM using that address, when I've tried to use vagrant / VMware as well, or if VirtualBox's own network interfaces are somehow stale or incorrect. I can't say for sure that's what you're seeing, but my troubleshooting steps in this case are usually to 1) shut down all VirtualBox instances, and 2) remove the VirtualBox network bridges and dhcp servers:
```
$ VBoxManage list hostonlyifs
$ VBoxManage hostonlyif remove vboxnet1
$ VBoxManage hostonlyif remove vboxnet1
$ VBoxManage list dhcpservers
$ VBoxManage remove --netname HostInterfaceNetworking-vboxnet1
```
VirtualBox will recreate them the next time you start a VM, which--at least for me--usually fixes the assignment of 172.17.8.100.

**Comment by Californian** [comment] 2015-03-09 18:20
`fleetctl list-machines` gives me  20 or so alternating INFO/ERROR lines:
`INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects`
`ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 100ms`
then
`Error retrieving list of active machines: timeout reached`

As for this removal business, I tried removing all the network bridges and dhcp servers. That went...interestingly. I'm not sure if I wasn't supposed to remove things suffixed `vboxnet0`, but something or other crashed the server while in the middle, so after rebooting I uninstalled vagrant and virtualbox, deleted `~/VirtualBox VMs` and `deis/.vagrant`, rebooted, reinstalled, deleted `hostonlyif` `vboxnet1`, `vagrant up`d, `ssh-add`ed the insecure private key, exported the 172 address for the tunnel, and got the same timeout result. I then tried exporting the 127...:2222 address again and got the above INFO/ERROR responses when doing `deisctl list`, which is strange because, as I mentioned, that previously worked.

Does this tell you anything? I don't know where to debug from here.

**Comment by carmstrong** [comment] 2015-03-09 20:52
@Californian Based on your debugging and your output, I would suspect that the VMs can't communicate with each other over the private network. What does `ifconfig` report on the VMs? That will confirm @mboersma's suspicion that they're getting addresses that aren't routable to each other. This would also explain why etcd can't communicate, and why your `deisctl start` hangs - there's effectively only one machine in your cluster, the one deisctl is talking to.

> VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet1

It's important that *all* DHCP servers are removed from VBox - we can't tell which one `vboxnet1` is in that particular instance.

Either way, I think an `ifconfig` would be helpful.

**Comment by Californian** [comment] 2015-03-10 18:05
Now `VBoxManage list dhcpservers` returns nothing no matter what (there was one at some point, but it's now gone and won't come back even after vagrant up).

Here is the `ifconfig` output for each machine.
**deis-01**
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fe8e:e1da  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:8e:e1:da  txqueuelen 1000  (Ethernet)
        RX packets 1048  bytes 119206 (116.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 780  bytes 103379 (100.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.8.100  netmask 255.255.255.0  broadcast 172.17.8.255
        inet6 fe80::a00:27ff:fea8:de2d  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:a8:de:2d  txqueuelen 1000  (Ethernet)
        RX packets 8302  bytes 1263214 (1.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10734  bytes 2386768 (2.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 3139  bytes 560126 (546.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3139  bytes 560126 (546.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
* * *
**deis-02**
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fe8e:e1da  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:8e:e1:da  txqueuelen 1000  (Ethernet)
        RX packets 879  bytes 99886 (97.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 661  bytes 82058 (80.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.8.101  netmask 255.255.255.0  broadcast 172.17.8.255
        inet6 fe80::a00:27ff:fef8:cc0f  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:f8:cc:0f  txqueuelen 1000  (Ethernet)
        RX packets 6618  bytes 1592794 (1.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5109  bytes 790712 (772.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 6097  bytes 1186419 (1.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6097  bytes 1186419 (1.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
* * *
**deis-03**
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fe8e:e1da  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:8e:e1:da  txqueuelen 1000  (Ethernet)
        RX packets 874  bytes 99543 (97.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 656  bytes 81788 (79.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.8.102  netmask 255.255.255.0  broadcast 172.17.8.255
        inet6 fe80::a00:27ff:fe5c:6e7c  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:5c:6e:7c  txqueuelen 1000  (Ethernet)
        RX packets 4530  bytes 888491 (867.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3515  bytes 517268 (505.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 2980  bytes 599476 (585.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2980  bytes 599476 (585.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by carmstrong** [comment] 2015-03-10 18:07
@Californian That looks OK now. Can you give it another go?

**Comment by carmstrong** [comment] 2015-03-10 18:07
Also, `cat /etc/environment` and confirm the public and private IPs.

**Comment by Californian** [comment] 2015-03-10 18:13
Oh wow that did work! I had to use 127.0.0.1:2222 for the tunnel, but it installed and is now starting. Thank you!

I suppose you can close this issue (though it is still confusing to me that I can't use `172.17.8.100`, an IP address that will now be burned into my memory).

**Comment by carmstrong** [comment] 2015-03-10 18:16
> I had to use 127.0.0.1:2222 for the tunnel, but it installed and is now starting.

Glad to hear you're up and running, but still dumbfounded as to why you can't route to that IP. By any chance, are you on a local (wired or wireless) network which assigns IP addresses in that range? I'm wondering if traffic to the VM is getting routed out to another network instead of using the local bridge.

`ifconfig` on your workstation should confirm or refute this.

**Comment by Californian** [comment] 2015-03-10 18:41
My workstation runs Arch, so this is the output of `ip a` instead.
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp26s0f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 00:0a:f7:1a:75:90 brd ff:ff:ff:ff:ff:ff
3: enp26s0f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 00:0a:f7:1a:75:92 brd ff:ff:ff:ff:ff:ff
4: enp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 34:40:b5:8c:5a:db brd ff:ff:ff:ff:ff:ff
    inet 69.46.236.200/26 brd 69.46.236.255 scope global enp6s0
       valid_lft forever preferred_lft forever
    inet6 fe80::6701:5559:2816:9b9e/64 scope link 
       valid_lft forever preferred_lft forever
5: enp11s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 34:40:b5:8c:5a:dc brd ff:ff:ff:ff:ff:ff
    inet6 fe80::d2d4:9f9e:e93a:cdaa/64 scope link tentative 
       valid_lft forever preferred_lft forever
6: enp0s29u1u1u5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 36:40:b5:8c:5a:de brd ff:ff:ff:ff:ff:ff
    inet 169.254.95.120/24 brd 169.254.95.255 scope global enp0s29u1u1u5
       valid_lft forever preferred_lft forever
    inet6 fe80::73df:524:258e:160e/64 scope link 
       valid_lft forever preferred_lft forever
9: vboxnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 0a:00:27:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::aca7:69d4:eddf:a9b9/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by Californian** [comment] 2015-03-10 19:22
`deis register` doesn't work. I assume this is related to the same root issue, but perhaps that is better-suited to a new bug?

**Comment by carmstrong** [comment] 2015-03-10 19:59
> I assume this is related to the same root issue, but perhaps that is better-suited to a new bug?

That won't work if you can't connect to the VMs via 172.17.8.100, since `local3.deisapp.com` resolves to `172.17.8.100 172.17.8.101 172.17.8.102`.

**Comment by Californian** [comment] 2015-03-10 20:13
Yeah I thought that was the implication above from @mboersma. How do I work around that?

**Comment by carmstrong** [comment] 2015-03-11 07:56
> Yeah I thought that was the implication above from @mboersma. How do I work around that?

Honestly, I'm not sure. I was going to suggest that you edit `~/.ssh/config` and add entries for the VMs so you can refer to them by name, but that doesn't help if you don't have a wildcard DNS record to point to them. And `/etc/hosts` doesn't work for wildcard domains...

Figuring out why `172.17.8.100` doesn't route to the VM on your machine is the blocker. Unfortunately, I'm out of ideas :(

**Comment by Californian** [comment] 2015-03-11 17:42
Should there be more than one `hostonlyif`?

**Comment by mboersma** [comment] 2015-03-11 17:59
Yes, typically you'll have `vboxnet0` and `vboxnet1` after running `vagrant up` with Deis.

**Comment by Californian** [comment] 2015-03-11 18:07
Ah well I only have one, maybe that's part of the problem. I had two at some point in this process (`vboxnet0` with an IP address I can't remember and `vboxnet1` with the 172 address), but now it's just `vboxnet0` with the 172 address.

**Comment by Californian** [comment] 2015-03-11 20:35
I started everything from scratch, including removing a bunch of hidden folders with data for vagrant/virtualbox, and after vagrant up, I get the following.
`VBoxManage list hostonlyifs`
```
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.56.101
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:aca7:69d4:eddf:a9b9
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       172.17.8.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:ff57:ffa8:308b:9f68
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1
```
* * *
`VBoxManage list dhcpservers`
```
NetworkName:    HostInterfaceNetworking-vboxnet0
IP:             192.168.56.100
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.56.101
upperIPAddress: 192.168.56.254
Enabled:        Yes
```

**Comment by mboersma** [comment] 2015-04-19 12:03
@Californian were you able to sort out the VirtualBox bridge issue here? I'm not sure what else to try for troubleshooting.

**Comment by mboersma** [comment] 2015-04-20 21:27
I'm closing this as there doesn't seem to be anything here that Deis can address.

**Closed by mboersma** 2015-04-20 21:27 UTC
Labels: contrib and provisioning
