### ISSUE TITLE
AWS instances crashing

### ISSUE THREAD

**Issue by mgartner** [deis/deis#2959] opened 2015-01-26 03:59 UTC
I've witnessed 3+ times in the last two weeks where an EC2 instance is terminated by my autoscaling group when it fails an instance status check. These terminations lead to problems with my cluster - putting Ceph into a HEALTH_WARN state and, with enough terminations, losing quorum. 

Given the regularity of the terminations, I think it's unlikely that the cause of the terminations is due to the infrastructure my instances were living on. Either Deis or one of my apps brings down the host machine, or causes an instance status check to fail.

The three apps I'm running on the cluster are fairly simple - one is a Node.js server, and the two other are background workers that pull messages from SQS and perform image manipulation with imagemagick and send out emails via SES. I can't think of any reason that one of these apps would lead to problems for the host, but I'm open to ideas. If other users hosting Deis have never seen unexpected terminations on AWS, then that might be strong evidence that my particular applications may be the source of the problem.

I've tried to look for any clues as to what is exactly happening, but the messaging from AWS is pretty vague. In addition, server metrics via New Relic don't show anything suspicious in terms of CPU, RAM, networking, or disk usage at the time that the instance is terminated.

I've had to move my production applications off of Deis for now, as I was having to manually intervene every-other-day or so, but I've left the cluster of affected machines running in case it will help diagnose the problem (although Ceph has lost quorum and the cluster is in a wonky state).

I'm hoping someone with more experience in this area has an idea of where to look for clues to get to the bottom of this.

**Comment by carmstrong** [comment] 2015-01-26 06:06
This issue is described a bit in #2877 - we're working on https://github.com/deis/mortician as a solution to automatically handle cases where an autoscaling event removes a node from the cluster, but we really need to get to the bottom of why some users are experiencing frequent failures... I know @ianblenke sees this too.

**Comment by ianblenke** [comment] 2015-01-27 14:30
I'm pretty sure this is ceph mds (cephfs) related.

In the past, we've had applications eat all available RAM and cause kernels to panic.

We've also had HVM clock drift because we weren't using NTP, which caused some ceph weirdness.

Now that we have both of those things under control, the last time I had a crash I did catch a mention of mds being in the middle of things:

    [534838.718074] ceph: mds0 caps stale
    [535083.710066] ceph: mds0 hung

It is important that we get folks to pull the system console output from AWS when an instances hangs like this, so that we might find  if there is a commonality.

Note: you can still pull the system console even from a TERMINATED instance, so long as you do so before the next periodic AWS cleanup sweep where that instance disappears from your account entirely.

**Comment by ianblenke** [comment] 2015-01-27 14:34
Also note: my current thinking on this is that we seem to have the problems when some stupid bot from russia or china tries an HTTP attack, causing massive amounts of nginx webhits to be logged, which causes deis-logspout to flood deis-logger which in turn struggles to write to cephfs in /var/lib/deis/store/logs/

In the past, when we had the ntp clock drift, I can also cause a pretty reproducable system crash if I try to rsync to/from /var/lib/deis/store/ from the btrfs filesystem. I haven't tried an rsync since fixing ntp. I've had more than one crash simply by doing an "ls /var/lib/deis/store/"

Because of that, I try to avoid even _looking_ at /var/lib/deis/store/ anymore. I'm actively afraid of angering CephFS.

**Comment by johanneswuerbach** [comment] 2015-01-27 14:39
@carmstrong can't we simply execute http://docs.deis.io/en/latest/managing_deis/add_remove_host/#removing-a-node as shutdown script on shutdown? AWS should wait 60 seconds by default for a node to gracefully shutdown.

**Comment by carmstrong** [comment] 2015-01-27 18:45
> AWS should wait 60 seconds by default for a node to gracefully shutdown.

In many cases, the instances become unresponsive, and AWS triggers a new node to replace the failed node. So we can't rely on shutdown scripts, unfortunately, or trust the instance itself at all. It'd help in the common case, but it's probably worth instead spending the time to build a general-purpose solution.



> In the past, when we had the ntp clock drift, I can also cause a pretty reproducable system crash if I try to rsync to/from /var/lib/deis/store/ from the btrfs filesystem. I haven't tried an rsync since fixing ntp. I've had more than one crash simply by doing an "ls /var/lib/deis/store/"

That makes me think of the Ceph bug @lorieri reported - http://lists.ceph.com/pipermail/ceph-users-ceph.com/2015-January/045838.html

It may be worth exploring switching from the kernel client for CephFS to the FUSE client - this would at least allow us to upgrade versions without waiting on a new kernel release.

**Comment by bacongobbler** [comment] 2015-01-27 20:29
I've had a cluster running for up to two weeks on Rackspace and Digital Ocean with no downtime, so this has to do with something specific with AWS/how we provision a cluster on AWS. @carmstrong mentioned the thought that it could be due to slow disk speeds, though some more monitoring/investigation would probably show the true culprit behind all this.

**Comment by ianblenke** [comment] 2015-01-28 03:10
Well, _we_ have been using SSD, and we still have the problem, so switching from standard magnetic to gp2 isn't going to fix it on its lonesome. We're proof of that.

**Comment by mgartner** [comment] 2015-01-29 23:34
I want to note that one of my applications writes a lot of temporary image files to the `/tmp` directory. I don't think that Ceph would be syncing those files across machines since they are written inside their own containers, but maybe it is somehow? This might explain why my staging cluster runs smooth, but my production cluster has problems, because my production apps write a hell of a lot more files than in staging. Maybe the large volume of temp files I'm writing is exposing Ceph-related issues for me?

**Comment by ianblenke** [comment] 2015-02-04 17:43
We have about one instance death a day now.

Yesterday's instance kernel log: https://gist.github.com/ianblenke/b74e5aa5547130ebc0fb

Today's instance kernel log: https://gist.github.com/ianblenke/8afe6ab3bb0849f96d10

**Comment by mgartner** [comment] 2015-03-02 23:23
@ianblenke are you still experiences these deaths? It's been a while since I last tinkered with this, was wondering if you've had any success in the meantime?

**Comment by ianblenke** [comment] 2015-03-03 00:57
After over a week of no instance losses, I lost another instance today. This is HVM based. The lost node was one of my 522 nodes, not the lone wierdo 584 node in that cluster. None of them have cephfs mounted at this point. Cephfs is essentially unused - I've grafted that cluster to use S3 only.

I have an entirely different cluster running v1.3.1 on PV and haven't had a problem with Ceph/Deis _yet_ - it has been up for 4 days now.

**Comment by kingkevin** [comment] 2015-03-19 01:42
Experienced this again today. For those on AWS, launching a new node and stopping the problematic node fixed the issue and the cluster (mostly) got back to a clean state.

It seems that several of the services that replicate across the cluster are now duplicated on one of the nodes (ie I still have 4 logger services but only 3 nodes). Do I need to take extra steps to remove the duplicate services?

**Comment by ianblenke** [comment] 2015-03-19 18:23
Experienced this today myself, PV this time (not HVM):

```
ritepage+0x39/0x80
[404640.324762]  [<ffffffff81150ca6>] shrink_page_list+0x7f6/0xac0
[404640.324767]  [<ffffffff8115159d>] shrink_inactive_list+0x1cd/0x590
[404640.324771]  [<ffffffff81152345>] shrink_lruvec+0x595/0x790
[404640.324774]  [<ffffffff811525c3>] shrink_zone+0x83/0x1d0
[404640.324781]  [<ffffffff81152d5c>] do_try_to_free_pages+0x19c/0x4d0
[404640.324786]  [<ffffffff8115314a>] try_to_free_pages+0xba/0x150
[404640.324789]  [<ffffffff81146891>] __alloc_pages_nodemask+0x5a1/0x9c0
[404640.324796]  [<ffffffff81188377>] alloc_pages_current+0x97/0x110
[404640.324801]  [<ffffffff81192d1b>] new_slab+0x33b/0x430
[404640.324805]  [<ffffffff814ee2bb>] __slab_alloc+0x316/0x477
[404640.324811]  [<ffffffff8128afc9>] ? __radix_tree_preload+0x39/0xa0
[404640.324815]  [<ffffffff81192f9b>] kmem_cache_alloc+0x18b/0x1e0
[404640.324818]  [<ffffffff8128afc9>] ? __radix_tree_preload+0x39/0xa0
[404640.324824]  [<ffffffff8128afc9>] __radix_tree_preload+0x39/0xa0
[404640.324828]  [<ffffffff814f5680>] ? _raw_spin_unlock_irqrestore+0x20/0x40
[404640.324832]  [<ffffffff8128b099>] radix_tree_maybe_preload+0x19/0x20
[404640.324836]  [<ffffffff8117d119>] read_swap_cache_async+0x79/0x160
[404640.324841]  [<ffffffff8117d340>] swapin_readahead+0x140/0x1a0
[404640.324846]  [<ffffffff8113e5df>] ? pagecache_get_page+0x2f/0x1e0
[404640.324850]  [<ffffffff81009a89>] ? xen_pmd_val+0x19/0x20
[404640.324853]  [<ffffffff81005261>] ? __raw_callee_save_xen_pte_val+0x11/0x1e
[404640.324857]  [<ffffffff8116bb3c>] handle_mm_fault+0xbac/0x1090
[404640.324861]  [<ffffffff81006035>] ? pte_mfn_to_pfn.part.15+0x85/0x110
[404640.324866]  [<ffffffff810577d4>] __do_page_fault+0x164/0x490
[404640.324872]  [<ffffffff81099680>] ? update_curr+0x80/0x180
[404640.324876]  [<ffffffff8105cec2>] ? gup_pte_range+0x82/0x140
[404640.324881]  [<ffffffff81099c42>] ? dequeue_entity+0x142/0x5c0
[404640.324886]  [<ffffffff81057b52>] do_page_fault+0x22/0x30
[404640.324890]  [<ffffffff814f7d48>] page_fault+0x28/0x30
[404640.324894]  [<ffffffff81291ad5>] ? copy_user_enhanced_fast_string+0x5/0x10
[404640.324898]  [<ffffffff812978bd>] ? memcpy_toiovec+0x4d/0xa0
[404640.324902]  [<ffffffff813e9c81>] skb_copy_datagram_iovec+0x61/0x2a0
[404640.324906]  [<ffffffff8143f9a6>] tcp_recvmsg+0x1e6/0xba0
[404640.324909]  [<ffffffff8146b7bc>] inet_recvmsg+0x6c/0x80
[404640.324913]  [<ffffffff813da953>] sock_aio_read.part.27+0xb3/0xc0
[404640.324917]  [<ffffffff813da981>] sock_aio_read+0x21/0x40
[404640.324920]  [<ffffffff811ad12a>] do_sync_read+0x5a/0x90
[404640.324923]  [<ffffffff814f5680>] ? _raw_spin_unlock_irqrestore+0x20/0x40
[404640.324927]  [<ffffffff811adba5>] vfs_read+0x145/0x180
[404640.324930]  [<ffffffff811ae666>] SyS_read+0x46/0xb0
[404640.324934]  [<ffffffff814f5f29>] system_call_fastpath+0x12/0x17
[404640.324939] INFO: task etcd:948 blocked for more than 120 seconds.
[404640.324942]       Not tainted 3.18.1 #2
[404640.324944] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[404640.324946] etcd            D 0000000000000000     0   948      1 0x00000000
[404640.324950]  ffff8800fa517458 0000000000000286 ffff8803965ae400 0000000000012ec0
[404640.324957]  ffff8800fa517fd8 0000000000012ec0 ffff8803a6e30000 ffff8803965ae400
[404640.324962]  ffff8800fa517468 ffff88039b7a7c00 ffff88039b7a7d14 ffff880376990000
[404640.324966] Call Trace:
[404640.324969]  [<ffffffff814f18c9>] schedule+0x29/0x70
[404640.324972]  [<ffffffffa0327e47>] loop_unregister_transfer+0x2c77/0x364a [loop]
[404640.324976]  [<ffffffff810a48d0>] ? prepare_to_wait_event+0x110/0x110
[404640.324981]  [<ffffffff810099d9>] ? xen_pte_val+0x19/0x20
[404640.324987]  [<ffffffff8125a610>] generic_make_request+0xc0/0x110
[404640.324990]  [<ffffffff8125a6d8>] submit_bio+0x78/0x160
[404640.324993]  [<ffffffff81180dc2>] ? map_swap_page+0x12/0x20
[404640.324999]  [<ffffffff8117c97a>] __swap_writepage+0x22a/0x280
[404640.325003]  [<ffffffff81176cf5>] ? rmap_walk+0x265/0x330
[404640.325006]  [<ffffffff8117d571>] ? swap_info_get+0x61/0xf0
[404640.325009]  [<ffffffff8117fc5c>] ? page_swapcount+0x4c/0x60
[404640.325013]  [<ffffffff8117ca09>] swap_writepage+0x39/0x80
[404640.325016]  [<ffffffff81150ca6>] shrink_page_list+0x7f6/0xac0
[404640.325020]  [<ffffffff8115159d>] shrink_inactive_list+0x1cd/0x590
[404640.325027]  [<ffffffff81152345>] shrink_lruvec+0x595/0x790
[404640.325031]  [<ffffffff811525c3>] shrink_zone+0x83/0x1d0
[404640.325035]  [<ffffffff81152d5c>] do_try_to_free_pages+0x19c/0x4d0
[404640.325040]  [<ffffffff8115314a>] try_to_free_pages+0xba/0x150
[404640.325045]  [<ffffffff81146891>] __alloc_pages_nodemask+0x5a1/0x9c0
[404640.325049]  [<ffffffff81188377>] alloc_pages_current+0x97/0x110
[404640.325063]  [<ffffffff813de7ba>] skb_page_frag_refill+0x5a/0xb0
[404640.325067]  [<ffffffff813df2a5>] sk_page_frag_refill+0x25/0xd0
[404640.325071]  [<ffffffff81441b63>] tcp_sendmsg+0x243/0xc60
[404640.325074]  [<ffffffff8146b704>] inet_sendmsg+0x64/0xb0
[404640.325078]  [<ffffffff813da88a>] sock_aio_write+0xca/0xe0
[404640.325082]  [<ffffffff811c39c5>] ? __dentry_kill+0x155/0x1f0
[404640.325085]  [<ffffffff811ad1ba>] do_sync_write+0x5a/0x90
[404640.325088]  [<ffffffff811add75>] vfs_write+0x195/0x1f0
[404640.325091]  [<ffffffff811ae716>] SyS_write+0x46/0xb0
[404640.325095]  [<ffffffff814f5f29>] system_call_fastpath+0x12/0x17
[404640.325098] INFO: task etcd:17743 blocked for more than 120 seconds.
[404640.325100]       Not tainted 3.18.1 #2
[404640.325102] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[404640.325105] etcd            D 0000000000000000     0 17743      1 0x00000000
[404640.325109]  ffff8801edb9b768 0000000000000286 ffff8803754c6400 0000000000012ec0
[404640.325113]  ffff8801edb9bfd8 0000000000012ec0 ffff8803a6e30000 ffff8803754c6400
[404640.325117]  ffff8801edb9b778 ffff88039b7a7c00 ffff88039b7a7d14 ffff880376990000
[404640.325122] Call Trace:
[404640.325125]  [<ffffffff814f18c9>] schedule+0x29/0x70
[404640.325128]  [<ffffffffa0327e47>] loop_unregister_transfer+0x2c77/0x364a [loop]
[404640.325132]  [<ffffffff810a48d0>] ? prepare_to_wait_event+0x110/0x110
[404640.325136]  [<ffffffff8125a610>] generic_make_request+0xc0/0x110
[404640.325139]  [<ffffffff8125a6d8>] submit_bio+0x78/0x160
[404640.325142]  [<ffffffff8117c3e0>] ? end_swap_bio_write+0x80/0x80
[404640.325145]  [<ffffffff81180dc2>] ? map_swap_page+0x12/0x20
[404640.325149]  [<ffffffff8117cb1c>] swap_readpage+0xcc/0xf0
[404640.325152]  [<ffffffff8117d161>] read_swap_cache_async+0xc1/0x160
[404640.325155]  [<ffffffff8117d340>] swapin_readahead+0x140/0x1a0
[404640.325159]  [<ffffffff8113e5df>] ? pagecache_get_page+0x2f/0x1e0
[404640.325162]  [<ffffffff81009a89>] ? xen_pmd_val+0x19/0x20
[404640.525613]  [<ffffffff81005261>] ? __raw_callee_save_xen_pte_val+0x11/0x1e
[404640.525623]  [<ffffffff8116bb3c>] handle_mm_fault+0xbac/0x1090
[404640.525628]  [<ffffffff81006035>] ? pte_mfn_to_pfn.part.15+0x85/0x110
[404640.525632]  [<ffffffff81145cb6>] ? get_page_from_freelist+0x3d6/0xa10
[404640.525637]  [<ffffffff810577d4>] __do_page_fault+0x164/0x490
[404640.525642]  [<ffffffff81099680>] ? update_curr+0x80/0x180
[404640.525652]  [<ffffffff8105cec2>] ? gup_pte_range+0x82/0x140
[404640.525656]  [<ffffffff81099855>] ? update_cfs_shares+0xb5/0x110
[404640.525660]  [<ffffffff81099680>] ? update_curr+0x80/0x180
[404640.525665]  [<ffffffff81057b52>] do_page_fault+0x22/0x30
[404640.525672]  [<ffffffff814f7d48>] page_fault+0x28/0x30
[404640.525676]  [<ffffffff81291ad5>] ? copy_user_enhanced_fast_string+0x5/0x10
[404640.525681]  [<ffffffff812978bd>] ? memcpy_toiovec+0x4d/0xa0
[404640.525686]  [<ffffffff813e9c81>] skb_copy_datagram_iovec+0x61/0x2a0
[404640.525692]  [<ffffffff8100fd30>] ? xen_smp_send_reschedule+0x10/0x20
[404640.525699]  [<ffffffff8143f9a6>] tcp_recvmsg+0x1e6/0xba0
[404640.525704]  [<ffffffff8146b7bc>] inet_recvmsg+0x6c/0x80
[404640.525708]  [<ffffffff810daa46>] ? wake_futex+0x66/0x90
[404640.525713]  [<ffffffff813da953>] sock_aio_read.part.27+0xb3/0xc0
[404640.525717]  [<ffffffff813da981>] sock_aio_read+0x21/0x40
[404640.525721]  [<ffffffff811ad12a>] do_sync_read+0x5a/0x90
[404640.525725]  [<ffffffff811adba5>] vfs_read+0x145/0x180
[404640.525728]  [<ffffffff811ae666>] SyS_read+0x46/0xb0
[404640.525732]  [<ffffffff810cbde1>] ? posix_ktime_get_ts+0x11/0x20
[404640.525736]  [<ffffffff814f5f29>] system_call_fastpath+0x12/0x17
[404640.525743] INFO: task etcd:24860 blocked for more than 120 seconds.
[404640.525746]       Not tainted 3.18.1 #2
[404640.525748] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[404640.525752] etcd            D 0000000000000000     0 24860      1 0x00000000
[404640.525757]  ffff88030d317d48 0000000000000286 ffff8801edba3200 0000000000012ec0
[404640.525762]  ffff88030d317fd8 0000000000012ec0 ffff8803a6e31900 ffff8801edba3200
[404640.525769]  ffff88030d317d58 ffff8803a1a3d800 000000000000001a ffff8803a1a3daf8
[404640.525775] Call Trace:
[404640.525778]  [<ffffffff814f18c9>] schedule+0x29/0x70
[404640.525791]  [<ffffffffa017e56c>] btrfs_del_orphan_item+0x184c/0x6d50 [btrfs]
[404640.525796]  [<ffffffff810a48d0>] ? prepare_to_wait_event+0x110/0x110
[404640.525803]  [<ffffffffa0184101>] btrfs_sync_log+0xc1/0x910 [btrfs]
[404640.525811]  [<ffffffffa0148040>] ? btrfs_merge_bio_hook+0x2d90/0x2d90 [btrfs]
[404640.525821]  [<ffffffffa0184e4d>] ? btrfs_log_dentry_safe+0x6d/0x80 [btrfs]
[404640.525829]  [<ffffffffa01540d6>] btrfs_sync_file+0x2b6/0x1080 [btrfs]
[404640.525834]  [<ffffffff811dcab1>] do_fsync+0x51/0x80
[404640.525837]  [<ffffffff811dcd40>] SyS_fsync+0x10/0x20
[404640.525843]  [<ffffffff814f5f29>] system_call_fastpath+0x12/0x17
[406746.720083] ceph: mds0 caps stale
[406766.720082] ceph: mds0 caps stale
[406991.712066] ceph: mds0 hung
```

**Comment by ianblenke** [comment] 2015-03-19 18:24
Note: the memory referenced there is swap. Yes, I enabled swap. IO to the root disk stopped as there was some kind of kernel panic that I missed just before. In the past, this has been cephfs falling over because ceph-md is unhappy because ceph-mon is unhappy about clock drift.

**Comment by carmstrong** [comment] 2015-03-19 18:26
> IO to the root disk stopped as there was some kind of kernel panic that I missed just before. In the past, this has been cephfs falling over because ceph-md is unhappy because ceph-mon is unhappy about clock drift.

Ok, that explains why etcd falls over:
```
[404640.525743] INFO: task etcd:24860 blocked for more than 120 seconds.
[404640.525746]       Not tainted 3.18.1 #2
[404640.525748] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[404640.525752] etcd            D 0000000000000000     0 24860      1 0x00000000
[404640.525757]  ffff88030d317d48 0000000000000286 ffff8801edba3200 0000000000012ec0
[404640.525762]  ffff88030d317fd8 0000000000012ec0 ffff8803a6e31900 ffff8801edba3200
[404640.525769]  ffff88030d317d58 ffff8803a1a3d800 000000000000001a ffff8803a1a3daf8
```

Unfortunately there's no smoking gun held by Ceph that I can see. If we can get a panic with a stacktrace that shows Ceph doing something wrong, we can send it to the ceph-users group and see if anyone has any ideas.

**Comment by carmstrong** [comment] 2015-03-19 18:29
Anecdotally, I've also heard that using the kernel client on the same machine as an OSD can result in a deadlock condition in some scenarios, although no one seems to know exactly how or why. And we really have no choice here.

**Comment by bacongobbler** [comment] 2015-05-04 21:56
is this still a common issue? Haven't heard much chatter about this in a while.

**Comment by mgartner** [comment] 2015-05-04 22:07
I haven't had any time to test recently, maybe @ianblenke has? I'm assuming it's still a common issue for anyone on AWS though as it has not yet been addressed.

**Comment by carmstrong** [comment] 2015-05-04 22:18
> though as it has not yet been addressed.

I'd like to see this tested again. With 1.6 we're shipping a newer CoreOS kernel and new Ceph release (hammer), so it's worth revisiting.

**Comment by kingkevin** [comment] 2015-05-04 22:30
Last experienced this issue mid-April

**Comment by carmstrong** [comment] 2015-05-28 00:25
Deploying Deis with Ceph on AWS should be a new experience since this issue was last seen:
* Clock drift has been fixed
* New CoreOS kernel
* New Ceph release (hammer)
* Automatic node removal script in master (#3561)

I'm going to close this for now, but we will certainly re-open should someone run into it again.

**Closed by carmstrong** 2015-05-28 00:25 UTC
Labels: store (Ceph)
