### ISSUE TITLE
etcd hardening and stress testing

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#4404] opened 2015-09-03 20:38 UTC
We have recently seen several issues relating to etcd performance - specifically, several 503s and 501s. We need to spend time stress testing etcd to understand how to improve performance and reliability. Specifically, this should include:

* Testing on Docker 1.7.1 to see if the networking rewrite makes the Docker proxy more performant for etcdctl requests
* Re-evaluation of `etcdctl watch` usage (seemingly it causes far too much traffic because TTL updates are not filtered out - see coreos/etcd#952). Our use of polling loops and sleeps is clunky and issue prone.
* Rewrite of master election lock logic in bin/boot scripts in registry and store-gateway
* Support for Jenkins to record etcd performance statistics for runs so that regressions can be identified early

**Comment by mboersma** [comment] 2015-09-09 21:23
> Testing on Docker 1.7.1

I have done this and saw the same 503 errors as with earlier CoreOS / Docker 1.5.0.

**Comment by mboersma** [comment] 2015-09-10 21:51
I have also tried using the native etcd2 2.1.2 binary instead of our current containerized version (see #4444). The 503 errors are still easily triggered, so the issue is not with containerization of `etcd2` *per se*.

**Comment by mboersma** [comment] 2015-10-31 15:16
Intermittent 503 errors still show up in Deis master under load in v1.12.0-rc1.

**Comment by bacongobbler** [comment] 2016-01-21 19:31
etcd will be going away in v2 and we won't be able to get to this for the LTS release so I'm going to close this. :)

**Closed by bacongobbler** 2016-01-21 19:31 UTC
Labels: etcd/fleet, open-roadmap
