### ISSUE TITLE
Running without Ceph: deis-registry create_bucket looks for keys that aren't set:

### ISSUE THREAD

**Issue by dmcnaught** [deis/deis#4710] opened 2015-11-03 16:59 UTC
Followed the instructions here to run without ceph: http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/

Running "deisctl start stateless-platform" hangs at 
>
>$ deisctl start stateless-platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●
Logging subsystem...
deis-logger.service: active/running
deis-logspout.service: active/running
Control plane...
deis-controller.service: active/running
deis-registry@1.service: active/running
deis-builder.service: activating/start-post
>

```$ deisctl journal registry```
>
Nov 03 16:33:26 ip-10-51-2-132.ec2.internal systemd[1]: deis-registry@1.service: Service hold-off time over, scheduling restart.
Nov 03 16:33:26 ip-10-51-2-132.ec2.internal systemd[1]: Starting deis-registry...
Nov 03 16:33:26 ip-10-51-2-132.ec2.internal etcdctl[5834]: Error:  105: Key already exists (/deis/cache) [5042]
Nov 03 16:33:26 ip-10-51-2-132.ec2.internal systemd[1]: Started deis-registry.
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal sh[5868]: Traceback (most recent call last):
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal sh[5868]: File "/app/bin/create_bucket", line 11, in <module>
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal sh[5868]: calling_format=OrdinaryCallingFormat())
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal sh[5868]: File "/usr/lib/python2.7/site-packages/boto/__init__.py", line 141, in connect_s3
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal sh[5868]: return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal sh[5868]: File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 190, in __init__
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal sh[5868]: validate_certs=validate_certs, profile_name=profile_name)
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal sh[5868]: File "/usr/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal sh[5868]: host, config, self.provider, self._required_auth_capability())
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal sh[5868]: File "/usr/lib/python2.7/site-packages/boto/auth.py", line 975, in get_auth_handler
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal sh[5868]: 'Check your credentials' % (len(names), str(names)))
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal sh[5868]: boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal systemd[1]: deis-registry@1.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal docker[5965]: Error response from daemon: no such id: deis-registry
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal docker[5965]: Error: failed to stop containers: [deis-registry]
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal systemd[1]: deis-registry@1.service: Unit entered failed state.
Nov 03 16:33:50 ip-10-51-2-132.ec2.internal systemd[1]: deis-registry@1.service: Failed with result 'exit-code'.
Nov 03 16:33:56 ip-10-51-2-132.ec2.internal systemd[1]: deis-registry@1.service: Service hold-off time over, scheduling restart.
>

https://github.com/deis/deis/blob/master/registry/templates/create_bucket#L9 is asking for getv "/deis/store/gateway/accessKey - which isn't present:

>$ etcdctl ls --recursive /deis/store/gateway
/deis/store/gateway
$ etcdctl get /deis/store/gateway

>$
>

**Comment by dmcnaught** [comment] 2015-11-03 17:07
Adding accessKey and secretKey to etcd /deis/store/gateway/ seemed to fix the issue:
>
Nov 03 17:01:04 ip-10-51-2-132.ec2.internal systemd[1]: Starting deis-registry...
Nov 03 17:01:04 ip-10-51-2-132.ec2.internal etcdctl[13616]: Error:  105: Key already exists (/deis/cache) [11572]
Nov 03 17:01:04 ip-10-51-2-132.ec2.internal systemd[1]: Started deis-registry.
Nov 03 17:01:25 ip-10-51-2-132.ec2.internal sh[13651]: 2015-11-03T17:01:25Z 288e6fe38db5 confd[26]: ERROR template: create_bucket:10:30: executing "create_bucket" at <getv "/deis/store/ga...>: error calling getv: key does not exist
Nov 03 17:01:25 ip-10-51-2-132.ec2.internal sh[13651]: registry: waiting for confd to write initial templates...
Nov 03 17:01:35 ip-10-51-2-132.ec2.internal sh[13651]: 2015-11-03T17:01:35Z 288e6fe38db5 confd[37]: ERROR template: create_bucket:10:30: executing "create_bucket" at <getv "/deis/store/ga...>: error calling getv: key does not exist
Nov 03 17:01:35 ip-10-51-2-132.ec2.internal sh[13651]: registry: waiting for confd to write initial templates...
Nov 03 17:01:45 ip-10-51-2-132.ec2.internal sh[13651]: 2015-11-03T17:01:45Z 288e6fe38db5 confd[43]: ERROR template: create_bucket:10:30: executing "create_bucket" at <getv "/deis/store/ga...>: error calling getv: key does not exist
Nov 03 17:01:45 ip-10-51-2-132.ec2.internal sh[13651]: registry: waiting for confd to write initial templates...
Nov 03 17:01:55 ip-10-51-2-132.ec2.internal sh[13651]: deis-registry running...
Nov 03 17:01:55 ip-10-51-2-132.ec2.internal sh[13651]: [2015-11-03 17:01:55 +0000] [61] [INFO] Starting gunicorn 19.3.0
Nov 03 17:01:55 ip-10-51-2-132.ec2.internal sh[13651]: [2015-11-03 17:01:55 +0000] [61] [INFO] Listening at: http://0.0.0.0:5000 (61)
Nov 03 17:01:55 ip-10-51-2-132.ec2.internal sh[13651]: [2015-11-03 17:01:55 +0000] [61] [INFO] Using worker: gevent
Nov 03 17:01:55 ip-10-51-2-132.ec2.internal sh[13651]: [2015-11-03 17:01:55 +0000] [74] [INFO] Booting worker with pid: 74
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: [2015-11-03 17:01:56 +0000] [75] [INFO] Booting worker with pid: 75
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: [2015-11-03 17:01:56 +0000] [82] [INFO] Booting worker with pid: 82
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: [2015-11-03 17:01:56 +0000] [83] [INFO] Booting worker with pid: 83
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 WARNING: Cache storage disabled!
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 WARNING: LRU cache disabled!
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 INFO: Configuring CORS for app:'docker-registry' with resources:[(<_sre.SRE_Pattern object at 0x7f6c3e18bc60>, {})]
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 INFO: Boto based storage initialized
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 WARNING: Cache storage disabled!
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 WARNING: LRU cache disabled!
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 INFO: Configuring CORS for app:'docker-registry' with resources:[(<_sre.SRE_Pattern object at 0x7f6c3e18bc60>, {})]
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 INFO: Boto based storage initialized
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 WARNING: Cache storage disabled!
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 WARNING: LRU cache disabled!
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 INFO: Configuring CORS for app:'docker-registry' with resources:[(<_sre.SRE_Pattern object at 0x7f6c3e18bc60>, {})]
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 INFO: Boto based storage initialized
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 WARNING: Cache storage disabled!
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 WARNING: LRU cache disabled!
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 INFO: Configuring CORS for app:'docker-registry' with resources:[(<_sre.SRE_Pattern object at 0x7f6c3e18bc60>, {})]
Nov 03 17:01:56 ip-10-51-2-132.ec2.internal sh[13651]: 03/Nov/2015:17:01:56 +0000 INFO: Boto based storage initialized
>

**Comment by bacongobbler** [comment] 2015-11-03 18:08
I think you missed a step: http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/#configure-registry

It's not a "true" standalone version where everything is ephemeral. You still need it to point to an S3 endpoint. :)

**Comment by dmcnaught** [comment] 2015-11-03 19:33
I did run through these steps before I got the error:
>
$ BUCKET=MYS3BUCKET
$ AWS_S3_REGION=some-aws-region #(e.g., us-west-1)
$ deisctl config registry set s3bucket=${BUCKET} \
                              s3region=${AWS_S3_REGION} \
                              s3path=/ \
                              s3encrypt=false \
                              s3secure=false
$ deisctl config registry set s3accessKey=your-access-key \
                              s3secretKey=your-secret-key
>

**Comment by bacongobbler** [comment] 2015-11-03 19:51
Good point. Sounds like it's a doc bug. I'll re-open this so we change the last step to use `deisctl config store/gateway` instead of `deisctl config registry`. Sorry for the confusion!

**Comment by helgi** [comment] 2015-11-03 19:53
See #4668

**Comment by lukasmartinelli** [comment] 2015-11-04 13:06
Just fell into the same trap...
Good I found the issue. Setting `/deis/store/gateway/accessKey` and `/deis/store/gateway/secretKey` works.

**Comment by carmstrong** [comment] 2015-11-06 22:15
Moving this to the 1.12.1 milestone as it should be an easy doc fix and it's biting people.

**Comment by helgi** [comment] 2015-11-10 01:01
This should be fixed by #4729

**Comment by carmstrong** [comment] 2015-11-10 05:04
> This should be fixed by #4729

Agreed. Closing - we can reopen if necessary.

**Closed by carmstrong** 2015-11-10 05:04 UTC
Labels: docs

**Comment by carmstrong** [comment] 2015-11-10 18:41
This should be fixed by #4729, which was merged and released in Deis v1.12.1 today.

**Comment by Blystad** [comment] 2015-11-22 19:31
From what I can see, it's not. The registry has a dependency on /deis/store/gateway key in the conf.d file, and this seems to stop the registry from starting:

```
Nov 22 19:25:11 ip-10-0-0-129.eu-west-1.compute.internal sh[2519]: 2015-11-22T19:25:11Z 1c2f82d1390c confd[839]: ERROR 100: Key not found (/deis/store) [7364]
```

Running
```
etcdctl set /deis/store/gateway/helloWorld 1
```

Fixed it.

**Comment by jeffbaier** [comment] 2015-12-02 22:09
I can confirm this is still an issue and the @Blystad workaround fixes it. 

I'm doing a fresh (stateless) install of 1.12.2. The registry won't start because confd is waiting on /deis/store key path. You either have to set `/deis/store/gateway/accessKey` like @dmcnaught did, or you can just create an unused key in `/deis/store/whatever` like Blystad did. 

ping @carmstrong
