### ISSUE TITLE
request: Custom 502 error page on per-application basis

### ISSUE THREAD

**Issue by Blystad** [deis/deis#2943] opened 2015-01-22 12:18 UTC
I would like to replace the current default 502 Bad gateway page with a custom page on a per application basis.

*The use case is as follows:*
- Whenever we do a `git push deis` and update the application, in the transistion period between two versions where the old version is shutted down and the new version is started up, the page is replaced with a "502 Bad Gateway" nginx page. Instead of this page it would be useful to replace it with a custom HTML page (similar to what, for instance, Twitter and Reddit has) until the server is up and running again.

Ideally, it shouldn't be needed, but until #1829 rolling version update is added, I think this is a good solution.

I'm thinking it should be possible to upload a single html file. If the html file needs external resources, then that should either be stored on an external CDN or embedded in the page (base64).

**Comment by mboersma** [comment] 2015-01-22 22:51
This is a duplicate of #1082, closing.

**Closed by mboersma** 2015-01-22 22:51 UTC
