### ISSUE TITLE
processes removed from Profile cannot be stopped

### ISSUE THREAD

**Issue by bfosberry** [deis/deis#2930] opened 2015-01-20 18:08 UTC
When an item is removed from the source code procfile, deis does not stop the containers. After the item is no longer in the Procfile it becomes impossible to stop the containers:
```
Brendans-MacBook-Air:hercules bfosberry$ deis ps | grep transacted
--- transacted_tender_importer:
transacted_tender_importer.1 up (v109)
--- transacted_item_importer:
transacted_item_importer.1 up (v109)
Brendans-MacBook-Air:hercules bfosberry$ deis scale transacted_tender_importer=0 
Scaling processes... but first, coffee!
400 BAD REQUEST
Container type transacted_tender_importer does not exist in application
```

**Comment by bacongobbler** [comment] 2015-01-20 18:26
dupe of #1639, however let's keep the discussion rolling here as the scheduler changes did not fix this.

**Closed** 2015-02-23 20:27 UTC
Labels: bug
