### ISSUE TITLE
fatal: 'somerepo.git' does not appear to be a git repository

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4557] opened 2015-10-01 17:51 UTC
Getting this error when pushing to deis. I tried to restart deis-builder but same problem.

```bash
$ git push deis
fatal: 'bsync-test-green.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

deis-builder logs:

```
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: [info] Key accepted for user git.
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: [info] Channel type: session
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: Key='LANG', Value='en_US.UTF-8'
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: Key='LC_ALL', Value='en_US.UTF-8'
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: Key='LC_CTYPE', Value='UTF-8'
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: [info] Checking user /deis/builder/users/olalonde
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: [info] Found user olalonde for fingerprint 62:c7:52:a8:aa:41:1d:5c:d6:80:4c:3d:7b:45:da:30
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: [info] Directory /home/git/bsync-test-green.git already exists.
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: [info] git-shell -c git-receive-pack 'bsync-test-green.git'
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: Waiting for git-receive to run.
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: Waiting for deploy.
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: [error] Error on command: exit status 128
Oct 01 17:50:04 ip-10-21-2-84.ec2.internal sh[311]: [error] Failed git receive: exit status 128
```

**Comment by olalonde** [comment] 2015-10-01 18:44
Fixed by removing `/home/git/bsync-test-green` in the deis-builder container. Though I'm not sure why this happened in the first place.

**Comment by krancour** [comment] 2015-10-01 19:45
Similar to and possibly related to #3458

**Comment by clayzermk1** [comment] 2015-10-20 21:58
:+1: seeing this as well on Deis 1.10.1 with stable CoreOs.

```
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: [info] Checking closer.
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: [info] Accepted connection.
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: [info] Adding key 'command="/usr/local/bin/gitreceive run clayzermk1 e4:20:82:f2:da:9d:08:59:db:68:cc:1f:42:a3:dd:a7",no-agent-forwarding,no-pty,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa <snip> clayzermk1@gmail.com'
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: [info] Adding key 'command="/usr/local/bin/gitreceive run <other user fingerprint snip>",no-agent-forwarding,no-pty,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa <other user snip>'
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: [info] Key accepted for user git.
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: [info] Channel type: session
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: Key='LANG', Value='en_US.UTF-8'
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: [info] Checking user /deis/builder/users/clayzermk1
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: [info] Found user clayzermk1 for fingerprint <snip>
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: [info] Directory /home/git/api-v2-staging.git already exists.
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: [info] git-shell -c git-receive-pack 'api-v2-staging.git'
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: Waiting for git-receive to run.
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: Waiting for deploy.
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: [error] Error on command: exit status 128
Oct 20 21:44:42 ip-10-21-2-102.ec2.internal sh[32548]: [error] Failed git receive: exit status 128
```

This is repeated three times. On the third time it fails after "Waiting for deploy."

**Comment by wajatimur** [comment] 2015-11-04 14:06
This happen when your current git repo is diverge from you previous push/deploy to deis. The message is standard git reply message if I were not mistaken.

**Comment by krancour** [comment] 2015-11-04 14:10
I'm pretty sure at this point that this is a duplicate of #3458.  #3458 was inadvertently addressed by a recent commit.  master and v1.12.0 (to be cut soon) should be ok.  Because the root cause is still not well understood, I also intend to merge #4689 as a failsafe.

Closing this since the issue and related work are already tracked.

**Closed by krancour** 2015-11-04 14:10 UTC
Labels: bug, builder
