### ISSUE TITLE
deis create issue

### ISSUE THREAD

**Issue by ainux4mrvce** [deis/deis#3864] opened 2015-06-12 08:33 UTC
@bacongobbler if i try to do <h3>deis create</h3> it shows 
vidyuth@Thunderbolt:~/rvce$ deis create
Creating application... done, created expert-frosting
fatal: remote deis already exists.
Could not create Deis remote

**Comment by szymonpk** [comment] 2015-06-12 08:37
You have remote already run `git remote -v`, if it doesn't match your current deis cluster run `git remote rm` and then `deis git:remote`.

**Comment by ainux4mrvce** [comment] 2015-06-12 08:39
but i do same thing with other app like : https://github.com/tutumcloud/tutum-docker-lamp its works totally fine 

<h3>vidyuth@Thunderbolt:~$ cd tutum-docker-lamp/
vidyuth@Thunderbolt:~/tutum-docker-lamp$ deis create
Creating application... done, created quoted-yeomanry
Git remote deis added

**Comment by szymonpk** [comment] 2015-06-12 08:41
Msg is pretty clear, remote already exist (so use it or ignore it :p), maybe you've run 'deis create' twice on this directory.

**Comment by ainux4mrvce** [comment] 2015-06-12 08:41
ya i did that how to overcome from it

**Comment by ainux4mrvce** [comment] 2015-06-12 12:46
can you tell more specifically what steps should i use

**Comment by bacongobbler** [comment] 2015-06-12 15:12
@ainux4mrvce use `git remote rm deis`.

Closing as a duplicate of https://github.com/deis/deis/issues/3368 since we also have a `--remote` flag to rename th destination remote.

**Closed by bacongobbler** 2015-06-12 15:12 UTC
