### ISSUE TITLE
store daemon is giving errors

### ISSUE THREAD

**Issue by s20691033** [deis/deis#3884] opened 2015-06-17 00:10 UTC
Hi guys,

I happen to find the store-daemon is producing errors:

```
Jun 17 10:09:05 Server.001 sh[4020]: 2015-06-17 00:09:05.539544 7f15768a2700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:05 Server.001 sh[4020]: 2015-06-17 00:09:05.784042 7f15780a5700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:05 Server.001 sh[4020]: 2015-06-17 00:09:05.900265 7f15788a6700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:06 Server.001 sh[4020]: 2015-06-17 00:09:06.276904 7f15780a5700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:06 Server.001 sh[4020]: 2015-06-17 00:09:06.862234 7f15780a5700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:10 Server.001 sh[4020]: 2015-06-17 00:09:10.050524 7f15780a5700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:10 Server.001 sh[4020]: 2015-06-17 00:09:10.170996 7f15798a8700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:10 Server.001 sh[4020]: 2015-06-17 00:09:10.430982 7f15798a8700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:10 Server.001 sh[4020]: 2015-06-17 00:09:10.547172 7f15798a8700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:11 Server.001 sh[4020]: 2015-06-17 00:09:11.753881 7f15788a6700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:11 Server.001 sh[4020]: 2015-06-17 00:09:11.973517 7f15780a5700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:13 Server.001 sh[4020]: 2015-06-17 00:09:13.619197 7f15788a6700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:14 Server.001 sh[4020]: 2015-06-17 00:09:14.031771 7f15758a0700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:14 Server.001 sh[4020]: 2015-06-17 00:09:14.311059 7f15768a2700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:14 Server.001 sh[4020]: 2015-06-17 00:09:14.580819 7f15758a0700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:14 Server.001 sh[4020]: 2015-06-17 00:09:14.708584 7f15788a6700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:15 Server.001 sh[4020]: 2015-06-17 00:09:15.098223 7f15758a0700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jun 17 10:09:15 Server.001 sh[4020]: 2015-06-17 00:09:15.654962 7f15758a0700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
```

But I'm not sure what is not working

**Comment by carmstrong** [comment] 2015-06-17 03:22
Hi @s20691033 can you confirm this is Deis v1.7.3? What version of CoreOS is this? (`cat /etc/os-release`)

**Comment by s20691033** [comment] 2015-06-17 03:29
It is 1.7.3

But I'm not running CoreOS, it's CentOS7
···
[root@Server.001 logs]# uname -a
Linux Server.001  3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
···

**Comment by carmstrong** [comment] 2015-06-17 04:07
> But I'm not running CoreOS, it's CentOS7

Wow... you're running Deis on CentOS? I'm surprised you got it working! Unfortunately that's an unsupported platform, so I'm not sure where to begin helping. I know that there have been a bunch of kernel fixes related to Ceph that you don't have with that kernel version.

**Comment by s20691033** [comment] 2015-06-17 05:37
It's working and functional mostly ..

How ever I checked the ceph's Doc , and centOS should be supported by them

anyway, do you happen to know what fixes need to be installed by any chance?

**Comment by bacongobbler** [comment] 2015-06-17 06:13
@carmstrong it's technically possible to run Deis on CoreOS. Whether we officially support running Deis on a CentOS-based cluster is another question, though. As an example, I'm working on a PoC here, which is still a work in progress, but "most" of the functionality is there: https://github.com/fishworks/deis-cookbook

@s20691033 do you see this error with the default installation? I'd ask the ceph user mailing list as at this point it looks like it's out of scope unless you can reproduce on CoreOS's stable channel. I don't know what fixes need to be applied to make Ceph work for you.

**Comment by carmstrong** [comment] 2015-06-17 06:30
> it's technically possible to run Deis on CentOS

I wasn't arguing that :) But it's certainly not either a recommended or supported path.

**Closed** 2015-06-17 06:32 UTC
