### ISSUE TITLE
deis limits:set not persistent after upgrade

### ISSUE THREAD

**Issue by azurewraith** [deis/deis#3234] opened 2015-03-08 15:26 UTC
I upgraded from `1.2.1` -> `1.4.1` and everything seems to be working fine except all of the custom limits I had set on a per-app basis had disappeared and now are 'unset' to `Unlimited`..

    [bcochran@schala a-demo|master *]$ deis releases
    === a-demo Releases
    v4      Sun Feb 15 10:49:51 2015 CST bcochran deployed b803d82
    v3      Mon Jan 26 16:10:29 2015 CST bcochran deployed 9cef9c1
    v2      Sun Jan 18 13:22:09 2015 CST bcochran deployed d328a95
    v1      Sun Jan 18 13:14:15 2015 CST bcochran created initial release
    
    [bcochran@schala a-demo|master *]$ deis limits
    === a-demo Limits
    
    --- Memory
    Unlimited
    
    --- CPU
    Unlimited

Just yesterday I set these to 712M and 1024 respectively.  It seems those revisions get wiped clean upon upgrade and do not get reset properly.

**Comment by bacongobbler** [comment] 2015-03-08 15:42
If you look directly in the database logs, does it indicate that any of the backups failed to upload to ceph/failed to restore any of the backups?

**Comment by bacongobbler** [comment] 2015-03-08 15:43
related: https://github.com/deis/deis/issues/2819

**Comment by aledbf** [comment] 2015-03-08 15:59
@bacongobbler I think that this https://github.com/deis/deis/pull/3128 is the cause.
I just hit the same issue

**Comment by azurewraith** [comment] 2015-03-08 16:11
I looked in my database logs but it logs somewhat frequently (past the time I upgraded) but everything seems to be backing up normally.

These limits were set at some points more than a week ago before the upgrade, it is a little hard to believe that the database wouldn't have sync'd by then when my log shows it syncing every few minutes.

I looked at my ceph cluster and it is in a `HEALTH_WARN` state for clock skew and low disk space.  The clock skew seems to be fairly common, like the NTP service fails to refresh after a cluster has been alive for some time.

**Comment by wenzowski** [comment] 2015-03-11 08:27
Did you check the database logs? I tried one of these, and it took a very long time for wal-e to bring back postgres.

**Comment by wenzowski** [comment] 2015-03-11 08:29
...as in long enough (*hours*) for me to get pissed & nuke the cluster & start from scratch. so I have no idea if backups would have worked.

**Comment by azurewraith** [comment] 2015-03-11 13:49
well it looked as though it was backing up to wal-e, so I assume it had restored enough to gain functionality....

probably going to have to nuke this cluster, though.

**Comment by azurewraith** [comment] 2015-03-12 17:51
Last chance to take a peek at any particulars of my non-working cluster for the purposes of root causing this...  let me know what you'd like to see, and I'll provide it in a gist.

**Comment by bacongobbler** [comment] 2015-03-12 17:53
@azurewraith do you have logs from the database boot? That would be useful to figure out if it properly restored from those backups.

**Comment by azurewraith** [comment] 2015-03-12 23:31
I'd need a way of looking past where `deisctl logs` gets me.  I tried looking on the container itself but the log files were empty...

**Comment by bacongobbler** [comment] 2015-03-13 00:07
If you log onto the host, `docker logs deis-database` will give you the full logs

**Comment by azurewraith** [comment] 2015-03-13 02:20
https://gist.github.com/azurewraith/34afc9657c3f64ca3c88

Let me know if you need more info.  This issue wasn't serious enough to break me but none of my git pushes register in the builder properly...

https://gist.github.com/azurewraith/97c0d9edeea7100402fd

**Comment by aledbf** [comment] 2015-03-13 02:31
@bacongobbler the gist is very similar to https://github.com/deis/deis/issues/3276

**Comment by carmstrong** [comment] 2015-03-16 20:48
> the gist is very similar to #3276

I think this is likely addressed by #3128.

**Closed** 2015-04-03 17:31 UTC
Labels: bug
