### ISSUE TITLE
Failure in deis registry

### ISSUE THREAD

**Issue by withinboredom** [deis/deis#3015] opened 2015-02-02 23:30 UTC
This is repeated in the journal:

Feb 02 23:18:21 core3 systemd[1]: Unit deis-registry@1.service entered failed state.
Feb 02 23:18:26 core3 systemd[1]: deis-registry@1.service holdoff time over, scheduling restart.
Feb 02 23:18:26 core3 systemd[1]: Stopping deis-registry...
Feb 02 23:18:26 core3 systemd[1]: Starting deis-registry...
Feb 02 23:18:26 core3 sh[28809]: Error: No such image or container: deis-registry
Feb 02 23:18:26 core3 systemd[1]: Started deis-registry.
Feb 02 23:18:43 core3 sh[28824]: 2015-02-02T23:18:43Z 8b28f2753b48 confd[35]: ERROR exit status 1
Feb 02 23:18:43 core3 sh[28824]: registry: waiting for confd to write initial templates...
Feb 02 23:27:48 core3 sh[28824]: Traceback (most recent call last):
Feb 02 23:27:48 core3 sh[28824]: File "/app/bin/create_bucket", line 15, in <module>
Feb 02 23:27:48 core3 sh[28824]: if not bucket in conn.get_all_buckets():
Feb 02 23:27:48 core3 sh[28824]: File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 436, in get_all_buckets
Feb 02 23:27:48 core3 sh[28824]: response = self.make_request('GET', headers=headers)
Feb 02 23:27:48 core3 sh[28824]: File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
Feb 02 23:27:48 core3 sh[28824]: retry_handler=retry_handler
Feb 02 23:27:48 core3 sh[28824]: File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1068, in make_request
Feb 02 23:27:48 core3 sh[28824]: retry_handler=retry_handler)
Feb 02 23:27:48 core3 sh[28824]: File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 943, in _mexe
Feb 02 23:27:48 core3 sh[28824]: response = connection.getresponse()
Feb 02 23:27:48 core3 sh[28824]: File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
Feb 02 23:27:48 core3 sh[28824]: response.begin()
Feb 02 23:27:48 core3 sh[28824]: File "/usr/lib/python2.7/httplib.py", line 409, in begin
Feb 02 23:27:48 core3 sh[28824]: version, status, reason = self._read_status()
Feb 02 23:27:48 core3 sh[28824]: File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
Feb 02 23:27:48 core3 sh[28824]: line = self.fp.readline(_MAXLINE + 1)
Feb 02 23:27:48 core3 sh[28824]: File "/usr/lib/python2.7/socket.py", line 476, in readline
Feb 02 23:27:48 core3 sh[28824]: data = self._sock.recv(self._rbufsize)
Feb 02 23:27:48 core3 sh[28824]: socket.timeout: timed out
Feb 02 23:27:49 core3 systemd[1]: deis-registry@1.service: main process exited, code=exited, status=1/FAILURE
Feb 02 23:27:49 core3 docker[29034]: Error response from daemon: No such container: deis-registry
Feb 02 23:27:49 core3 docker[29034]: 2015/02/02 23:27:49 Error: failed to remove one or more containers
Feb 02 23:27:49 core3 systemd[1]: Unit deis-registry@1.service entered failed state.
Feb 02 23:27:54 core3 systemd[1]: deis-registry@1.service holdoff time over, scheduling restart.
Feb 02 23:27:54 core3 systemd[1]: Stopping deis-registry...
Feb 02 23:27:54 core3 systemd[1]: Starting deis-registry...
Feb 02 23:27:54 core3 sh[29077]: Error: No such image or container: deis-registry
Feb 02 23:27:54 core3 systemd[1]: Started deis-registry.
Feb 02 23:28:11 core3 sh[29094]: 2015-02-02T23:28:11Z e332ea3d3081 confd[32]: ERROR exit status 1
Feb 02 23:28:11 core3 sh[29094]: registry: waiting for confd to write initial templates...

**Comment by carmstrong** [comment] 2015-02-02 23:51
@withinboredom Does the output from `store-gateway` look healthy? The errors from registry indicate that is the root cause.

**Comment by withinboredom** [comment] 2015-02-03 00:02
Issue was that one of the nodes ran out of diskspace, if I wanted to mount another drive, where would I want to mount it?

**Comment by carmstrong** [comment] 2015-02-03 02:18
> Issue was that one of the nodes ran out of diskspace, if I wanted to mount another drive, where would I want to mount it?

That depends on what platform you're running Deis on, and which mount is out of space.

See also #2886.

**Comment by withinboredom** [comment] 2015-02-03 04:40
Currently running on Azure. Root (/) was out of diskspace (95% used).

Looked like it was the local cache of images. On Azure, at least the images I was playing with, I was limited to 30GB root disks and I could attach more disks that got auto-mounted to /opt. Naturally, I can move the mount, after attaching them, but need to know where I can get the most bang for my buck...

A nice feature would be being able to specify where deis's files get stored at platform install, including the location of the ceph mount... that may be the most portable across all providers.

**Comment by carmstrong** [comment] 2015-02-03 06:01
Did you use the provision script in #2893? It should have attached a 100GB volume to use for Docker, which I suspect is using up the most data out of anything. Ceph should really only be using a few GB per machine. Although I need to flesh these out in more detail in #2559, here is some info:

* /var/lib/ceph is where Ceph stores its data, and this lives on the root volume
* /var/lib/docker is where Docker stores its data - on providers with external storage (EC2, GCE, Azure) this is a separate volume

I'm going to close this issue as Azure isn't yet a supported platform, and the provision script and accompanying documentation will prevent issues like this on Azure. Good to see you mostly got things running, though!

**Closed by carmstrong** 2015-02-03 06:01 UTC
