### ISSUE TITLE
Deis Builder resets key after upgrade / restart

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#3474] opened 2015-04-14 09:40 UTC
I updated deis from v1.4.1 to v1.5.1 yesterday.
I had troubles starting up the deis builder, so I've manually restarted it during the upgrade (which might not have been the best idea)

After pushing (for the first time after update) today I got the following error

~~~~~
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:RANDOMRANDOMRANDOM.
Please contact your system administrator.
Add correct host key in /home/nathan/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/nathan/.ssh/known_hosts:113
ECDSA host key for [deis.apps.myhost]:2222 has changed and you have requested strict checking.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
~~~~~~

I've done as suggested, and removed the key from known_hosts. But obviously I might have been udner a real MITM attack...

**Comment by bacongobbler** [comment] 2015-04-17 21:53
relevant: https://github.com/deis/deis/pull/2203

**Comment by mboersma** [comment] 2015-04-19 11:58
This is a duplicate of #3092.

**Closed by mboersma** 2015-04-19 11:58 UTC
