### ISSUE TITLE
deisctl: Add more keys for access

### ISSUE THREAD

**Issue by mooyah** [deis/deis#4933] opened 2016-02-24 22:54 UTC
What is the recommended way of adding more ssh-keys to deisctl? I need to grant more people on my team access to "dock" to containers to debug issues. I first suggested they use deis apps:run, but that doesn't allow them to create a bash session and try to investigate the container.

Do you have any suggestions or best practices for this type of access?

TYIA for your help.

**Comment by bacongobbler** [comment] 2016-02-24 23:02
It's true that `deis run bash` (i.e. long-running bi-directional TCP connections) is still an unsolved problem. See #117 (one of our oldest bugs). Most administrators have been giving users access to the cluster so they can run `docker exec -it myapp_v2.web.1 bash` for the time being. It's both a technical problem with fleet and with WSGI being unable to handle long-running client requests.

Closing as a duplicate of #117 so we can keep all conversations related to interactive shell sessions in that ticket (including workarounds). Thanks!

**Closed by bacongobbler** 2016-02-24 23:02 UTC

**Comment by krancour** [comment] 2016-02-25 17:56
> What is the recommended way of adding more ssh-keys to deisctl?

I haven't done this, but I've seen something _similar_ done.  You could include a unit on every host that routinely checks for an `authorized_keys` file in a publicly accessible location such as a github repo or a gist.  It would contain the public keys of people who should be able to use deisctl and ssh to the host.
