### ISSUE TITLE
The builder is leaving behind files.

### ISSUE THREAD

**Issue by kalbasit** [deis/deis#3570] opened 2015-04-23 22:16 UTC
On the deis-builder `/home/git` is full of:

```
$ ls -la .receiver* | wc -l
89
$ ls -l
[...]
-rw------- 1 root root 529 Apr 21 04:33 .receiver796207336
-rw------- 1 root root 517 Apr 20 20:27 .receiver856541792
-rw------- 1 root root 517 Apr 20 20:27 .receiver887119175
-rw------- 1 root root 517 Apr 21 04:33 .receiver899304851
-rw------- 1 root root 517 Apr 20 20:27 .receiver921569884
-rw------- 1 root root 517 Apr 20 20:27 .receiver922349812
-rw------- 1 root root 529 Apr 21 04:33 .receiver923056395
-rw------- 1 root root 529 Apr 21 04:33 .receiver932673847
-rw------- 1 root root 529 Apr 21 04:33 .receiver964918569
-rw------- 1 root root 517 Apr 20 20:27 .receiver971662746
-rw------- 1 root root 529 Apr 21 04:33 .receiver984877335
-rw------- 1 root root 517 Apr 20 20:27 .receiver988812749
```

```
root@1c6fd3da811b:/home/git# diff -Naur receiver .receiver988812749
--- receiver    2015-04-20 07:40:00.313608000 +0000
+++ .receiver988812749  2015-04-20 20:27:42.122608000 +0000
@@ -12,4 +12,4 @@
   -H 'Content-Type: application/json' \
   -H "X-Deis-Builder-Auth: ..." \
   -d "{\"receive_user\": \"$username\", \"receive_repo\": \"$app\", \"sha\": \"$sha\", \"fingerprint\": \"$fingerprint\", \"ssh_connection\": \"$SSH_CONNECTION\", \"ssh_original_command\": \"$SSH_ORIGINAL_COMMAND\"}" \
-  --silent http://10.21.1.242:8000/v1/hooks/push >/dev/null
+  --silent http://
\ No newline at end of file
```

This is of course is not an issue now, but it will be once it takes a lot of space.

**Comment by bacongobbler** [comment] 2015-04-23 22:38
Looks like cruft from confd which isn't getting cleaned up.

**Comment by mboersma** [comment] 2015-04-29 19:49
Confirmed that there are still `confd` droppings in master, after running the integration tests:
```console
$ docker exec -it f05ca2140890 bash
# ls -la /home/git/
total 104
drwxr-xr-x 1 git  git  4096 Apr 29 19:47 .
drwxr-xr-x 1 root root 4096 Apr 29 19:23 ..
-rw------- 1 root root 1419 Apr 29 19:24 .builder426783943
-rw------- 1 root root 1419 Apr 29 19:24 .builder686933522
-rw------- 1 root root 1419 Apr 29 19:24 .builder694223400
-rw------- 1 root root 1426 Apr 29 19:24 .builder889896394
-rw------- 1 root root 1426 Apr 29 19:24 .builder946466344
drwx------ 2 git  git  4096 Apr 29 19:32 .cache
-rw------- 1 root root  188 Apr 29 19:24 .receiver189588956
-rw------- 1 root root  188 Apr 29 19:24 .receiver370842859
-rw------- 1 root root  517 Apr 29 19:24 .receiver381270492
-rw------- 1 root root  188 Apr 29 19:24 .receiver790178662
-rw------- 1 root root  517 Apr 29 19:24 .receiver902437022
drwxr-xr-x 1 git  git  4096 Apr 29 19:47 .ssh
drwxrwxr-x 9 git  git  4096 Apr 29 19:33 appssample.git
-rwxr-xr-x 1 root root 4828 Apr 29 19:24 builder
drwxrwxr-x 9 git  git  4096 Apr 29 19:35 buildsample.git
-rwxr-xr-x 1 root root  586 Apr 29 19:24 check-repos
drwxrwxr-x 9 git  git  4096 Apr 29 19:37 configsample.git
drwxrwxr-x 9 git  git  4096 Apr 29 19:41 domainsample.git
drwxrwxr-x 9 git  git  4096 Apr 29 19:43 permssample.git
drwxrwxr-x 9 git  git  4096 Apr 29 19:44 pssample.git
-rwxr-xr-x 1 root root  560 Apr 29 19:24 receiver
drwxrwxr-x 9 git  git  4096 Apr 29 19:45 releasessample.git
-rw-r--r-- 5 root root   98 Apr 21 16:18 shim.dockerfile
```

**Comment by carmstrong** [comment] 2015-05-26 23:36
This is fixed upstream: https://github.com/kelseyhightower/confd/commit/a6b03e1d363bc957cb02a80baa11c3113aa049e9

I think @kelseyhightower has plans to cut a new confd release this week with some fixes. We should bump to that once it's released.

**Comment by mboersma** [comment] 2015-06-16 22:37
The fix is in there, but no new `confd` release yet...

**Closed** 2015-06-25 00:45 UTC
Labels: builder
