### ISSUE TITLE
azure-coreos-cluster fails with "socket.error: [Errno 61] Connection refused"

### ISSUE THREAD

**Issue by josephwinston** [deis/deis#3725] opened 2015-05-20 13:41 UTC
I'm following the instructions on <http://docs.deis.io/en/latest/installing_deis/azure/> and I'm having issues with `azure-coreos-cluster`.  This is running on OS X 10.10.4 using anaconda with `conda install` for both `azure` and  `pyyaml`.

As instructed, I've modified `cert.conf` in ` contrib/azure` and then ran `./generate-mgmt-cert.sh` in the same directory.  Then I uploaded `azure-cert.cer` to <https://manage.windowsazure.com/#Workspaces/AdminTasks/ListManagementCertificates> and saved the subscription_id.  `./create-azure-user-data $(curl -s https://discovery.etcd.io/new)` ran without issues.

When I ran

```bash
./azure-coreos-cluster deis_cloud \
--subscription my-subscription-id \
--azure-cert azure-cert.pem \
--num-nodes 5 \
--location "Central US" \
--vm-size A6 \
--pip \
--deis \
--blob-container-url https://data.blob.core.windows.net/vhds/ \
--data-disk \
--custom-data azure-user-data
```
I received the following error:

```bash
SSH arguments not given, generating certificate
Generated SSH certificate with thumbprint 3615F18BCB854905A0065B46373E0477F3716BF4
Creating the hosted service...
Traceback (most recent call last):
  File "./azure-coreos-cluster", line 190, in <module>
    args.cloud_service_name, label=args.cloud_service_name, location=args.location)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementservice.py", line 378, in create_hosted_service
    extended_properties))
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 339, in _perform_post
    response = self.perform_post(path, body, x_ms_version)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 184, in perform_post
    response = self._perform_request(request)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 294, in _perform_request
    resp = self._filter(request)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/azure/http/httpclient.py", line 221, in perform_request
    self.send_request_headers(connection, request.headers)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/azure/http/httpclient.py", line 200, in send_request_headers
    connection.endheaders()
  File "/Users/hb55683/anaconda/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/Users/hb55683/anaconda/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/Users/hb55683/anaconda/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/Users/hb55683/anaconda/lib/python2.7/httplib.py", line 1204, in connect
    HTTPConnection.connect(self)
  File "/Users/hb55683/anaconda/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/Users/hb55683/anaconda/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 61] Connection refused
```

What should I do to troubleshoot this issue?

**Comment by carmstrong** [comment] 2015-05-20 14:57
@josephwinston On a hunch, I'd try using a hosted service name without underscores. Try something like "deiscloud".

**Comment by josephwinston** [comment] 2015-05-20 23:41
Outside of the authenticating proxy (`ntlm`) and using the same arguments as before, the error becomes:

```bash
SSH arguments not given, generating certificate
Generated SSH certificate with thumbprint A5B54E325D89489504EC0737A0035C615D1FEA8B
Creating the hosted service...

Traceback (most recent call last):
  File "./azure-coreos-cluster", line 190, in <module>
    args.cloud_service_name, label=args.cloud_service_name, location=args.location)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementservice.py", line 378, in create_hosted_service
    extended_properties))
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 339, in _perform_post
    response = self.perform_post(path, body, x_ms_version)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 184, in perform_post
    response = self._perform_request(request)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 296, in _perform_request
    return _management_error_handler(ex)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/azure/servicemanagement/__init__.py", line 1996, in _management_error_handler
    return _general_error_handler(http_error)
  File "/Users/hb55683/anaconda/lib/python2.7/site-packages/azure/__init__.py", line 549, in _general_error_handler
    http_error.respbody.decode('utf-8-sig'))
azure.WindowsAzureError: Unknown error (Bad Request)
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>The hosted service name is invalid.</Message></Error>
```

You were also correct about the name @carmstrong.

However, the original issue reported is happening using the correct form for the host name even though I have `cntlm` set with `http_proxy` as well as `https_proxy` and this setup is know to work inside of the firewall.  The question here then is around what does the application need in addition to these two environment variables?

**Comment by carmstrong** [comment] 2015-05-21 21:21
@josephwinston From your last line, you're still getting: `The hosted service name is invalid.`. What hosted service name are you trying? Perhaps it already exists and you're stuck in a semi-created state?

**Comment by mboersma** [comment] 2015-06-17 17:08
@josephwinston did you get any further with the `hosted service name is invalid` issue?

**Comment by josephwinston** [comment] 2015-06-17 19:13
I have not tried anything else.

**Comment by mboersma** [comment] 2015-06-30 16:53
I'm going to close this since it doesn't appear there's anything Deis can address directly, but please re-open it if it persists and is reproducible with [Deis v1.7.3](https://github.com/deis/deis/releases).

**Closed by mboersma** 2015-06-30 16:53 UTC
Labels: contrib and provisioning
