### ISSUE TITLE
deisctl install platform

### ISSUE THREAD

**Issue by ainux4mrvce** [deis/deis#3615] opened 2015-05-03 08:00 UTC
$deisctl install platform
every time i tries to install deisctl platform i get this error message 
o/p
Error: Missing platform domain, use:
deisctl config platform set domain=<your-domain>

i allready use the command : "$deisctl config platform set domain=local3.deisapp.com".

**Comment by mboersma** [comment] 2015-05-03 14:16
`deisctl` only prints that error message if it thinks the etcd key /deis/platform/domain doesn't exist. The code in question is here: https://github.com/deis/deis/blob/master/deisctl/cmd/cmd.go#L120-L125

What does this command return?
```console
$ deisctl config platform get domain
```

**Comment by ainux4mrvce** [comment] 2015-05-03 16:11
@mboersma 
deis$ deisctl config platform get domain 
Error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

i read all the comment of "https://github.com/deis/deis/issues/3117" even i have all this problem along with this actually i don't understand how to follow the step given on "deis.io" and where to install deisctl on host or vm on which coreos is install

**Comment by bacongobbler** [comment] 2015-05-03 16:25
To clear things up, have you followed the instructions on [how to set up deisctl](http://docs.deis.io/en/latest/installing_deis/install-platform/#install-the-deis-platform)? That error indicates that either a) you forgot to set $DEISCTL_TUNNEL or b) etcd is down.

> actually i don't understand how to follow the step given on "deis.io" and where to install deisctl on host or vm on which coreos is install

The documentation on how to install `deisctl` is [here](http://docs.deis.io/en/latest/installing_deis/install-deisctl/). When you provision the CoreOS hosts using our scripts in `contrib`, deisctl will be installed for you on every host so you don't have to follow the earlier steps, but if you want to connect remotely through an SSH tunnel then the documentation shows you how to set that up. Otherwise you can just use `ssh -A core@node-ip-address` and run `deisctl` from there. :)

**Comment by ainux4mrvce** [comment] 2015-05-03 16:49
do we really need 8 Gb RAM for doing all this, cause i have only 4 Gb RAM on my laptop. I followed all the step as given on  "http://docs.deis.io/en/latest/installing_deis/install-platform/#install-the-deis-platforml" along with "$DEISCTL_TUNNEL". if i do fresh installation its work for very first only and stucks at step "$deisctl install platform" or either "$deisctl start platform" in the same way phspagiari said on his comments "https://github.com/deis/deis/issues/3117"

**Comment by bacongobbler** [comment] 2015-05-03 17:03
If you're running a cluster on vagrant, you'll need [at least 16GB](http://docs.deis.io/en/latest/installing_deis/system-requirements/#resources).

Could you please try the following to retrieve etcd logs: `vagrant ssh deis-01 -c journalctl --no-pager -u etcd`

**Comment by ainux4mrvce** [comment] 2015-05-03 17:19
core@deis-01 ~ $  journalctl --no-pager -u etcd

o/p :
-- Logs begin at Sun 2015-05-03 16:00:09 UTC, end at Sun 2015-05-03 17:18:45 UTC. --
May 03 16:00:22 deis-01 systemd[1]: Starting etcd...
May 03 16:00:22 deis-01 systemd[1]: Started etcd.
May 03 16:00:22 deis-01 etcd[936]: [etcd] May  3 16:00:22.941 INFO      | Discovery via https://discovery.etcd.io using prefix /d5ea800a476e1dfbf6b8965dab74cf31.
May 03 16:00:28 deis-01 etcd[936]: [etcd] May  3 16:00:28.060 INFO      | Discovery _state was empty, so this machine is the initial leader.
May 03 16:00:28 deis-01 etcd[936]: [etcd] May  3 16:00:28.060 INFO      | Discovery fetched back peer list: []
May 03 16:00:28 deis-01 etcd[936]: [etcd] May  3 16:00:28.060 INFO      | f55c0088858549869df3a54c8fb61232 is starting a new cluster
May 03 16:00:28 deis-01 etcd[936]: [etcd] May  3 16:00:28.062 INFO      | etcd server [name f55c0088858549869df3a54c8fb61232, listen on :4001, advertised url http://172.17.8.100:4001]
May 03 16:00:28 deis-01 etcd[936]: [etcd] May  3 16:00:28.062 INFO      | peer server [name f55c0088858549869df3a54c8fb61232, listen on :7001, advertised url http://172.17.8.100:7001]
May 03 16:00:28 deis-01 etcd[936]: [etcd] May  3 16:00:28.063 INFO      | f55c0088858549869df3a54c8fb61232 starting in peer mode
May 03 16:00:28 deis-01 etcd[936]: [etcd] May  3 16:00:28.063 INFO      | f55c0088858549869df3a54c8fb61232: state changed from 'initialized' to 'follower'.
May 03 16:00:28 deis-01 etcd[936]: [etcd] May  3 16:00:28.063 INFO      | f55c0088858549869df3a54c8fb61232: state changed from 'follower' to 'leader'.
May 03 16:00:28 deis-01 etcd[936]: [etcd] May  3 16:00:28.063 INFO      | f55c0088858549869df3a54c8fb61232: leader changed from '' to 'f55c0088858549869df3a54c8fb61232'.
May 03 16:00:28 deis-01 etcd[936]: [etcd] May  3 16:00:28.116 INFO      | f55c0088858549869df3a54c8fb61232: available_internal_versions [1] is registered into key space successfully.
May 03 16:37:07 deis-01 systemd[1]: Stopping etcd...
May 03 16:37:07 deis-01 systemd[1]: etcd.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 03 16:37:07 deis-01 systemd[1]: Stopped etcd.
May 03 16:37:07 deis-01 systemd[1]: Unit etcd.service entered failed state.
May 03 16:37:07 deis-01 systemd[1]: etcd.service failed.
-- Reboot --
May 03 17:13:44 deis-01 systemd[1]: Starting etcd...
May 03 17:13:44 deis-01 systemd[1]: Started etcd.
May 03 17:13:45 deis-01 etcd[542]: [etcd] May  3 17:13:45.119 INFO      | Peer URLs in log:  / f55c0088858549869df3a54c8fb61232 (http://172.17.8.100:7001)
May 03 17:13:45 deis-01 etcd[542]: [etcd] May  3 17:13:45.120 INFO      | Discovery via https://discovery.etcd.io using prefix /d5ea800a476e1dfbf6b8965dab74cf31.
May 03 17:13:50 deis-01 etcd[542]: [etcd] May  3 17:13:50.669 WARNING   | Discovery encountered an error: Discovery found an initialized cluster but no reachable peers are registered.
May 03 17:13:50 deis-01 etcd[542]: [etcd] May  3 17:13:50.671 INFO      | etcd server [name f55c0088858549869df3a54c8fb61232, listen on :4001, advertised url http://172.17.8.100:4001]
May 03 17:13:50 deis-01 etcd[542]: [etcd] May  3 17:13:50.671 INFO      | peer server [name f55c0088858549869df3a54c8fb61232, listen on :7001, advertised url http://172.17.8.100:7001]
May 03 17:13:50 deis-01 etcd[542]: [etcd] May  3 17:13:50.671 INFO      | f55c0088858549869df3a54c8fb61232 starting in peer mode
May 03 17:13:50 deis-01 etcd[542]: [etcd] May  3 17:13:50.674 INFO      | f55c0088858549869df3a54c8fb61232: state changed from 'initialized' to 'follower'.
May 03 17:13:53 deis-01 etcd[542]: [etcd] May  3 17:13:53.716 INFO      | f55c0088858549869df3a54c8fb61232: state changed from 'follower' to 'candidate'.
May 03 17:13:53 deis-01 etcd[542]: [etcd] May  3 17:13:53.717 INFO      | f55c0088858549869df3a54c8fb61232: state changed from 'candidate' to 'leader'.
May 03 17:13:53 deis-01 etcd[542]: [etcd] May  3 17:13:53.717 INFO      | f55c0088858549869df3a54c8fb61232: leader changed from '' to 'f55c0088858549869df3a54c8fb61232'.
May 03 17:13:54 deis-01 etcd[542]: [etcd] May  3 17:13:54.899 INFO      | f55c0088858549869df3a54c8fb61232: available_internal_versions [1] is registered into key space successfully.

**Comment by bacongobbler** [comment] 2015-05-03 17:34
> Discovery encountered an error: Discovery found an initialized cluster but no reachable peers are registered.

that looks like a CoreOS "bug", which you'll have to re-generate the discovery URL: https://github.com/coreos/etcd/issues/842#issuecomment-47365146

Since this root issue has been [documented](http://docs.deis.io/en/latest/troubleshooting_deis/#all-the-given-peers-are-not-reachable) and raised several times in different issues, I'm going ahead and closing this as a duplicate of #830, #1176, #2696, and #3443.

**Closed by bacongobbler** 2015-05-03 17:34 UTC
Labels: deisctl

**Comment by ainux4mrvce** [comment] 2015-05-06 06:18
cmd: sudo ssh-add ~/.vagrant.d/insecure_private_key 
gives this Error : Could not open a connection to your authentication agent.

**Comment by bacongobbler** [comment] 2015-05-06 15:08
that means your ssh agent is not running. Run `eval $(ssh-agent -s)` as per http://docs.deis.io/en/latest/installing_deis/install-platform/

**Comment by ainux4mrvce** [comment] 2015-05-07 06:48
fail to install deisctl 
cmd : curl -sSL http://deis.io/deisctl/install.sh | sudo sh -s 1.5.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1572k  100 1572k    0     0  53036      0  0:00:30  0:00:30 --:--:--  100k
Verifying archive integrity... All good.
Uncompressing Deis Control Utility  100%  
Error: Get https://raw.githubusercontent.com/deis/deis/v1.5.2/deisctl/units/deis-builder.service: dial tcp: lookup raw.githubusercontent.com: no DNS servers

**Comment by ainux4mrvce** [comment] 2015-05-07 09:42
Did i made any mistake here i getting error at installation of deisctl install platform 

 curl -sSL http://deis.io/deisctl/install.sh | sudo sh -s 1.5.2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1572k  100 1572k    0     0   245k      0  0:00:06  0:00:06 --:--:--  323k
Verifying archive integrity... All good.
Uncompressing Deis Control Utility  100%  
Refreshed deis-builder.service from v1.5.2
Refreshed deis-cache.service from v1.5.2
Refreshed deis-controller.service from v1.5.2
Refreshed deis-database.service from v1.5.2
Refreshed deis-logger.service from v1.5.2
Refreshed deis-logspout.service from v1.5.2
Refreshed deis-publisher.service from v1.5.2
Refreshed deis-registry.service from v1.5.2
Refreshed deis-router.service from v1.5.2
Refreshed deis-store-admin.service from v1.5.2
Refreshed deis-store-daemon.service from v1.5.2
Refreshed deis-store-gateway.service from v1.5.2
Refreshed deis-store-metadata.service from v1.5.2
Refreshed deis-store-monitor.service from v1.5.2
Refreshed deis-store-volume.service from v1.5.2

deisctl is in the current directory and unit files are
in /home/mca/.deis/units. Please move deisctl to a
directory in your search PATH.

See http://docs.deis.io/ for documentation.

$ sudo ln -fs $PWD/deisctl /usr/local/bin/deisctl

[sudo] password for mca: 
no talloc stackframe at ../source3/param/loadparm.c:4864, leaking memory

~$ sudo ln -fs $PWD/deisctl /usr/local/bin/deisctl

~$ git clone https://github.com/deis/deis.git

~$ cd deis/

~/deis$ export DEIS_NUM_INSTANCES=3

~/deis$ make discovery-url && vagrant up

sed -e "s,# discovery:,discovery:," -e "s,discovery: https://discovery.etcd.io/.*,discovery: $(curl -s -w '\n' https://discovery.etcd.io/new)," contrib/coreos/user-data.example > contrib/coreos/user-data
Bringing machine 'deis-01' up with 'virtualbox' provider...
Bringing machine 'deis-02' up with 'virtualbox' provider...
Bringing machine 'deis-03' up with 'virtualbox' provider...
==> deis-01: Running triggers before up...
==> deis-01: Checking if box 'coreos-stable' is up to date...
==> deis-01: VirtualBox VM is already running.
==> deis-02: Running triggers before up...
==> deis-02: Checking if box 'coreos-stable' is up to date...
==> deis-02: VirtualBox VM is already running.
==> deis-03: Running triggers before up...
==> deis-03: Checking if box 'coreos-stable' is up to date...
==> deis-03: VirtualBox VM is already running.
mca@mca:~/deis$ vagrant halt
==> deis-03: Attempting graceful shutdown of VM...
==> deis-02: Attempting graceful shutdown of VM...
==> deis-01: Attempting graceful shutdown of VM...
mca@mca:~/deis$ make discovery-url && vagrant up
sed -e "s,# discovery:,discovery:," -e "s,discovery: https://discovery.etcd.io/.*,discovery: $(curl -s -w '\n' https://discovery.etcd.io/new)," contrib/coreos/user-data.example > contrib/coreos/user-data
Bringing machine 'deis-01' up with 'virtualbox' provider...
Bringing machine 'deis-02' up with 'virtualbox' provider...
Bringing machine 'deis-03' up with 'virtualbox' provider...
==> deis-01: Running triggers before up...
==> deis-01: Checking if box 'coreos-stable' is up to date...
==> deis-01: Clearing any previously set forwarded ports...
==> deis-01: Clearing any previously set network interfaces...
==> deis-01: Preparing network interfaces based on configuration...
    deis-01: Adapter 1: nat
    deis-01: Adapter 2: hostonly
==> deis-01: Forwarding ports...
    deis-01: 22 => 2222 (adapter 1)
==> deis-01: Running 'pre-boot' VM customizations...
==> deis-01: Booting VM...
==> deis-01: Waiting for machine to boot. This may take a few minutes...
    deis-01: SSH address: 127.0.0.1:2222
    deis-01: SSH username: core
    deis-01: SSH auth method: private key
    deis-01: Warning: Connection timeout. Retrying...
==> deis-01: Machine booted and ready!
==> deis-01: Setting hostname...
==> deis-01: Configuring and enabling network interfaces...
==> deis-01: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> deis-01: to force provisioning. Provisioners marked to run always will still run.
==> deis-02: Running triggers before up...
==> deis-02: Checking if box 'coreos-stable' is up to date...
==> deis-02: Clearing any previously set forwarded ports...
==> deis-02: Fixed port collision for 22 => 2222. Now on port 2200.
==> deis-02: Clearing any previously set network interfaces...
==> deis-02: Preparing network interfaces based on configuration...
    deis-02: Adapter 1: nat
    deis-02: Adapter 2: hostonly
==> deis-02: Forwarding ports...
    deis-02: 22 => 2200 (adapter 1)
==> deis-02: Running 'pre-boot' VM customizations...
==> deis-02: Booting VM...
==> deis-02: Waiting for machine to boot. This may take a few minutes...
    deis-02: SSH address: 127.0.0.1:2200
    deis-02: SSH username: core
    deis-02: SSH auth method: private key
    deis-02: Warning: Connection timeout. Retrying...
==> deis-02: Machine booted and ready!
==> deis-02: Setting hostname...
==> deis-02: Configuring and enabling network interfaces...
==> deis-02: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> deis-02: to force provisioning. Provisioners marked to run always will still run.
==> deis-03: Running triggers before up...
==> deis-03: Checking if box 'coreos-stable' is up to date...
==> deis-03: Clearing any previously set forwarded ports...
==> deis-03: Fixed port collision for 22 => 2222. Now on port 2201.
==> deis-03: Clearing any previously set network interfaces...
==> deis-03: Preparing network interfaces based on configuration...
    deis-03: Adapter 1: nat
    deis-03: Adapter 2: hostonly
==> deis-03: Forwarding ports...
    deis-03: 22 => 2201 (adapter 1)
==> deis-03: Running 'pre-boot' VM customizations...
==> deis-03: Booting VM...
==> deis-03: Waiting for machine to boot. This may take a few minutes...
    deis-03: SSH address: 127.0.0.1:2201
    deis-03: SSH username: core
    deis-03: SSH auth method: private key
    deis-03: Warning: Connection timeout. Retrying...
==> deis-03: Machine booted and ready!
==> deis-03: Setting hostname...
==> deis-03: Configuring and enabling network interfaces...
==> deis-03: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> deis-03: to force provisioning. Provisioners marked to run always will still run.
mca@mca:~/deis$ ssh-add ~/.vagrant.d/insecure_private_key
Identity added: /home/mca/.vagrant.d/insecure_private_key (/home/mca/.vagrant.d/insecure_private_key)

~/deis$ export DEISCTL_TUNNEL=172.17.8.100

mca@mca:~/deis$ deisctl config platform set sshPrivateKey=~/.vagrant.d/insecure_private_key
LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBNk5GOGlhbGx2UVZwMjJXRGtUa3lydHZwOWVXVzZBOFlWcitrejRUakdZZTdnSHpJCncrbmlObHRHRUZIekQ4K3YxSTJZSjZvWGV2Y3QxWWVTMG85SFp5TjFROXFnQ2d6VUZ0ZE9LTHY2SWVkcGxxb1AKa2NtRjBhWWV0MlBrRURvM01sVEJja0ZYUElUQU16RjhkSlNJRm85RDhIZmRPVjBJQWR4NE83UHRpeFdLbjV5MgpoTU5HMHpRUHlVZWNwNHB6QzZraXZBSWh5ZkhpbEZSNjFSR0wrR1BYUTJNV1pXRlliQUdqeWlZSm5BbUNQM05PClRkMGpNWkVuRGtiVXZ4aE1tQllTZEVUazFyUmdtK1I0TE96RlVHYUhxSERMS0xYK0ZJUEtjRjk2aHJ1Y1h6Y1cKeUxiSWJFZ0U5OE9IbG5WWUN6UmRLOGpscW04dGVoVWM5YzlXaFFJQkl3S0NBUUVBNGlxV1BKWHR6WkE2OG1LZApFTHM0akpzZHlreStld2RaZU5kczV0amNuSFU1elVZRTI1SytmZkpFRDlxVVdJQ2NMWkRjODFUR1dqSHlBcUQxCkJ3N1hwZ1V3RmdlVUp3VWx6UXVyQXYrL3lTbnhpd3VhR0pmaEZNMUNhUUh6ZlhwaGdWbWwrZlpVdm5KVVR2emYKVEsyTGc2RWRiVUU5VGFyVWxCZi94UGZ1RWhNU2xJRTVrZWIvWnozL0xVbFJnOHlEcXo1dytRV1ZKNHV0bktuSwppcXdaTjBtd3B3VTdZU3lKaGxUNFlWMUYzbjRZakxzd001d0pzMm9xbTBqc3NRdS9CVDB0eUVYTkRZQkxFRjRBCnNDbGFXdVNKMmtqcTdLaHJyWVh6YWdxaG5TZWk5T0RZRlNoSnU4VVdWZWMzSWhiNVpYbHpPNnZkTlExSjlYc2YKNG0rMnl3S0JnUUQ2cUZ4eC9SdjlDTk45NmwvNHJiMTRIS2lyQzJvL29yQXBpSG1IRHNVUnM1clVLRHgwZjlpUApjWE43UzF1ZVBYdUpSSy81aHN1YmFPQ3gzT3dkMnU5Z0Q2T3EwQ3NNa0U0Q1VTaUpjWXJNQU50eDU0Y0dIN1JrCkVqRlp4Szh4QXYxbGRFTEV5eHJGcWtiRTRCS2Q4UU90NDE0cWp2VEd5QUsrT0xEM00yUWRDUUtCZ1FEdHg4cE4KQ0F4Ujd5aEhiSVdUMUFINjYrWFdOOGJYcTdsM1JPL3VrZWFjaTk4SmZrYmt4VVJaaHR4Vi9ISHV2VWhuUExkWAozVHd5Z1BCWVpGTm80cHpWRWh6V29UdG5FdHJGdWVLeHljMytMalpwdW8rbUJsUTZPUnRmZ2tyOWdCVnBoWFpHCllFemtDRDNsVmRsOEw0Y3c5QlZwS3JKQ3MxYzV0YUdqRGdkSW5RS0JnSG0vZlZ2djk2Ykp4Yzl4MXRmZlhBY2oKM09WZFVOMFVnWE5DU2FmLzNBL3BoYmVCUWU5eFMrM21wYzRyNnF2eCtpeTY5bU5CZU5aMHhPaXRJanBqQm8yKwpkQkVqU0J3TGs1cTV0SnFIbXkvaktNSkw0bjlST2x4OTNYUytuanhnaWJUdlU2RnA5dytOT0ZEL0h2eEIzVGN6CjYrakpGODVENUJOQUczREJNS0JqQW9HQkFPQXhadmdzS04rSnVFTlhzU1Q3Rjg5VGNrMmlUY1FJVDhnNXJ3V0MKUDlWdDc0eWJvZTJrRFQ1MzF3OCtlZ3o3bkFtUkJLTk03NTFVLzk1UDl0ODhFRGFjREkvWjJPd251RlFIQ1BERgpsbFlPVUkrU3BMSjYvdlVSUmJIU25ubjhhL1hHK256ZWRHSDVKR3FFSk5Rc3oreFQyYXhNMC9XL0NSa25tR2FKCmtkYS9Bb0dBTldyTEN6NzA4eTdWWWdBdFcyVWYxRFBPSVlNZHZvNmZ4SUI1aTlaZklTZ2NKL2JiQ1VrRnJob0gKK3ZxLzVDSVd4Q1BwMGY4NVI0cXh4UTVpaHhKMFlEUVQ5SnB4NFRNc3M0UFNhdlBhQkgzUlhvdzVPaGUrYllvUQpORTVPZ0VYazJ3VmZaY3pDWnBpZ0JLYktaSE5ZY2VsWHRUdC9uUDNyc0N1R2NNNGg1M3M9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

~/deis$ deisctl config platform set domain=local3.deisapp.com
local3.deisapp.com

~/deis$ deisctl install platform && deisctl start platform
● ▴ ■
■ ● ▴ Installing Deis...
▴ ■ ●

Storage subsystem...
Could not find unit template for store-daemon
