### ISSUE TITLE
Application restart policies

### ISSUE THREAD

**Issue by jchauncey** [deis/deis#4632] opened 2015-10-19 21:33 UTC
Right now if a deployed app fails to start, fleet will try and restart it forever. This seems wrong as it really pollutes the docker event stream and could make debugging difficult. Having a set restart policy seems like a good thing.

**Comment by bacongobbler** [comment] 2015-10-19 21:37
Note that this kind of idea has been shot down in kubernetes: https://github.com/kubernetes/kubernetes/issues/127

It may be better to stay the course so the migration path between the fleet and kubernetes schedulers are identical.

**Comment by jchauncey** [comment] 2015-10-19 22:04
Im not sure I agree with their assessments in that issue. In a production environment we would never allow an app to flap an infinite number of times. Most process managers (runit, god, bluepill, etc..) would be configured to retry a certain number of times and then give up. This makes it much easier to determine whether an application is down. 

We are basically polluting the docker event stream with an unnecessary number of events (4 per restart).

**Comment by jchauncey** [comment] 2015-10-19 22:06
This will also make using an annotation service almost useless as we will pollute the graphs with unnecessary details.

**Comment by krancour** [comment] 2015-10-19 22:17
I didn't read through the entire related k8s issue, but I agree on some level with @jchauncey.  Flapping indefinitely in the face of failure just doesn't seem ideal.

**Comment by jchauncey** [comment] 2015-10-21 16:48
My suggestion is we add the following to all deis unit files:

```
StartLimitInterval=60s
StartLimitBurst=3
```

According to the systemd docs this will cause system to stop trying to restart an application if it fails more than 3 times in a 60s period.

**Comment by bacongobbler** [comment] 2015-10-21 16:57
I'd be okay with this in v1, but I'm just warning that kubernetes won't have this restart policy luxury (at least not in v1), so we should be aware of that if we're writing software around a restart limit interval. Old application units won't have it either (only new apps will get this restart policy) so we may end up having to support both types because of backwards compatibility.

**Comment by jchauncey** [comment] 2015-10-21 16:59
we could enforce user created apps to have the policy when we create the container in the controller. So the next time an app is deployed it gets the restart policy. Deis components will get the new restart policy via the unit files. So that should button up v1. 

I will start trying to figure out how we will do this in v2.

**Comment by carmstrong** [comment] 2015-10-21 17:52
I think we definitely want this on the application units themselves (https://github.com/deis/deis/blob/f70bc126914d48909863ee1df81a7a79749ce104/controller/scheduler/fleet.py#L370-L380). The components I'm unsure of, and I think it's worth a discussion - we may want these to automatically restart so if the issue is resolved that prevents them from successfully starting, they will immediately recover rather than require manual intervention.

Application units, however, have many more causes of failure (such as application code issues) and shouldn't restart forever.

**Comment by jchauncey** [comment] 2015-10-21 18:01
On the application units I just found that and have added the above policy to it as well. 

Components and applications really suffer from the same problem when we are trying to determine if they are down. If the only docker state I can key off of is the die event then that can happen for any number of reasons. It also means that containers caught in a death loop of restarting will be constantly sending alerts.

For us to have a robust alerting system we need to only alert in the case of a container being stopped. This ensures that we have (unsuccessfully) tried to restart the container and now we need to alert support/operations.

I think the cases were a component finally starts because we fix some error case in the system seems like the wrong approach. Instead, if components died after trying to restart, when the error was fixed the user could just restart the components themselves.

**Comment by krancour** [comment] 2015-11-06 15:16
@jchauncey I mostly agree with you, but what would be the possibility of alerting on flapping instead?  Then ops gets the alert AND retries can continue.

**Comment by jchauncey** [comment] 2015-11-06 16:56
The problem is that components get into spiral of `create -> start -> die -> destroy`. So if we want to alert on a component dying we can only do that on the `die` state which isn't ideal since the `die` state is used all over the container lifecycle. 

The `die` event could be triggered because of restarts or application upgrades. 

Instead, we should trigger alerts because the container is in the `stopped` state. This means it has exited and all restarts have been unsuccessful.

**Comment by krancour** [comment] 2015-11-06 17:10
Could we count how frequently that cycle happens?  For instance, consider something to be flapping if restarts are happening frequently at short intervals?

**Comment by jchauncey** [comment] 2015-11-06 17:32
Counting is far more complex because I will have to keep the state of every container in which I see at least 1 die event. While some stream processors are capable of doing this, other tools we are evaluating make this more difficult. 

If the container was in an error state and dies then it is much easier to say we no longer are receiving stats for that container and we alert on that case. It also is much easier to capture the cause of the container dying when we are not always destroying the container when it fails. Eventually, it will stop removing the container and its last state will be around for me to determine what the caused the exit.

**Comment by jchauncey** [comment] 2015-11-06 17:48
By the way I have PR open to address this - #4647

**Comment by iancoffey** [comment] 2015-11-06 17:50
A lot of this issue is that the current units RestartSec is too short, and one solution is to just increase it. This would improve both monitoring systems and humans ability to determine what is actually going on. Having all units set for hyper-speed restart doesnt seem super necessary.

**Comment by bacongobbler** [comment] 2016-01-21 19:35
We won't be able to get to this for the LTS release and since in v2 kubernetes won't allow you to modify the restart policy, I'm going to close this. Thank you very much for posting this though :)

**Closed by bacongobbler** 2016-01-21 19:35 UTC
Labels: controller, etcd/fleet
