### ISSUE TITLE
possible bug in client-go: error when scaling app w/ mesos as the scheduler

### ISSUE THREAD

**Issue by krancour** [deis/deis#4158] opened 2015-07-31 00:27 UTC
About 50% of the time the following happens when I scale using the mesos/marathon scheudler:

```
[kent@mbp example-ruby-sinatra]$ deis scale web=2
Scaling processes... but first, coffee!
done in 10s
Error: Get http://deis.local3.deisapp.com/v1/apps/walkup-espresso/containers/: EOF
```

**Comment by mboersma** [comment] 2015-08-04 15:44
@krancour are you using the new go `deis` CLI? I've seen the same, but it doesn't happen for me with the traditional python CLI.

**Comment by krancour** [comment] 2015-08-04 15:45
Yep.  Good call.

**Comment by Joshua-Anderson** [comment] 2015-08-04 15:47
I'll look into this, as I've seen this as well. I love `EOF` errors!

**Comment by krancour** [comment] 2015-08-13 13:44
Reporting that this happens with k8s as the scheduler as well.

**Comment by Joshua-Anderson** [comment] 2015-08-14 20:19
Related #4269

**Comment by mboersma** [comment] 2015-08-25 22:40
I can't reproduce this currently against master with the go CLI. Maybe nginx 1.9.4 (#4306) or maybe go 1.5?

**Comment by krancour** [comment] 2015-08-26 02:07
I'll re-attempt just to corroborate.

**Comment by krancour** [comment] 2015-08-26 19:41
I can no longer re-create this.  Closing.

**Comment by krancour** [comment] 2015-08-26 19:48
No sooner did I close this than it reared it's ugly head again.  @mboersma has observed this in Jenkins today and just now it _finally_ bit me locally after _many_ recent failures to duplicate.

```
[kent@mbp example-go]$ deis scale web=100
Scaling processes... but first, coffee!
done in 81s
Error: Get http://deis.krancour.deis.ninja/v1/apps/lively-kerchief/containers/?page_size=100: EOF
```

**Comment by bacongobbler** [comment] 2015-08-28 15:37
This looks like a manifestation of an older bug we've had for a very long time. More information on this bug here: https://github.com/deis/deis/pull/4261#issuecomment-135552944

**Comment by mboersma** [comment] 2015-09-04 15:13
We haven't seen an EOF since #4261 was merged, so I assume `DisableKeepAlives=true` fixed this. (Please re-open this issue if I'm wrong and you've seen any EOF errors with the new go CLI.)

**Closed by mboersma** 2015-09-04 15:13 UTC
Labels: client-go, k8s, mesos
