### ISSUE TITLE
stop-update-engine.service results in degraded status

### ISSUE THREAD

**Issue by woopstar** [deis/deis#4093] opened 2015-07-23 18:29 UTC
When a new CoreOS server is provisioned with Deis, Deis is creating and starting the stop-update-engine.service from it's user-data.

When this service is started, the update-engine.service enters into a failed state, resulting the systemctl status to be degraded with 1 failed:

```
$ systemctl status
● coreos-1cbyh28tidigd0nf
    State: degraded
     Jobs: 0 queued
   Failed: 1 units
    Since: Thu 2015-07-23 19:51:21 CEST; 31min ago
```

Finding the failed unit:
```
$ systemctl | grep fail
● update-engine.service                                                               masked failed failed    update-engine.service
```

The log is then shown here:
```
$ journalctl | grep update-engine.service
Jul 23 19:51:37 coreos-1cbyh28tidigd0nf sudo[670]: 2015/07/23 19:51:37 Writing unit "stop-update-engine.service" to filesystem
Jul 23 19:51:37 coreos-1cbyh28tidigd0nf sudo[670]: 2015/07/23 19:51:37 Writing file to "/etc/systemd/system/stop-update-engine.service"
Jul 23 19:51:37 coreos-1cbyh28tidigd0nf sudo[670]: 2015/07/23 19:51:37 Wrote file to "/etc/systemd/system/stop-update-engine.service"
Jul 23 19:51:37 coreos-1cbyh28tidigd0nf sudo[670]: 2015/07/23 19:51:37 Wrote unit "stop-update-engine.service"
Jul 23 19:51:37 coreos-1cbyh28tidigd0nf sudo[670]: 2015/07/23 19:51:37 Calling unit command "start" on "stop-update-engine.service"'
Jul 23 19:51:37 coreos-1cbyh28tidigd0nf systemd[1]: update-engine.service: Main process exited, code=exited, status=1/FAILURE
Jul 23 19:51:37 coreos-1cbyh28tidigd0nf systemd[1]: update-engine.service: Unit entered failed state.
Jul 23 19:51:37 coreos-1cbyh28tidigd0nf systemd[1]: update-engine.service: Failed with result 'exit-code'.
Jul 23 19:51:37 coreos-1cbyh28tidigd0nf systemctl[718]: Created symlink from /etc/systemd/system/update-engine.service to /dev/null.
Jul 23 19:51:37 coreos-1cbyh28tidigd0nf sudo[670]: 2015/07/23 19:51:37 Result of "start" on "stop-update-engine.service": done
```
Unsure if it's a missing sudo on the stop command that causes this.

I don't believe this is a major problem at all. I find it more as a minor fix just to make let coreos status not be degraded. This looks a bit bad in our monitoring systems that servers are degraded due to this.

**Comment by mboersma** [comment] 2015-07-23 21:47
@woopstar you're right--I tried this with just `make dev-cluster` and see the same "Failed: 1 units" message. I think the issue is that `update-engine.service` is enabled in the ebuild image for CoreOS and is already started by the time modifications in user-data are recognized, which is why we had to write another one-short service to kill and mask it afterward. Even if you simplify things to this as Brandon suggests in [this discussion thread](https://groups.google.com/forum/#!msg/coreos-user/FXiprF4cKcg/Td0ft8weoQgJ), I still get the same results of "Failed: 1 units" pointing at update-engine:
```
  - name: update-engine.service
    command: stop
    mask: true
```

It isn't a major problem, but I can see how it plays havoc with monitoring of systemd services. If anyone has a creative solution for this, bring it on.

**Comment by woopstar** [comment] 2015-07-24 09:33
I think we have the same problem when scaling an application. I tried to scale a demo application from 1 to 3 webs, and then back to 1 web again.

Now logging on, on one of the nodes, this output is suddenly seen:

```
$ systemctl | grep fail
● deluxe-yardbird_v2.web.1.service                                                    not-found failed failed    deluxe-yardbird_v2.web.1.service
● deluxe-yardbird_v3.web.3.service                                                    not-found failed failed    deluxe-yardbird_v3.web.3.service
● update-engine.service                                                               masked    failed failed    update-engine.service
```

Having a bit closer look:

```
$ systemctl status deluxe-yardbird_v3.web.3.service
● deluxe-yardbird_v3.web.3.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: exit-code) since Fri 2015-07-24 10:45:42 CEST; 45min ago
 Main PID: 66844 (code=exited, status=137)

Jul 24 10:43:17 coreos-68wkg7dspbe6enkq systemd[1]: Started deluxe-yardbird_v3.web.3.
Jul 24 10:43:18 coreos-68wkg7dspbe6enkq sh[66844]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
Jul 24 10:43:18 coreos-68wkg7dspbe6enkq sh[66844]: Recommending WEB_CONCURRENCY=1
Jul 24 10:43:18 coreos-68wkg7dspbe6enkq sh[66844]: Node app is running at localhost:5000
Jul 24 10:45:32 coreos-68wkg7dspbe6enkq systemd[1]: Stopping deluxe-yardbird_v3.web.3...
Jul 24 10:45:42 coreos-68wkg7dspbe6enkq systemd[1]: deluxe-yardbird_v3.web.3.service: Main process exited, code=exited, status=137/n/a
Jul 24 10:45:42 coreos-68wkg7dspbe6enkq docker[67116]: deluxe-yardbird_v3.web.3
Jul 24 10:45:42 coreos-68wkg7dspbe6enkq systemd[1]: Stopped deluxe-yardbird_v3.web.3.service.
Jul 24 10:45:42 coreos-68wkg7dspbe6enkq systemd[1]: deluxe-yardbird_v3.web.3.service: Unit entered failed state.
Jul 24 10:45:42 coreos-68wkg7dspbe6enkq systemd[1]: deluxe-yardbird_v3.web.3.service: Failed with result 'exit-code'.
```

For me, it looks like either:

1. When scaling down, the services is not cleaned up correctly and removed, or
2. We have the same issue as above with stopping a service results in failed?

**Comment by bacongobbler** [comment] 2016-01-21 19:49
This is not something we'll be able to get to fixing for the LTS release, and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.

**Closed by bacongobbler** 2016-01-21 19:49 UTC
Labels: contrib and provisioning, help wanted
