### ISSUE TITLE
Router not respecting domains when routing traffic (app name/subdomain only?)

### ISSUE THREAD

**Issue by soulware** [deis/deis#3804] opened 2015-06-06 16:13 UTC
Setup: Deis deployed to a private subnet in AWS with an internal load balancer and a private hosted zone `services-staging.internal`.
By configuring a second public ELB `external-service.my-services.com` to point to the same Deis instances it is possible to access applications via the Deis router even if custom domains are not configured.

The intent here was to expose a limited set of apps via the public ELB and restrict all other apps to the private subnet.

See below for example calls via the IP address of the public external ELB by modifying the Host Header.

It appears the router is not honoring either the main Deis domain or the apps custom domains when routing traffic to the "internal-service" app.

Is this expected behavior?

````Shell
$ deisctl config platform get domain
services-staging.internal

$ deis domains -a internal-service
=== internal-service Domains
No domains

$ dig +short external-service.my-services.com
52.5.110.243
107.23.169.20
````

````Shell
$ curl 52.5.110.243 -H "Host: internal-service.services-staging.internal"
{"msg":"hello from service"}

$ curl 52.5.110.243 -H "Host: internal-service.my-services.com"
{"msg":"hello from service"}

$ curl 52.5.110.243 -H "Host: internal-service.other"
{"msg":"hello from service"}
````

I would have expected `internal-service` app to *only* be accessible via the `internal-service.services-staging.internal` domain and not be accessible via any other domain.

**Comment by gabrtv** [comment] 2015-06-11 20:59
@soulware thanks for the report.  I _believe_ this is intended behavior -- as in the router is responding the virtual host names it's configured with.

> The intent here was to expose a limited set of apps via the public ELB and restrict all other apps to the private subnet.

This use-case is definitely something I'd like to support, though we'll need to discuss how.  Ideas?

**Comment by bacongobbler** [comment] 2015-06-11 21:03
> I believe this is intended behavior -- as in the router is responding the virtual host names it's configured with.

Yes. For clarification, some users wanted to allow multiple domains pointing at the same router, which is why the router doesn't care about the virtual host names. :)

**Comment by soulware** [comment] 2015-06-11 21:10
Thanks.
I was wondering if there could be a way to configure multiple routers. i.e. one internal and one external.
Right now we are pointing 2 ELBs to the same router which doesn't feel right - it would feel cleaner if we were pointing each ELB at a different router.

**Comment by carmstrong** [comment] 2015-06-11 21:17
> Right now we are pointing 2 ELBs to the same router which doesn't feel right - it would feel cleaner if we were pointing each ELB at a different router.

Some people customize the router component so they have two routers - one for internal services, one for external services. You'd have to perform some custom logic to filter out the apps/services you don't care about and maintain these separately, though, but this seems to work well.

Then you'd have an internal ELB for the internal services (typically including controller also), and a public ELB.

**Comment by soulware** [comment] 2015-06-11 21:30
Alternatively - I was wondering if there was some way of of getting non-web procfile entries into the registry so they could be looked up and accessed directly, skipping the router. Basically use the etcd entries for service discovery between internal apps/services.

-- Simon

**Comment by sstarcher** [comment] 2015-09-01 23:50
I'm interested in @carmstrong thought of 2 separate routers in Deis for public (limited subnet) and private (all applications).  Would this be something that we could incorporate into Deis itself or should we just do this privately for our group?

**Comment by bacongobbler** [comment] 2015-09-02 00:04
@sstarcher I'd keep following https://github.com/deis/deis/issues/3072 since that will solve this problem with internal DNS routing.

Since the original question was answered and this is intentional behaviour, I'm going to close this but please feel free to open another issue if #3072 is not what you were looking for. Thanks! :)

**Closed by bacongobbler** 2015-09-02 00:04 UTC
Labels: router
