### ISSUE TITLE
Server version comes up blank in error after setting "deisctl config router set enforceHTTPS=true" 

### ISSUE THREAD

**Issue by dmcnaught** [deis/deis#4740] opened 2015-11-10 17:41 UTC
There are a few tickets that might relate to this, but for simplicity I'm going to enter this as an issue in it's own right, and it can be referenced/closed as appropriate.

I have a stateless platform.

I installed SSL on the Deis Routers: 
`deisctl config router set sslKey=~/openssl/server.key sslCert=~/openssl/server.crt`

Login by HTTPS and HTTP was now fine.

I set to enforce HTTPS: 
`deisctl config router set enforceHTTPS=true`

HTTPS login is still fine.

Now I get this error with HTTP login:

```$ deis login http://...
username: xxxxxxxxxx
password:
!    WARNING: Client and server API versions do not match. Please consider upgrading.
!    Client version: 1.7
!    Server version:
Error: invalid character '<' looking for beginning of value```

This looks similar to https://github.com/deis/deis/issues/4667

**Comment by bacongobbler** [comment] 2015-11-10 18:05
@dmcnaught this does look like an exact duplicate of #4667. Let's keep it all in that ticket for now, but we are starting to get an idea what's causing `enforceHTTPS=true` to fail in another related issue. It's possible that this started after we switched the ELB from a HTTP listener to a TCP listener and enabled `proxyProtocolEnabled=true` on AWS.

**Closed by bacongobbler** 2015-11-10 18:05 UTC
