### ISSUE TITLE
deis CLI: `deis releases prune` command

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3698] opened 2015-05-15 18:02 UTC
@haf has proposed a new command in #3693 which would purge all old releases and their images, reclaiming disk space.

**Comment by croemmich** [comment] 2015-05-18 22:44
I'd be a big fan of this. I'm running on Linode and have a somewhat limited supply of disk space.

The hardest part is removing the images from the registry, but my https://github.com/myriadmobile/docker-s3-cleaner project seems to be working properly for such. The only other steps required would be to delete the release from the database and untag the image in the registry.

**Possible Syntax:**
Destroy single release: `deis releases:destroy v5`
Destroy releases that are older than 10 days: `deis releases:prune age=10d`
Destroy all releases except the latest 3: `deis releases:prune keep=3`

**Questions:**
What is the expected behavior if the current version is pruned?
What is the expected behavior of rollback if the previous release has been deleted?

**Comment by bacongobbler** [comment] 2015-05-18 23:02
While I agree with the motivation behind this, I'm not too sure if we should approach it through the API. The release ledger is an append-only ledger. While you can remove the release from the database (which we should disable), the [views don't allow you to remove a specific release](https://github.com/deis/deis/blob/master/controller/api/tests/test_release.py#L110-L111), so we'd be breaking [one of our core tenets](http://12factor.net/build-release-run):

> Releases are an append-only ledger and a release cannot be mutated once it is created. Any change must create a new release.

That being said, I'd be happy if we introduced a deis-specific cleanup component to remove images from the hosts and removing images from the registry would be preferable, IMO. Since these are artifacts of the release being distributed across the scheduler, these can be cleaned up.

**Comment by carmstrong** [comment] 2015-05-18 23:08
> That being said, I'd be happy if we introduced a deis-specific cleanup component to remove images from the hosts and removing images from the registry. Since these are artifacts of the release being distributed across the scheduler, these can be cleaned up.

Yeah, I wasn't thinking we'd remove anything from the ledger - rather clean up the images themselves. This is also related to what we're discussing in #3675

**Comment by croemmich** [comment] 2015-05-18 23:29
Yeah, #3675 should take care of cleaning up the hosts, which just leaves the images in the registry.

What's the thought when the image backing the release is removed? At that point the release is nearly useless. I don't see an issue with soft-deleting the release or marking the build as deleted, as a row in the database isn't really an issue, however I really need a way to delete the backing images.

I completely understand the desire for an append-only ledger but you also have to consider how people may be using Deis. We have a development environment that has seen 15+ releases a day. I don't care a darn bit about any one of them. At that point, having an arbitrary "rule" preventing me from deleting releases because it is "bad practice" leaves a bit of a bad taste in my mouth.

**Comment by carmstrong** [comment] 2015-05-18 23:31
> I completely understand the desire for an append-only ledger but you also have to consider how people may be using Deis. We have a development environment that has seen 15+ releases a day. I don't care a darn bit about any one of them. At that point, having an arbitrary "rule" preventing me from deleting releases because it is "bad practice" leaves a bit of a bad taste in my mouth.

A release is just that - a database entry. Wouldn't you want to look back and see that chris pushed <sha> a week ago, even if you don't have the image anymore?

I think we're all on the same page that images have a short usefulness timeline, but seeing what led up to the current release/version can be important information.

**Comment by croemmich** [comment] 2015-05-18 23:33
Yeah, no qualms with that here! We'll just have to decide what to do I a user tries to rollback to a release with a deleted image.

**Comment by carmstrong** [comment] 2015-05-18 23:34
> We'll just have to decide what to do I a user tries to rollback to a release with a deleted image.

Same thing that happens now - we build a new release with a new image :)

**Comment by croemmich** [comment] 2015-05-18 23:36
Fair enough, does the builder just use the git hash to do so? I'm not that familiar with that component yet.

**Comment by carmstrong** [comment] 2015-05-18 23:53
> I'm not that familiar with that component yet.

Admittedly I'd have to dig into the internals of that too. Here's the model logic: https://github.com/deis/deis/blob/4287fc04e384f3b38928c14969b87c1a1d45d4b3/controller/api/models.py#L769-L785

**Comment by krancour** [comment] 2015-05-21 18:49
Could we also make sure we clean up _all_ of an app's images when an app is destroyed?

**Comment by bacongobbler** [comment] 2015-05-21 19:51
@krancour you may be looking for #685 which was closed due to limitations with the registry.

**Comment by wgrrrr** [comment] 2015-07-20 17:39
I'm a big fan of this feature. I am operating a cluster with many apps each having many releases per day. I am quickly using a large amount of disk space. I don't care about any of the previous releases (except for the last couple). I like the syntax ideas proposed by @croemmich above, but would also love a global configuration which said something like "keep the last `x` releases as images" and then have the ability to rollback to any previous release by rebuilding the image using the Git SHA hash.

**Comment by bacongobbler** [comment] 2016-06-09 22:51
closing as irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/). kubernetes handles this for us.

**Closed by bacongobbler** 2016-06-09 22:51 UTC
Labels: client, v2

**Comment by nathansamson** [comment] 2016-06-09 22:55
I assume old releases are still available through the registry in deis V2?
So assuming you have off cluster storage; you will fill up this storage?
and not actually purge old releases completely; unless i am
misunderstanding something

Nathan

**Comment by bacongobbler** [comment] 2016-06-09 23:03
correct, however that cannot be resolved until docker actually comes up with a way to delete image artifacts from the registry. Everything else is purged from the system though.
