### ISSUE TITLE
Out of disk space on machine running deis-builder

### ISSUE THREAD

**Issue by cray0000** [deis/deis#3144] opened 2015-02-25 16:30 UTC
1 machine from the cluster (the one where `deis-builder` is running) runs out of space very quickly. 

We've figured out that it's `deis-builder-data` that dramatically eats space. And it grows fast with each deploy because `deis-builder` doesn't seem to fully clean the intermediate containers. 

The solution right now is to stop `deis-builder`, remove `deis-builder-data` container **with** its volume (`-v` option) and run `deis-builder` again:
```bash
# Log into the machine that is running deis-builder and:
deisctl stop builder
docker rm -v deis-builder-data
deisctl start builder
```

ref #1678

**Comment by bacongobbler** [comment] 2015-02-25 16:44
Which kind of app deployments are you running in the builder? I know that application images will get cleaned up, but if you're using a Dockerfile approach and your app relies on another image (i.e. `FROM ubuntu:14.04`), that parent image won't get cleaned up.

Instead of cleaning up just the app image after a run, maybe we can clean up all images except for the few containers that we require in the build process like slugbuilder, slugrunner and cedarish. This has the downside of making all `git push` deployments slower because you'll always have to pull the parent image, so there's a tradeoff there.

**Comment by wenzowski** [comment] 2015-02-25 18:44
Any outside chance could be caused by [heroku-buildpack-nodejs](https://github.com/heroku/heroku-buildpack-nodejs/tree/v64/) caches? @cray0000

**Comment by cray0000** [comment] 2015-02-26 10:00
@bacongobbler yes, we use Dockerfile and there is a `FROM` base image.

The parent image can be pretty big, the one we use right now is about 300M for example, so downloading it each time is not a perfect solution but definetly one we should consider. 

I wonder if it's possible to auto/manually push parent image into `deis-registry` to be used on some stage of the build process, and tell Docker to use that registry to find image first, and if it wasn't found there then fall back to the public registry. This will make downloading much faster thanks to the local network bandwith and there won't be any downsides of cleaning the whole deis-builder each time.

**Comment by bacongobbler** [comment] 2015-03-05 21:16
From #3209:

> Running and pushing many different updates to a Deis environment can add up to a lot of Docker images. I have no reason for keep ALL Docker images for an app along the way.

> It would be nice if we could add a config var like DIMAGE_CNT=3 that would force the builder to always remove any Docker images for an application that are not the most recent 3 images.

> The goal is to prevent 100 different images from accumulating that haven't been used in weeks and are just consuming disk space.

**Comment by mastephens** [comment] 2015-03-05 21:23
In my case I don't seem to have issues with intermediate images not being cleaned up,  it its purely from an archival issue for the final image for each build.  I am using a fork of a Heroku Buildpack for NodeJs for our builds.   We can run upwards of 20+ builds a day,  with these old images hanging around we are having to manually purge the older ones pretty frequently to keep from running out of disk.

**Comment by bacongobbler** [comment] 2015-03-05 21:26
ah, so you're having to purge old images from the hosts? We have documentation around that, though it'd be nice for the scheduler to remove the image when the process is killed.

**Comment by mastephens** [comment] 2015-03-05 21:29
You hit it on the head.   Yeah I have no problem purging the images manually,  your docs were great for helping out with that. It would just be nice if we could set a ENV_VAR for the app and the builder would do its thing and push the most recent image to the registry,  then purge any older than X.

**Comment by bacongobbler** [comment] 2015-03-05 21:30
Okay. Sorry for the premature close! Let's track that back in #3209

**Comment by carmstrong** [comment] 2015-05-12 20:36
@cray0000 @mastephens Are we okay closing this, given that we have documentation around cleaning up old images and are tracking the automatic removal in #3209?

**Comment by mastephens** [comment] 2015-05-12 20:41
@carmstrong yep,  as long as #3209 stays open.  This is a completely different issue in my opinion.

**Comment by carmstrong** [comment] 2015-05-12 20:43
> This is a completely different issue in my opinion.

:+1:

**Closed by carmstrong** 2015-05-12 20:43 UTC
Labels: builder
