### ISSUE TITLE
Logout REST api call for the controller feature request

### ISSUE THREAD

**Issue by daemonza** [deis/deis#3111] opened 2015-02-19 14:54 UTC
Hi

Exposing deis auth:logout through the controller API.

**Comment by mboersma** [comment] 2015-02-20 23:13
Deis' controller uses token-based authentication now, so there is no server-side session or state that is maintained. When we made that change, we [got rid of the logout REST endpoint](https://github.com/deis/deis/pull/2136#discussion_r18847907). You can still do `deis logout`, but it just destroys the local copy of the token and doesn't make any network calls.

@daemonza is there a need for the logout endpoint if the server isn't storing session state?

**Comment by bacongobbler** [comment] 2015-02-23 03:36
ping @daemonza

**Comment by daemonza** [comment] 2015-02-23 08:25
Yes, so we don't really use the cmd line deis utility that much. We are busy with a web interface through which we are deploying applications from docker repo's. The problem I have is, if I want to "expire" a user's token. Without the API call, how would I be able to do it.

**Comment by bacongobbler** [comment] 2015-02-23 15:58
In Django REST Framework's implementation, there is no way to expire a token by default. It is persistent, meaning that every time you log in, you are given the same auth token that was generated for you on the first registration/login. See http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication

If we are to add token expiration features, we should follow https://developers.facebook.com/blog/post/2011/05/13/how-to--handle-expired-access-tokens/ as there are a few cases where we need to expire the token (such as when we change the user's password).

**Comment by bacongobbler** [comment] 2015-03-03 17:50
ping @daemonza. Are you looking for token expiration, or was this explanation good for you?

**Comment by bacongobbler** [comment] 2015-03-03 19:06
closing as a duplicate of #2175.

**Closed by bacongobbler** 2015-03-03 19:06 UTC

**Comment by daemonza** [comment] 2015-03-04 11:52
yup thanks @bacongobbler
