### ISSUE TITLE
Setting a configuration value prevents further application pushes

### ISSUE THREAD

**Issue by ngerakines** [deis/deis#3338] opened 2015-03-19 19:27 UTC
When a specific application configuration has been set no further pushes to deis for the application succeed.

Given the variable is set with:

    $ deis config:set NETSUITE_AUTH="NLAuth nlauth_account=000001, nlauth_email=xxx, nlauth_signature=yyy, nlauth_role=zzz"

Pushing to the deis application's git repository fails:

    $ git push deis release-2.0.0:master
    Counting objects: 1, done.
    Writing objects: 100% (1/1), 187 bytes | 0 bytes/s, done.
    Total 1 (delta 0), reused 0 (delta 0)
    Unable to find image 'nlauth_account=000001,:latest' locally
    time="2015-03-19T19:20:04Z" level="fatal" msg="Invalid repository name (nlauth_account=000001,), only [a-z0-9-_.] are allowed"
    To ssh://git@deis.our-magical-cluster:2222/helium-staging.git
       4041347..76ff68f  release-2.0.0 -> master

**Comment by ngerakines** [comment] 2015-03-19 19:28
It should be noted that unsetting that specific application configuration key fixes it.

    $ deis config:unset NETSUITE_AUTH

**Comment by carmstrong** [comment] 2015-03-19 20:50
I suspect this has to do with config value escaping, again: #2980 

:(

**Comment by bacongobbler** [comment] 2015-07-16 18:59
closing as a duplicate of #2980 -- let's keep the conversation rolling in one issue so we're all on the same page WRT bugfixes :)

**Closed by bacongobbler** 2015-07-16 18:59 UTC
Labels: bug
