### ISSUE TITLE
Instructions for using graceful-etcd-shutdown

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#4951] opened 2016-03-02 13:54 UTC
According to the docs on [automatic host removal](http://docs.deis.io/en/latest/managing_deis/add_remove_host/#automatic-host-removal), I can use `graceful-etcd-shutdown`. Considering it's part of `contrib/coreos/user-data.example`, I'd have expected that it'd be available when I provisioned my AWS cluster.

```
$ systemctl enable graceful-etcd-shutdown
Failed to execute operation: Interactive authentication required.

$ sudo systemctl enable graceful-etcd-shutdown
Failed to execute operation: No such file or directory
```

**Comment by carmstrong** [comment] 2016-03-02 20:49
The documentation for `latest` corresponds to the master branch, not for the latest Deis release. The unit files are in master, but until Deis v1.13 LTS is released, they won't be in a specific release.

**Comment by bacongobbler** [comment] 2016-03-02 21:06
closing as a duplicate of #4918.

**Closed by bacongobbler** 2016-03-02 21:06 UTC

**Comment by rstacruz** [comment] 2016-03-03 06:15
thats embarassing, i actually asked the same question before haha. sorry about that.
