### ISSUE TITLE
Go build failed

### ISSUE THREAD

**Issue by sockeye44** [deis/deis#3869] opened 2015-06-14 22:44 UTC
Hello. I am trying to deploy Go app.

	MacBook-Pro-Alexander:app sockeye$ ls
	Godeps		Procfile	index.htm	web.go		public		app
	MacBook-Pro-Alexander:app sockeye$ git push deis master
	Counting objects: 229, done.
	Delta compression using up to 4 threads.
	Compressing objects: 100% (213/213), done.
	Writing objects: 100% (229/229), 722.14 KiB | 210.00 KiB/s, done.
	Total 229 (delta 14), reused 0 (delta 0)
	-----> Go app detected

	gzip: stdin: not in gzip format
	tar: Child returned status 1
	tar: Error is not recoverable: exiting now
	To ssh://git@deis.sockeye.cc:2222/app.git
	 ! [remote rejected] master -> master (pre-receive hook declined)
	error: failed to push some refs to 'ssh://git@deis.sockeye.cc:2222/app.git'
Procfile:

	web: app

What am I doing wrong?

**Comment by bacongobbler** [comment] 2015-06-15 01:35
Seems like a buildpack issue, though I'm not sure why the app failed to deploy. Are you able to deploy it fine on Heroku?

**Comment by sockeye44** [comment] 2015-06-15 01:57
Yes

    Counting objects: 231, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (215/215), done.
    Writing objects: 100% (231/231), 723.00 KiB | 0 bytes/s, done.
    Total 231 (delta 14), reused 0 (delta 0)
    remote: Compressing source files... done.
    remote: Building source:
    remote: 
    remote: -----> Fetching custom git buildpack... done
    remote: -----> Go app detected
    remote: -----> Installing go1.4.2... done
    remote: -----> Running: godep go install -tags heroku ./...
    remote: -----> Discovering process types
    remote:        Procfile declares types -> web
    remote: 
    remote: -----> Compressing... done, 3.2MB
    remote: -----> Launching... done, v3

**Comment by bacongobbler** [comment] 2015-06-15 16:08
If you can provide some code that shows this issue, that would be appreciated. We're testing Go with [example-go](https://github.com/deis/example-go), which works fine for us but I'm interested to see how this is breaking for you.

**Comment by mboersma** [comment] 2015-06-17 19:27
@sockeye44 are you using a [current version](https://github.com/deis/deis/releases) of Deis? If you could share the app code, or a reproducible example, we would like to fix this if Deis is doing something wrong.

**Comment by sockeye44** [comment] 2015-06-18 04:42
Yes, I'm using current version. And this (https://github.com/gin-gonic/gin/tree/master/examples/realtime-advanced) can be a good example of go-gin application.

**Comment by mboersma** [comment] 2015-11-03 02:55
I'm closing this since it hasn't seen any activity in several months. Please open a new issue if this app continues to be problematic on the current version of Deis.

**Closed by mboersma** 2015-11-03 02:55 UTC
Labels: builder
