### ISSUE TITLE
Router ERROR Missing template 

### ISSUE THREAD

**Issue by sstarcher** [deis/deis#4323] opened 2015-08-24 14:42 UTC
Our Deis cluster was provisioned with Deis 1.9.0 on 8/20 on AWS using the stateless-platform.
This morning 8/24 prior to anyone coming into work we started receiving the following on 2 of out 3 of our Deis routers.  The fix was to shutdown the router and restart as a new container.  I also jumped into the containers that were having the error to find that the files were actually present.  This error caused any traffic that was routed to these routers to fail and the router to still be considered healthy as it was responding to pings from the AWS ELB.

```
2015-08-24T13:37:41Z 9c2a97b4651e confd[46]: ERROR Missing template: /app/templates/deis.cert
2015-08-24T13:37:41Z 9c2a97b4651e confd[46]: ERROR Missing template: /app/templates/deis.conf
2015-08-24T13:37:41Z 9c2a97b4651e confd[46]: ERROR Missing template: /app/templates/deis.key
2015-08-24T13:37:41Z 9c2a97b4651e confd[46]: ERROR Missing template: /app/templates/dhparam.pem
2015-08-24T13:37:41Z 9c2a97b4651e confd[46]: ERROR Missing template: /app/templates/generate-certs
```

**Comment by mboersma** [comment] 2015-08-26 20:28
Was there any context in the router logs before this happened that might give us a clue?

**Comment by sstarcher** [comment] 2015-08-26 20:36
Nothing abnormal in the router logs just normal requests coming into the system.  I rebuilt the cluster so I have lost the rest of the logs.

**Comment by bacongobbler** [comment] 2015-08-26 20:42
note that the error in confd indicates that the [template files are gone](https://github.com/kelseyhightower/confd/blob/d74d87a7efbb8775c3d553597463b00a2450486f/src/github.com/kelseyhightower/confd/resource/template/resource.go#L110-L112), so I'm not sure if somehow they were removed or if it's an upstream issue. :/

Have you been able to reproduce this issue after rebooting the router?

**Comment by sstarcher** [comment] 2015-08-26 21:01
Prior to termination the cluster I jumped into the docker container for the router and the files were indeed in the container at the correct location.  Since I created this ticket the issue has not happened again.

**Comment by bacongobbler** [comment] 2015-08-26 21:47
okay, sounds like we can close this for now then at least until it pops up again, which then we can take a closer look. Thanks for the report :)

**Comment by sstarcher** [comment] 2015-09-16 21:38
So I have had this happen a second time now.  This router had been running for 3 weeks on Deis 1.9.0.
Prior to the first occurrence of ERROR Missing template nothing looks out of the ordinary in the log.

```
Sep 16 21:26:24 ip-10-0-10-63.ec2.internal sh[1696]: 2015-09-16T21:26:24Z d2725b878cda confd[45]: ERROR Missing template: /app/templates/deis.cert
Sep 16 21:26:24 ip-10-0-10-63.ec2.internal sh[1696]: 2015-09-16T21:26:24Z d2725b878cda confd[45]: ERROR Missing template: /app/templates/deis.conf
Sep 16 21:26:24 ip-10-0-10-63.ec2.internal sh[1696]: 2015-09-16T21:26:24Z d2725b878cda confd[45]: ERROR Missing template: /app/templates/deis.key
Sep 16 21:26:24 ip-10-0-10-63.ec2.internal sh[1696]: 2015-09-16T21:26:24Z d2725b878cda confd[45]: ERROR Missing template: /app/templates/dhparam.pem
Sep 16 21:26:24 ip-10-0-10-63.ec2.internal sh[1696]: 2015-09-16T21:26:24Z d2725b878cda confd[45]: ERROR Missing template: /app/templates/generate-certs
Sep 16 21:26:24 ip-10-0-10-63.ec2.internal sh[1696]: 2015-09-16T21:26:24Z d2725b878cda confd[45]: ERROR Missing template: /app/templates/nginx.conf```

**Comment by jpizarrom** [comment] 2015-09-28 14:46
It's happen on deis 1.7.3 too

```
Sep 28 14:39:04.ec2.internal sh[32571]: 2015-09-28T14:39:04Z 91706ce90336 confd[46]: ERROR Missing template: /app/templates/deis.cert
Sep 28 14:39:04 .ec2.internal sh[32571]: 2015-09-28T14:39:04Z 91706ce90336 confd[46]: ERROR Missing template: /app/templates/deis.conf
Sep 28 14:39:04 .ec2.internal sh[32571]: 2015-09-28T14:39:04Z 91706ce90336 confd[46]: ERROR Missing template: /app/templates/deis.key
Sep 28 14:39:04 .ec2.internal sh[32571]: 2015-09-28T14:39:04Z 91706ce90336 confd[46]: ERROR Missing template: /app/templates/generate-certs
Sep 28 14:39:04 ip-10-21-1-191.ec2.internal sh[32571]: 2015-09-28T14:39:04Z 91706ce90336 confd[46]: ERROR Missing template: /app/templates/nginx.conf
Sep 28 14:39:09 ip-10-21-1-191.ec2.internal sh[32571]: 2015-09-28T14:39:09Z 91706ce90336 confd[46]: ERROR Missing template: /app/templates/deis.cert
Sep 28 14:39:09 ip-10-21-1-191.ec2.internal sh[32571]: 2015-09-28T14:39:09Z 91706ce90336 confd[46]: ERROR Missing template: /app/templates/deis.conf
Sep 28 14:39:09 ip-10-21-1-191.ec2.internal sh[32571]: 2015-09-28T14:39:09Z 91706ce90336 confd[46]: ERROR Missing template: /app/templates/deis.key
Sep 28 14:39:09 ip-10-21-1-191.ec2.internal sh[32571]: 2015-09-28T14:39:09Z 91706ce90336 confd[46]: ERROR Missing template: /app/templates/generate-certs
Sep 28 14:39:09 ip-10-21-1-191.ec2.internal sh[32571]: 2015-09-28T14:39:09Z 91706ce90336 confd[46]: ERROR Missing template: /app/templates/nginx.conf
```

```
--- VERSIONS ---
CoreOS 647.2.0
Deis v1.7.3
etcd version 0.4.9
fleetd version 0.9.2
```

**Comment by carmstrong** [comment] 2015-09-28 18:21
This is something we should look into. 

/cc @deis/production-team

**Comment by sstarcher** [comment] 2015-10-01 14:17
I had my router go down again.  I went to the box and did a simple docker stop/start and the "ERROR Missing template" went away.

Let me know if their is something I can do to help debug the issue.

**Comment by Blystad** [comment] 2015-10-01 14:46
Try running "lsof" next time and post the output. I have a theory that you're running out of file descriptors because of a leak in nginx.

**Comment by mboersma** [comment] 2015-11-03 00:16
nginx was updated to 1.9.4 since Deis v1.9.0. Has anyone seen this issue in Deis v1.10 or later? It could also be a `confd` problem I suppose.

**Comment by sstarcher** [comment] 2015-11-03 15:58
I have not seen this issue reoccur since switching to Deis 1.10

**Comment by krancour** [comment] 2015-12-01 08:26
I'm going to close this since there are no reports of this happening with versions newer than 1.10.

**Closed by krancour** 2015-12-01 08:26 UTC
Labels: bug, production-team, router
