### ISSUE TITLE
Vagrant: error: failed to push some refs

### ISSUE THREAD

**Issue by Crispy1975** [deis/deis#3995] opened 2015-07-09 14:41 UTC
Not sure if the issues reported in `https://github.com/deis/deis/issues/1330` are related but they seem similar. The problem I am having is with Vagrant, builds are working and successful, but when the process gets to the final steps we get the following error(s):

	Successfully built afa009ed8d44
	-----> Pushing image to private registry
	To ssh://git@deis.local3.deisapp.com:2222/my-app.git
	 ! [remote rejected] testing/deis -> master (pre-receive hook declined)
	error: failed to push some refs to 'ssh://git@deis.local3.deisapp.com:2222/my-app.git'

What is odd is that some apps deploy no problem at all, however there is always a long wait right after the `Successfully built ...` stage. I am guessing some kind of timeout, but not sure.

This is a new Vagrant cluster with nothing special going on (v1.7.3).

**Comment by szymonpk** [comment] 2015-07-09 15:29
Have you checked deis-builder and ceph logs? It might be issue with ceph since it's happening during Pushing phase.

**Comment by bacongobbler** [comment] 2015-07-15 20:24
gentle ping @Crispy1975. Any word on this?

**Comment by mboersma** [comment] 2015-07-15 20:27
Refs #2980.

**Comment by Crispy1975** [comment] 2015-07-15 22:00
@bacongobbler In the end we switched to using Dockerfiles over buildpacks as it also made sense for us getting private repo keys into the build process. Never got it to work again before switching. We're waiting on the Cephless release (or we'll build out an S3/RDS install) so we can get a new cluster going in AWS.

Happy to test a few things out with Vagrant locally however.

**Comment by bacongobbler** [comment] 2015-07-15 22:05
v1.8 is out! http://deis.io/deis-1-8-ceph-optional/

**Comment by bacongobbler** [comment] 2015-07-15 22:08
I guess since there's no builder/registry logs to follow up and the integration tests seem fine on master, we should probably close this and re-open if others are hitting the same issue. Would that seem fair to you?

**Comment by Crispy1975** [comment] 2015-07-15 22:28
@bacongobbler yeah, that is good with me. Now that 1.8 is out - awesome - I will build that out in AWS and run a few tests with both buildpacks, Dockerfiles, and pre-built images. Plus try a Ceph version with vagrant if I get a few spare moments to mess with it.

Thanks.

**Comment by bacongobbler** [comment] 2015-07-15 22:30
Any time! let's re-open again if you can reproduce on vagrant. We're been on a crusade to close out PRs that we can't follow up on, but we really appreciate your input. :)

Thanks!

**Closed by bacongobbler** 2015-07-15 22:30 UTC
