### ISSUE TITLE
Feature: Allow System & Application monitoring based on Graphite

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#2866] opened 2015-01-08 13:48 UTC
Warning: I have the feeling there should already be a bug report about this (maybe even commented on by me?) but I couldn't find it (I only looked at open bug reports though...)

As a Deis System Administrator I want to see

* Global (VM) Performance statistics over time (memory, CPU Utilization, Network Usage, (free) disk space). Normally this can be done by any networking system (zabbix), but "auto" configuration should be central (eg adding a node should automatically use this system).
Bonus points if I can add alerts that trigger on certain tresholds..

As a Deis user
* Per container metrics. This includes Memory Usage, CPU Usage, Network Usage etc per container & also averages per container type (web, worker, cmd, ...).
* Per web metrics. On top of that for the web type containers I also want metrics on requests (number of requests, response times, number of failed requests)...
This is similar to what Heroku provides. (https://devcenter.heroku.com/articles/metrics)
* As bonus points I should be able to use the same toolkit for custom metrics (number of logins, ...)

I think graphite together with collectd / statsd and others will be a perfect method to implement this.

Obviously all of this would probably be implemented as optional components that can just run onto the coreos cluster...

Note: I Understand it is not in Deis' scope to write a new monitoring tool that implements storing metrics, triggers etc... I merely propose using existing tools, whereby I think Graphite based stack might be a good start (althoug something else can probably work as well).

If there is any intrest in this I might have a look at it mystelf to build out a basic platform...

**Comment by PierreKircher** [comment] 2015-01-08 13:52
there is even a post on the readme .. as for collecting .. cadvisor / influxdb and how ever you call it .. are easy to install and give you a decent overview of the cluster

**Comment by bacongobbler** [comment] 2015-01-08 16:11
dupe of #981. Let's keep the discussion all in one place, please. Thanks :)

**Comment by bacongobbler** [comment] 2015-01-08 16:12
sorry, premature close. I didn't realize that one was closed. We'd be happy to see documentation on plugging into graphite for platform monitoring.

**Comment by nathansamson** [comment] 2015-01-08 23:02
@PierreKircher Somehow I missed that part of the documentation.

Note that cadvisor or the datadog solution only expose info of container metrics. And either makes everything availble to everyone or everything to only the sysadmin (not sure what authorization happens in cadvisor, I assume it is open to the world).
This is not very good :)

Also it doesn't seem ot be possible to have per app custom metrics.


I'll see if I can prepare something :)

**Comment by nathansamson** [comment] 2015-01-08 23:05
http://docs.deis.io/en/latest/managing_deis/platform_monitoring/?highlight=monitor seems to use fleetctl to load & distribute components.

Would it be viable to extend deisctl to allow custom components (either global, single unit or scalable)?

**Comment by bacongobbler** [comment] 2015-01-09 00:49
> Note that cadvisor or the datadog solution only expose info of container metrics. And either makes everything availble to everyone or everything to only the sysadmin (not sure what authorization happens in cadvisor, I assume it is open to the world).
> This is not very good :)

That's assuming that your cluster is running out in the open. If you're on EC2 for example, the only thing that's exposed is the load balancer endpoints. Running an internal cadvisor/graphite/whatever will only be reachable to the users who are authorized to use the cluster, which in most cases is just the administrator.

> Would it be viable to extend deisctl to allow custom components (either global, single unit or scalable)?

I don't see why not. I'd rather we first start looking at writing out a test suite for deisctl before we start implementing features (fleet/etcd is hard to mock) like an extension layer, but it's doable.

**Comment by bacongobbler** [comment] 2015-07-16 18:28
related: #3699

**Comment by krancour** [comment] 2015-07-22 16:17
> Note that cadvisor or the datadog solution only expose info of container metrics.

I feel like cadvisor's name of "container advisor" is a misnomer.  "cgroup advisor" might have been more appropriate.  cgroups are hierarchical, and although I can't recall its name off the top of my head, there is a "top level" cgroup for the user space (so everything non-kernel).  Metrics for that cgroup would be pretty close (as close as you can get with cadvisor) to VM-level metrics.  Just throwing that out there in case it's of any help in terms of DIY metrics until we roll out a more comprehensive telemetry solution.

**Comment by mboersma** [comment] 2015-08-31 03:46
#4110 has the current Deis project proposal for monitoring, metrics, telemetry--please follow up there.

**Closed by mboersma** 2015-08-31 03:46 UTC
Labels: proposal
