### ISSUE TITLE
logging issues and etcd failures on Deis 1.7.3

### ISSUE THREAD

**Issue by bf4** [deis/deis#4354] opened 2015-08-27 16:25 UTC
We too regularly get notified that our logging service isn't receiving information, so we have to run `deisctl restart logspout && deisctl restart logger`.

This is a major reason we're probably moving off of deis.  (Running on 1.9.0 regularly crashed as a 404. At least 1.7.3 isn't doing that).

```bash
deis_debug_logs() {
  ssh "core@$DEISCTL_TUNNEL" /bin/bash -l -c '/opt/bin/deis-debug-logs'
}

deis_debug_logs
--- VERSIONS ---
CoreOS 717.3.0
Deis v1.7.3
etcd version 0.4.9
fleetd version 0.10.2

--- SYSTEM STATUS ---
-- Logs begin at Thu 2015-08-27 09:53:18 UTC, end at Thu 2015-08-27 16:17:37 UTC. --
Failed to get journal fields: Cannot assign requested address
-- Logs begin at Thu 2015-08-27 09:53:18 UTC, end at Thu 2015-08-27 16:17:37 UTC. --
Aug 27 13:50:36 deis-v173-1 fleetd[746]: ERROR engine.go:217: Engine leadership lost, renewal failed: timeout reached
Aug 27 13:50:36 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 13:50:48 deis-v173-1 fleetd[746]: ERROR engine.go:217: Engine leadership lost, renewal failed: timeout reached
Aug 27 13:50:48 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 13:50:52 deis-v173-1 fleetd[746]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([28430908 != 28430952]) [28430970]
Aug 27 14:35:09 deis-v173-1 fleetd[746]: INFO manager.go:138: Triggered systemd unit deis-logspout.service stop: job=46504696
Aug 27 14:35:09 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StopUnit job=deis-logspout.service reason="unit currently launched but desired state is loaded"
Aug 27 14:35:13 deis-v173-1 fleetd[746]: INFO manager.go:127: Triggered systemd unit deis-logspout.service start: job=46504781
Aug 27 14:35:13 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StartUnit job=deis-logspout.service reason="unit currently loaded but desired state is launched"
Aug 27 14:35:18 deis-v173-1 fleetd[746]: INFO manager.go:138: Triggered systemd unit deis-logger.service stop: job=46505133
Aug 27 14:35:18 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StopUnit job=deis-logger.service reason="unit currently launched but desired state is loaded"
Aug 27 14:35:22 deis-v173-1 fleetd[746]: INFO manager.go:127: Triggered systemd unit deis-logger.service start: job=46505220
Aug 27 14:35:22 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StartUnit job=deis-logger.service reason="unit currently loaded but desired state is launched"
Aug 27 14:41:27 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 14:41:27 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 14:41:27 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 14:41:27 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 14:41:27 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 15:19:27 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 15:19:27 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 15:19:27 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 15:19:27 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 15:19:27 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 15:19:28 deis-v173-1 fleetd[746]: ERROR engine.go:217: Engine leadership lost, renewal failed: timeout reached
Aug 27 15:19:28 deis-v173-1 fleetd[746]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Aug 27 15:19:30 deis-v173-1 fleetd[746]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([28490274 != 28490331]) [28490413]
Aug 27 15:39:42 deis-v173-1 fleetd[746]: INFO manager.go:138: Triggered systemd unit deis-logspout.service stop: job=46542850
Aug 27 15:39:42 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StopUnit job=deis-logspout.service reason="unit currently launched but desired state is loaded"
Aug 27 15:39:47 deis-v173-1 fleetd[746]: INFO manager.go:127: Triggered systemd unit deis-logspout.service start: job=46542851
Aug 27 15:39:47 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StartUnit job=deis-logspout.service reason="unit currently loaded but desired state is launched"
Aug 27 15:39:52 deis-v173-1 fleetd[746]: INFO manager.go:138: Triggered systemd unit deis-logger.service stop: job=46543115
Aug 27 15:39:52 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StopUnit job=deis-logger.service reason="unit currently launched but desired state is loaded"
Aug 27 15:39:56 deis-v173-1 fleetd[746]: INFO manager.go:127: Triggered systemd unit deis-logger.service start: job=46543116
Aug 27 15:39:56 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StartUnit job=deis-logger.service reason="unit currently loaded but desired state is launched"
Aug 27 16:01:50 deis-v173-1 fleetd[746]: INFO manager.go:138: Triggered systemd unit deis-logspout.service stop: job=46545140
Aug 27 16:01:50 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StopUnit job=deis-logspout.service reason="unit currently launched but desired state is loaded"
Aug 27 16:01:54 deis-v173-1 fleetd[746]: INFO manager.go:127: Triggered systemd unit deis-logspout.service start: job=46545141
Aug 27 16:01:54 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StartUnit job=deis-logspout.service reason="unit currently loaded but desired state is launched"
Aug 27 16:01:58 deis-v173-1 fleetd[746]: INFO manager.go:138: Triggered systemd unit deis-logger.service stop: job=46545321
Aug 27 16:01:58 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StopUnit job=deis-logger.service reason="unit currently launched but desired state is loaded"
Aug 27 16:02:02 deis-v173-1 fleetd[746]: INFO manager.go:127: Triggered systemd unit deis-logger.service start: job=46545322
Aug 27 16:02:02 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StartUnit job=deis-logger.service reason="unit currently loaded but desired state is launched"
Aug 27 16:16:32 deis-v173-1 fleetd[746]: INFO manager.go:138: Triggered systemd unit deis-logspout.service stop: job=46546842
Aug 27 16:16:32 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StopUnit job=deis-logspout.service reason="unit currently launched but desired state is loaded"
Aug 27 16:16:36 deis-v173-1 fleetd[746]: INFO manager.go:127: Triggered systemd unit deis-logspout.service start: job=46546843
Aug 27 16:16:36 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StartUnit job=deis-logspout.service reason="unit currently loaded but desired state is launched"
Aug 27 16:16:41 deis-v173-1 fleetd[746]: INFO manager.go:138: Triggered systemd unit deis-logger.service stop: job=46547023
Aug 27 16:16:41 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StopUnit job=deis-logger.service reason="unit currently launched but desired state is loaded"
Aug 27 16:16:46 deis-v173-1 fleetd[746]: INFO manager.go:127: Triggered systemd unit deis-logger.service start: job=46547024
Aug 27 16:16:46 deis-v173-1 fleetd[746]: INFO reconcile.go:330: AgentReconciler completed task: type=StartUnit job=deis-logger.service reason="unit currently loaded but desired state is launched"
```

all services loaded, active, and running

possibly related https://github.com/deis/deis/issues/4300

**Comment by krancour** [comment] 2015-08-27 16:47
@bf4, this is likely caused by issue #3633 and already resolved by #4291.  You can look for that in the upcoming v1.10.0.

A more strategic upgrade of logspout in #4347 has also been shown to address this issue.  This will likely be included in v1.11.0.

> This is a major reason we're probably moving off of deis.

We'd certainly hate to see that happen.  Are you familiar with how to build `deis-logspout` from master?  If so, you can pick up and deploy that big fix now.  If not, I'd be happy to show you the steps.

**Comment by carmstrong** [comment] 2015-08-27 16:48
@bf4 Your errors look like etcd is falling over... what does `journalctl -fu etcd` look like on the `deis-v173-1` host?

Sorry to hear you're considering moving off Deis! Is this the main issue you're facing? How did you provision these hosts, and on what platform? etcd seems to have more trouble when it shares a filesystem with the Docker daemon, since IO contention will cause etcd to miss heartbeat timeouts. 

Also, a fresh provision of Deis v1.9.1 will use etcd 2.1.2 with plenty of bugfixes. I'd strongly encourage you to give that a shot.

**Comment by carmstrong** [comment] 2015-08-27 16:50
@bf4 Also, you're running a version of CoreOS (717.3.0) that is newer than our tested and recommended version of 647.2.0. There are known issues with the version of Docker in that release. Is it possible for you to reprovision Deis 1.9.1 on 647.2.0?

**Comment by krancour** [comment] 2015-08-27 16:51
@carmstrong good eye on those issues.  fwiw, I do think #3633 is _also_ a problem here since he noted that restarting logspout and logger help.

**Comment by bf4** [comment] 2015-08-27 16:53
( Thanks for the quick response.  I'm working on something else right now, but will come back to comment.)

**Comment by bf4** [comment] 2015-08-27 20:36
@carmstrong 

> Failed to get journal fields: Cannot assign requested address

**Comment by bf4** [comment] 2015-08-27 20:46
Would it be possible to apply https://github.com/deis/deis/pull/4291 to our deployment with minimal risk?  I'm not sure how to patch and rebuild the running service

This comment also looks useful as a workaround https://github.com/coreos/fleet/issues/1202#issuecomment-96896961

And someone else said setting ` KillMode=none` was a good workaround for them

**Comment by krancour** [comment] 2015-08-27 20:49
> Would it be possible to apply #4291 to our deployment with minimal risk? I'm not sure how to patch and rebuild the running service

Yes.  Easily done.  But if your etcd / fleet cluster is unhealthy, that should get fixed first.  There's no sense doing anything else before that is fixed.

**Comment by bf4** [comment] 2015-08-27 20:54
@krancour no idea how to fix the clusters nor hot fix the code...

**Comment by krancour** [comment] 2015-08-27 21:04
@bf4 Is this a production cluster?  What are the chances of re-provisioning at @carmstrong asked?  As he pointed out, you're running on a newer version of CoreOS than Deis has been tested against and it's a version with known issues-- namely with the included Docker.  If you can somehow afford the luxury of re-provisioning, 1.9.1 is much more stable on account of etcd2.

**Comment by bf4** [comment] 2015-08-27 21:06
I spent a week and a half running 1.9.0 and trying to debug why it was 404's.... got tired of it and reverted to our 1.7.3.  1.7.3 is serving the site, at least :)

**Comment by carmstrong** [comment] 2015-08-27 21:25
@bf4 What cloud provider are you on? Did you provision using our provision scripts? And can you show me a `df -h` and a `mount` on one of your hosts?

**Comment by bf4** [comment] 2015-08-27 21:29
digital ocean, yes, using the scripts...

`df -h`

```plain
ssh "core@$DEISCTL_TUNNEL" df -h
Filesystem                                      Size  Used Avail Use% Mounted on
devtmpfs                                        3.9G     0  3.9G   0% /dev
tmpfs                                           4.0G     0  4.0G   0% /dev/shm
tmpfs                                           4.0G  7.4M  3.9G   1% /run
tmpfs                                           4.0G     0  4.0G   0% /sys/fs/cgroup
/dev/vda9                                        76G   38G   35G  53% /
/dev/vda3                                       985M  346M  589M  37% /usr
tmpfs                                           4.0G     0  4.0G   0% /media
tmpfs                                           4.0G     0  4.0G   0% /tmp
/dev/vda6                                       108M   56K   99M   1% /usr/share/oem
10.x.x.x,10.x.x.y,10.x.x.z:/  226G  139G   88G  62% /var/lib/deis/store
```

`mount`

```plain
ssh "core@$DEISCTL_TUNNEL" mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=4077476k,nr_inodes=1019369,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
/dev/vda9 on / type ext4 (rw,relatime,data=ordered)
/dev/vda3 on /usr type ext4 (ro,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
tmpfs on /media type tmpfs (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
tmpfs on /tmp type tmpfs (rw)
/dev/vda6 on /usr/share/oem type ext4 (rw,nodev,relatime,commit=600,data=ordered)
10.x.x.x,10.x.x.y,10.x.x.z:/ on /var/lib/deis/store type ceph (rw,relatime,name=admin,secret=<hidden>,nodcache,nofsc)
```

**Comment by carmstrong** [comment] 2015-08-27 21:54
> digital ocean

Ah, okay. Other providers give us the ability to separate the etcd journal and Docker volume and place them on different devices. We've seen that in some conditions there is write contention between etcd and Docker that prevents etcd from working well. Additionally, etcd 0.4.x has a myriad of known issues. Even the etcd core team is recommending users to use the new 2.x branch exclusively. 

Our recommended course of action would be to provision a fresh cluster on Deis 1.9.1, as that has fixes we know of. We can certainly help you debug the 404s you were experiencing. We're also going to be shipping Deis 1.10.0 on Tuesday if you'd like to wait to give that a shot.

**Comment by bf4** [comment] 2015-08-27 21:56
Ok, I'm provisioning a new 1.9.1 now

**Comment by krancour** [comment] 2015-08-27 22:50
@bf4 when 1.9.1 is running smoothly, I'll show you steps for building _deis-logspout_ from master.  The steps will assume you have an adequate development environment set up as documented here:

http://docs.deis.io/en/latest/contributing/hacking/

Also if you _don't_ want to build _deis-logspout_ from master, as @carmstrong mentioned, we're releasing v1.10.0 shortly and there is a convenient "graceful upgrade" process that can get you easily from v1.9.0+ to any newer minor or fix release-- perfect for upgrading from v1.9.1 to v1.10.0.

Documentation for that here:

http://docs.deis.io/en/latest/managing_deis/upgrading-deis/#graceful-upgrade

**Comment by bf4** [comment] 2015-08-28 16:13
@carmstrong 

> you're running a version of CoreOS (717.3.0) that is newer than our tested and recommended version of 647.2.0

so, the digital ocean provision script just specifies the coreos-stable channel, but no version. I'm not sure how to pass `-V 647.2.0` to the `coreos-install`... is a pretty big blocker to building anything new

**Comment by bf4** [comment] 2015-08-28 16:20
if digital ocean uses https://github.com/coreos/init/blob/master/bin/coreos-install#L34 then I can set $VERSION_ID

**Comment by bf4** [comment] 2015-08-28 16:23
or specify it in the user-data https://github.com/digitalocean/doctl/blob/master/droplet.go (vs. docl client)

**Comment by bf4** [comment] 2015-08-28 16:58
per @bacongobbler this is a limitation of DO, that I can't just install http://stable.release.core-os.net/amd64-usr/647.2.0/coreos_production_image.bin.bz2  (in deis irc) 


per abcrawf in coreos irc there should be a public image

> > image: number (if using an image ID), or String (if using a public image slug)	The image ID of a public or private image, or the unique slug identifier for a public image. This image will be the base image for your Droplet.
>  CoreOS uses slugs (coreos-stable, coreos-beta, coreos-alpha) to point to the latest version, but you can also reference by ID to get older images
> bffff_> like coreos-674.2.0 ?
> 11:53 AM <bffff_> I haven't seen that documented or in e.g. coreos-isntall, but I wondered..
> 11:53 AM <abcrawf> bffff_: no, it will be some random ID number (e.g. 47563275)
> 11:54 AM <abcrawf> bffff_: the only way to get the number is to search their image list via the API
> 11:54 AM <abcrawf> bffff_: I don't have an automated way of doing that
> 11:54 AM <bffff_> I have yet to across such as list
 → tleyden and Industrial joined  
11:56 AM <abcrawf> bffff_: https://developers.digitalocean.com/documentation/v2/#list-all-images
11:57 AM <bffff_> that's just my images, I believe, or I'm hitting the wrong endpoint

or maybe I could build one?  https://www.packer.io/docs/builders/digitalocean.html

**Comment by bf4** [comment] 2015-08-31 15:47
Running smoothly! I got it out on Friday!

**Comment by krancour** [comment] 2015-08-31 16:25
@bf4 v1.10.0 release is around the corner and upgrade is easy.  Do you want to wait for that or build the fixed `deis-logspout` from master now?

If you have a development environment _already set up_, the steps would look something like this:

```
cd <local deis repo location>
git checkout master
git pull <remote name for github:deis/deis; e.g. upstream or origin depending on your setup> master
export DEV_REGISTRY=registry.hub.docker.com
cd logspout
make build deploy
```

The `build` task will build a new Docker image of `deis-logspout` based on master.

The `deploy` task will do a number of things.  It will push the newly built image up to a public Docker repository within your own account on Docker hub, it will update an etcd key in your cluster that instructs the `get_image` helper script on what Docker image to use for the `deis-logspout` component, and then it will stop and start the Fleet unit for `deis-logspout`.  Upon restart, the new image will automatically be pulled and used.

Let me know if that helps you or if you run into any problems with that procedure.

**Comment by krancour** [comment] 2015-09-09 21:00
@bf4 are you all set with this?

**Comment by bf4** [comment] 2015-09-09 21:21
Sorry, we're on AWS now.. during the brief period we used 1.9.1 it didn't seem to have any problems :) :(

**Closed** 2015-09-09 21:21 UTC
Labels: bug, etcd/fleet, logger
