### ISSUE TITLE
Azure: InvalidDomainNameLabel problem with provisioning

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#4854] opened 2016-01-14 06:49 UTC
I'm trying to follow the Deis guides on setting up a CoreOS cluster in Azure. I seem to be getting stuck at this:

> Type: Microsoft.Network/publicIPAddresses
>
>Resource Id: /subscriptions/57b1bfdb-07f3-493e-931f-c46ae13f962a/resourceGroups/deis0/providers/Microsoft.Network/publicIPAddresses/2
>
> StatusMessage:
> {"error":{"code":"InvalidDomainNameLabel","message":"The domain name label 2 is invalid. It must conform to the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$.","details":[]}}

I have these defined in parameters.json:

```js
{
  "newStorageAccountName": {
    "value": "deis0"
  },
  "publicDomainName": {
    "value": "hellocloud.io"
  },
  "dnsPrefixNameForPublicIP": {
    "value": ""
  },
```

**Comment by krancour** [comment] 2016-01-16 17:17
See #4593.  There is some discussion of the same problem.

**Comment by monaka** [comment] 2016-01-19 03:03
@rstacruz `publicDomainName` is used as a prefix to hostnames. Not your domain name.
 
For example, it will be created three instances that have hostname deisNode0, DeisNode1 and, DeisNode2 if you set "deisNode" as the value of `publicDomainName`.

**Comment by rstacruz** [comment] 2016-01-19 10:36
I tried setting it to a string of letters (like "hellocloud") and I still
got the same error.

**Comment by volderam** [comment] 2016-03-18 04:16
hellocloud  doesn't match this pattern: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$ You can check it here http://rubular.com/, for example.
publicDomainName should be something like hello-cloud or deis-node, ... etc.

**Comment by rstacruz** [comment] 2016-03-19 09:55
oh damn, alright. I don't have access to the Azure account anymore so I can't test this, however.

**Comment by carmstrong** [comment] 2016-03-20 06:27
> hellocloud doesn't match this pattern

It should! That should be okay as a `publicDomainName`. It must be 1-62 alphanumeric characters or hyphens. The original value is invalid because of the period in the string, but `hellocloud` should be acceptable.

Closing as @rstacruz doesn't seem to be using Azure anymore, and the root cause has been recorded for posterity.

**Closed by carmstrong** 2016-03-20 06:27 UTC
Labels: contrib and provisioning

**Comment by MadhurBhardwaj** [comment] 2017-09-26 07:10
I'm facing same error while deploying Docker EE cluster on azure , I'm not setting this value "PublicDomainName"...  it is auto generating this , but giving this issue.... 
"InValidDomainName"
