### ISSUE TITLE
Node fails and enters unrecoverable state

### ISSUE THREAD

**Issue by kingkevin** [deis/deis#3208] opened 2015-03-05 19:43 UTC
I've been experiencing an intermittent issue in which one of the three nodes in my cluster fails. All services that are running on that node enter a dead state and the node eventually leaves the cluster. However the node can still see the other machines using `fleetctl list-machines`

Upon reboot the node is no longer reachable by ssh.

Usually this occurs after a few weeks, and I usually take the opportunity to upgrade to the latest deis (yay 1.4!). Are there any docs for debugging this issue? I can pull logs from papertrail if that would help.

**Comment by bacongobbler** [comment] 2015-03-05 19:51
are you on EC2? I can't find the bug but I know that this has been reported on there.

**Comment by kingkevin** [comment] 2015-03-05 19:51
Yes

**Comment by bacongobbler** [comment] 2015-03-05 19:52
closing as a dupe of #2959

**Closed by bacongobbler** 2015-03-05 19:52 UTC
