### ISSUE TITLE
Can't push to deis after `deisctl restart builder`

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3977] opened 2015-07-07 06:40 UTC
One of my builds was taking forever to finish so I restarted the builder with `deisctl restart builder`. It restarted correctly but now all my `git push deis` fail with

```bash
$ git push deis
/usr/local/bin/gitreceive: line 33: /home/git/testnet.git/hooks/pre-receive: No such file or directory
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by bacongobbler** [comment] 2015-07-07 06:44
dupe of #3458

**Closed by bacongobbler** 2015-07-07 06:44 UTC

**Comment by olalonde** [comment] 2015-07-07 06:48
```
fleetctl ssh deis-builder
nse deis-builder
rm -rf /home/git/myproject.git
```

worked, thanks.
