### ISSUE TITLE
logspout message too long error

### ISSUE THREAD

**Issue by aledbf** [deis/deis#2046] opened 2014-10-07 17:20 UTC
After running the deis-logspout component for 2 days I see this error in the journal:
```console
Oct 06 11:56:25 nodo-1 sh[17045]: 2014/10/06 14:56:25 syslog: write udp 192.168.2.201:514: message too long
```
(occurred 2 times in those 2 days)

**Comment by nathansamson** [comment] 2016-01-25 13:35
I still have this issue on 1.12.2

~~~
Jan 25 13:07:25 ams3-cloud-beeple-5 sh[3485]: 2016/01/25 13:07:25 syslog: write udp 172.17.1.158:40559->10.133.120.13:514: write: message too long
Jan 25 13:07:25 ams3-cloud-beeple-5 systemd[1]: deis-logspout.service: Main process exited, code=exited, status=1/FAILURE
Jan 25 13:07:25 ams3-cloud-beeple-5 docker[4313]: Error response from daemon: no such id: deis-logspout
Jan 25 13:07:25 ams3-cloud-beeple-5 docker[4313]: Error: failed to stop containers: [deis-logspout]
Jan 25 13:07:25 ams3-cloud-beeple-5 systemd[1]: deis-logspout.service: Unit entered failed state.
Jan 25 13:07:25 ams3-cloud-beeple-5 systemd[1]: deis-logspout.service: Failed with result 'exit-code'.
Jan 25 13:07:30 ams3-cloud-beeple-5 systemd[1]: deis-logspout.service: Service hold-off time over, scheduling restart.
Jan 25 13:07:30 ams3-cloud-beeple-5 systemd[1]: Starting deis-logspout...
Jan 25 13:07:30 ams3-cloud-beeple-5 systemd[1]: Started deis-logspout.
~~~

Lets assume I try to log a stupidly long log message, it still should not cause a DOS on the logger for other applications as well...
(The logspout service restarted 8 times over a 10 minute period with the same problem)

**Comment by nathansamson** [comment] 2016-01-25 13:37
And yes its entirely possible I log stupidly long log messages.
My rails application logs full HTTP requests/responses to a 3rd-party API which is generating PDF files...

**Comment by bacongobbler** [comment] 2016-01-25 15:27
@nathansamson if you could run `docker logs` from one of your application instances, that would be helpful to determine if this is a long message error (or supply a similar log line that reproduces the issue)

**Comment by nathansamson** [comment] 2016-01-25 15:49
~~~
core@ams3-cloud-beeple-5 ~ $ docker logs --tail=153 9222bd35ca85 > last153
core@ams3-cloud-beeple-5 ~ $ tail -n 141 last153 | wc
    141    3718 3395478
core@ams3-cloud-beeple-5 ~ $ tail -n 140 last153 | wc
    140    3386  768585
~~~

So line 141 is 1578317 (more than twice) bytes longer as the current limit.
Not saying the current limit is not more than enough but either there should be an option to split lines over multiple UDP packets (although that would make the streaming server/processes too complex) or just ignore lines above a (configurable) parameter and not sent them through, and as a result also not crash.

When the condition happenings logging a line along "Sending log with length XXX which is too long." + the capped log line which would be either the first 4096 bytes or so, or just enough to fit the configurable length would be a good idea as well

**Comment by krancour** [comment] 2016-01-25 18:34
https://github.com/deis/deis/blob/master/logspout/logspout.go#L81

The buffer size set here is actually larger than the max UDP packet size-- the practical limit for which is 65,507 bytes (65,535 bytes minus 8 bytes of UDP headers and 20 bytes of IP headers).  No matter how big that buffer is set, a message larger than 65,507 bytes can not be sent in a single packet.

> either there should be an option to split lines over multiple UDP packets

UDP packets are by definition not related or ordered.  This would have to be implemented as an application-layer protocol.

> although that would make the streaming server/processes too complex

Exactly.  Beyond being complex, it would also be a ton of throwaway work since v2 doesn't use logspout.  Also, while we _could_ make the logger understand that custom app-layer protocol, other alternative log destinations not under our control (e.g. Papertrail) never would.

So this isn't an option.

> or just ignore lines above a (configurable) parameter and not sent them through, and as a result also not crash

fwiw, this is fixed in upstream logspout's master branch using a strategy something like that, but that hasn't made its way into a release yet and the pending release is a major one with many breaking changes.  Deis LTS won't be upgrading as it's too risky.

What I would propose be done here is that the code change such that the formatted string to be written (which includes the log message headers added by Deis for date/time and app, etc.) be prepared in advance (not on the fly).  That should be converted to bytes (to account for the possibility of non UTF-8 chars that consume more than a single byte) and the length of that byte slice should be compared to 65,507.  If it is any bigger, it should be trimmed down to 65,504 bytes and then have the bytes for "..." appended to the end.

This can be sent using `udpconn.Write(dataBytes)` and must _not_ be sent using `fmt.Fprint` since the latter is for writing strings; _not_ bytes.

I will gladly PR this is truncating in this fashion seems reasonable.  @bacongobbler thoughts?

fwiw, I think the TCP path through the code should receive the same treatment, but for different reasons.  Writing more bytes than can fit in a single packet is just fine when it comes to TCP, but on the logger end, there is still a simple assumption made that there is one log message per packet.

**Comment by bacongobbler** [comment] 2016-01-25 19:33
sgtm. I was unaware of the maximum packet size, so I guess my change essentially did nothing. I think truncating the log line is a reasonable fix unless there's another way to send multiple packets for one line that I'm unaware of (fwiw this is not an area I'm familiar with).

**Comment by krancour** [comment] 2016-01-25 19:37
> I guess my change essentially did nothing.

No... it did.  It increased the max length of the message beyond what it had been initially.  It just did not increase it up to as high as you thought.

**Comment by krancour** [comment] 2016-01-26 20:11
> fwiw, I think the TCP path through the code should receive the same treatment, but for different reasons. Writing more bytes than can fit in a single packet is just fine when it comes to TCP, but on the logger end, there is still a simple assumption made that there is one log message per packet.

I did PR this fix, but I ended up _not_ changing how things are done with TCP.  Testing revealed it to not be necessary.

**Closed** 2016-01-29 21:29 UTC
Labels: bug
