### ISSUE TITLE
Spontaneous kernel reboot

### ISSUE THREAD

**Issue by ianblenke** [deis/deis#3372] opened 2015-03-25 16:34 UTC
CoreOS 557.2.0 host reboot

```
[1977593.083649] polling.rb:25 invoked oom-killer: gfp_mask=0x50, order=0, oom_score_adj=0
[1977593.088480] polling.rb:25 cpuset=docker-08028fe1cf868eab49a1d1255bb05a2286a305562af7e4402248e3008b638c80.scope mems_allowed=0
[1977593.095756] CPU: 2 PID: 15190 Comm: polling.rb:25 Not tainted 3.18.1 #2
[1977593.099864] Hardware name: Xen HVM domU, BIOS 4.2.amazon 06/02/2014
[1977593.104131]  ffff880024629400 ffff880151e13be8 ffffffff814eef09 0000000000000001
[1977593.108912]  ffff88014a206400 ffff880151e13c88 ffffffff814ec607 ffff880151e13c18
[1977593.113593]  ffffffff8114b1ff[    6.193066] xenbus_probe_frontend: Waiting for devices to initialise: 

25s...20s...15s...10s...5s...
```

**Comment by gabrtv** [comment] 2015-03-25 17:46
@ianblenke looks like an out of memory error caused by a userspace process (`polling.rb:25`).  Does that fit the bill?  More on the Linux OOM killer here: https://lwn.net/Articles/317814/

**Comment by bacongobbler** [comment] 2015-03-26 18:50
is this a CoreOS issue or a Deis issue? If there's nothing we can do on our end then this should be reported upstream.

**Comment by mboersma** [comment] 2015-04-07 03:39
This looks like a CoreOS issue rather than anything specific to Deis. I'm closing this, but please re-open if I'm mistaken.

**Closed by mboersma** 2015-04-07 03:39 UTC
