### ISSUE TITLE
Unable to deploy when a config entry contains a space

### ISSUE THREAD

**Issue by simpsora** [deis/deis#3663] opened 2015-05-11 00:27 UTC
This may be a regression from https://github.com/deis/deis/issues/2682 / https://github.com/deis/deis/pull/2335.

When a config entry has a space in it, I'm unable to deploy via `git push`:

```
$ deis --version
1.5.2

$ deis config
=== recommender-api Config
NEW_RELIC_APP_NAME         "Recommender API"

$ git push deis master
Counting objects: 876, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (511/511), done.
Writing objects: 100% (876/876), 161.29 KiB | 0 bytes/s, done.
Total 876 (delta 384), reused 643 (delta 249)
Unable to find image 'API:latest' locally
time="2015-05-11T00:10:05Z" level="fatal" msg="Invalid repository name (API), only [a-z0-9-_.] are allowed"
To ssh://git@deis.discovery.envato.com:2222/recommender-api.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis.discovery.envato.com:2222/recommender-api.git'
```

When I remove the space, it deploys fine:

```
$ deis config:set NEW_RELIC_APP_NAME="RecommenderAPI"
Creating config... done, v13

=== recommender-api
NEW_RELIC_APP_NAME: RecommenderAPI

$ git push deis master
Counting objects: 10, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (10/10), 2.11 KiB | 0 bytes/s, done.
Total 10 (delta 6), reused 0 (delta 0)
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.1.6
...
SUCCESS!
```

Versions:

* CoreOS 633.1.0
* Deis v1.5.2
* etcd version 0.4.8
* fleetd version 0.9.1

**Comment by carmstrong** [comment] 2015-05-11 03:29
Pretty sure this is a duplicate of #2980 - we tried to fix the builder parsing of config values, but it only caused other issues, and resulted in a few regressions so we backed off the change :(

@bacongobbler is evaluating (#3578) the work to rewrite builder in Go so we can fix some of these issues.

**Comment by simpsora** [comment] 2015-05-11 21:45
Thanks @carmstrong, looks like there are a lot of issues around this.  It's not a big issue for me, since I can just remove the space.  I'll leave it with you guys.

**Comment by carmstrong** [comment] 2015-05-15 21:27
@simpsora Sorry for the trouble - I'm going to close in #2980 since it's the same issue. Thanks for taking the time to report!

**Closed by carmstrong** 2015-05-15 21:27 UTC
Labels: builder
