### ISSUE TITLE
Force SSL behind AWS ELB results in a redirect loop.

### ISSUE THREAD

**Issue by Crispy1975** [deis/deis#4400] opened 2015-09-03 12:49 UTC
`deisctl config router set enforceHTTPS=true`

Results in redirect loop on Cephless 1.9 install.

**Comment by krancour** [comment] 2015-09-06 14:30
Can you be more specific?  Is the redirect loop you're seeing happening when accessing the controller via the `deis` CLI?  Or are you seeing this when making a request to a deployed application?

**Comment by Crispy1975** [comment] 2015-09-06 14:34
This is on a deployed application. It/they listen on port 80 behind the ELB. The ELB is forwarding 80 to 80 and 443 to 80. Setting the router to force SSL results in too many redirects on the browser.

**Comment by krancour** [comment] 2015-09-06 16:11
You're terminating SSL at the load balancer?

**Comment by Crispy1975** [comment] 2015-09-06 16:35
Yeah.

**Comment by krancour** [comment] 2015-09-06 18:19
So that's where the loop comes from.  You're terminating SSL at the load balancer... the load balancer initiates a new non-SSL request to the router.  The router says, "you need to use SSL" and redirects.  Do you absolutely need to terminate SSL at your ELB?  You ahould probably avoid that if you can.

**Comment by nathansamson** [comment] 2015-09-06 18:32
You should be able to pass a header like x-forwarded-proto with value https
that will tell apps (works in rails at least) to actually not redirect in
this case.

So that's where the loop comes from. You're terminating SSL at the load
balancer... the load balancer initiates a new non-SSL request to the
router. The router says, "you need to use SSL" and redirects. Do you
absolutely need to terminate SSL at your ELB? You ahould probably avoid
that if you can.

—
Reply to this email directly or view it on GitHub
<https://github.com/deis/deis/issues/4400#issuecomment-138106008>.

**Comment by Crispy1975** [comment] 2015-09-06 21:21
The Deis router should check for `http_x_forwarded_proto` as this is sent from the ELB so it's possible for nginx to detect the SSL termination and stop the loop.

We have terminated at the Deis router at the moment but have other issues there right now.

**Comment by sstarcher** [comment] 2015-11-05 20:45
I have not verified this, but if the ELB protocol is SSL and not HTTPS it won't add the http_x_forwarded_proto header.

**Comment by bacongobbler** [comment] 2015-11-05 21:29
Hmm... So perhaps using the router's proxy protocol in #3096 to enable websockets on AWS could have broken HTTPS redirects? That's an interesting proposition.

@Crispy1975 can you verify as well if this may be the case?

**Comment by Crispy1975** [comment] 2015-11-09 10:43
@bacongobbler @sstarcher unfortunately we have switched to SSL termination on the Deis Router as we wanted to have socket support later on, so right now we just use the ELB for plain load balancing. We have another issue open - https://github.com/deis/deis/issues/4504 - relating to this and `enforceHTTPS`.

**Comment by Crispy1975** [comment] 2015-11-09 10:49
@bacongobbler I believe that @sstarcher is correct. The CloudFormation template sets the ELB to forward TCP (SSL) packets and not HTTP(S) so the HTTP headers required by the router would not be present. That makes the most sense to me.

**Comment by sstarcher** [comment] 2015-12-01 19:38
I can confirm that to use enforceHTTPS you can't be using proxyProtocol.
If you are not using proxyProtocol you can't use enforceWhitelist or DEIS_WHITELIST

Anyone have any idea for implementing enforceHTTPS, SSL termination at AWS ELBs and enforceWhitelist all at the same time?

**Comment by laurrentt** [comment] 2015-12-01 22:18
@sstarcher I had to add this to enable DEIS_WHITELIST and enforceHTTPS without proxyProtocol: 
```
real_ip_header X-Forwarded-For;
set_real_ip_from {{ or (getv "/deis/router/proxyRealIpCidr") "0.0.0.0/0" }};
```

**Comment by sstarcher** [comment] 2015-12-01 22:46
Would it make sense in the nginx config to add those 2 values if proxyProtocol is turned off.

```    {{ $useProxyProtocol := or (getv "/deis/router/proxyProtocol") "false" }}{{ if ne $useProxyProtocol "false" }}
    set_real_ip_from {{ or (getv "/deis/router/proxyRealIpCidr") "10.0.0.0/8" }};
    real_ip_header proxy_protocol;
    {{ end }}
```

**Comment by bacongobbler** [comment] 2016-01-21 23:53
Okay, so the action item here is to disable proxyProtocol by default so users can force SSL redirection. If users want websocket support in AWS then they can enable the proxy protocol support, but since that covers a very specific use case then we shouldn't have it enabled if it's blocking higher priority things like SSL redirection.

**Comment by krancour** [comment] 2016-01-25 19:48
fwiw, the argument _against_ disabling proxy proto by default is that it allows router and applications to know the IP of the actual end-user.  That's almost always a desirable bit of information.

**Comment by krancour** [comment] 2016-01-25 19:48
That is to say, this wasn't only for the benefit of the less common case of using web sockets.

**Comment by Blystad** [comment] 2016-01-25 20:01
Hmm...

I think there's something wrong with your nginx based force SSL Redirect configuration. 

See the following two links:

http://http-dump.dev.hostedmobiles.com/
https://http-dump.dev.hostedmobiles.com/

(Ignore that the second doesn't have a valid certificate)

Nginx correctly passes on the headers, with:
```
GET / HTTP/1.1
Host: http-dump.dev.hostedmobiles.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Connection: close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: no,en-US;q=0.8,en;q=0.6,nb;q=0.4,en-GB;q=0.2
Connection: close
Upgrade-Insecure-Requests: 1
X-Forwarded-For: XXXXXX
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Ssl: on
```

on the https version.

Then see: http://cx.pixavi.com vs https://cx.pixavi.com where I have force SSL redirect implemented in the end application. (By configuring the Java webapp container to force SSL usage: https://stackoverflow.com/questions/22625699/how-to-redirect-automatically-to-https-with-spring-boot ).

**Comment by krancour** [comment] 2016-01-25 21:16
Ok.  So I've got a v1.12.2 cluster up and running right now.  I'm using proxy proto, a valid wildcard cert for my domain, and `enforceHTTPS=true`.

I am not encountering any problem at all with this configuration.

Where I _do_ encounter a problem is when I go back to @Crispy1975's original configuration.  If I attempt to terminate SSL at the load balancer with proxy protocol enabled (on the ELB itself and on the router end) then I do have problems, although they look more like errors to me than a redirect loop.

At any rate... this experimentation has reduced my belief that there is an actual problem here.  When a load balancer terminates an HTTPS request and initiates an HTTP request to the backend, all HTTP headers should be set appropriately, including `X-Forwarded-For`, and afaik, that should negate any practical need for using proxy protocol to begin with.  (That is to say, proxy protocol is most needed wherever HTTP is _not_ spoken and raw TCP traffic is being piped through to the router.)

The conclusion I am drawing is this:

* Terminating SSL at the ELB is (of course) mutually exclusive with using TCP listeners on 80 and 443
* PROXY protocol is only useful when using TCP listeners
* Terminating SSL at the ELB and using PROXY protocol are therefor mutually exclusive

Ultimately, I do believe that _not_ terminating SSL at the ELB is the more common use case.  Since that means using TCP listeners, that means also leaving PROXY protocol enabled by default since that will allow the router to learn the end user's IP in the absence of an `X-Forwarded-For` HTTP header that the ELB would _not_ have set in such a case.

I would suggest that disabling PROXY protocol by default undermines this most common use case.

Now my inclination toward humility asserts itself-- it's possible I have this entirely wrong and if that is the case, I am eager for whatever I am missing to be pointed out.  :)

**Comment by sstarcher** [comment] 2016-01-25 21:21
@krancour I believe all that you said is correct minus, but I believe a bug still exists.

```
If you are not using proxyProtocol you can't use enforceWhitelist or DEIS_WHITELIST

Anyone have any idea for implementing enforceHTTPS, SSL termination at AWS ELBs and enforceWhitelist all at the same time?
```

* enforceHTTPS=true
* enforceWhitelist=true
* proxyProtocol=false
* SSL termination at AWS ELB
* DEIS_WHITELIST fails to block connections

**Comment by bacongobbler** [comment] 2016-01-25 21:30
@sstarcher since that is out of the context of this specific issue (redirect loop when enforceHttps=true), would you mind opening a different issue so we can track that separately? Thanks.

**Comment by Blystad** [comment] 2016-01-26 12:29
Hmm, so the issue is that when you terminate SSL on the ELB instead of on the router, by redirecting everything from port 443 -> 80, problems occur.

Maybe we could just add a flag on port 443 that disable SSL, and then use nginx [server_port](http://nginx.org/en/docs/http/ngx_http_core_module.html#.24server_port) instead of access_protocol.

That feels like a better all-round solution then just ripping out Proxy Protocol, and it would work if there was a third party load balancer with the same caveat as ELB.

**Comment by Blystad** [comment] 2016-01-26 12:39
Something like:

```diff
diff --git a/router/rootfs/etc/confd/templates/nginx.conf b/router/rootfs/etc/confd/templates/nginx.conf
index 9c94571..e331b2e 100644
--- a/nginx.conf
+++ b/nginx.conf
@@ -65,11 +65,19 @@ http {
         ''      close;
     }
 
+    {{ $disableSsl := or (getv "/deis/router/disableSsl") "false" }}
+    {{ if ne $disableSsl "false" }}
     # trust http_x_forwarded_proto headers correctly indicate ssl offloading
     map $http_x_forwarded_proto $access_scheme {
       default $http_x_forwarded_proto;
       ''      $scheme;
     }
+    {{ else }}
+    map $server_port $access_scheme {
+      default 'http';
+      '443'   'https';
+    }
+    {{ end }}
 
     ## HSTS instructs the browser to replace all HTTP links with HTTPS links for this domain until maxAge seconds from now
     {{ $enableHSTS := or (getv "/deis/router/hsts/enabled") "false" }}
@@ -211,7 +219,7 @@ http {
         server_name_in_redirect off;
         port_in_redirect off;
         listen 80{{ if ne $useProxyProtocol "false" }} proxy_protocol{{ end }};
-        listen 443 ssl http2{{ if ne $useProxyProtocol "false" }} proxy_protocol{{ end }};
+        listen 443{{ if ne $disableSsl "false" }} ssl{{ end }} http2{{ if ne $useProxyProtocol "false" }} proxy_protocol{{ end }};
         ssl_certificate /etc/ssl/deis/certs/{{ $app_domain }}.cert;
         ssl_certificate_key /etc/ssl/deis/keys/{{ $app_domain }}.key;
         include ssl.conf;
@@ -431,7 +439,7 @@ http {
         server_name_in_redirect off;
         port_in_redirect off;
         listen 80{{ if ne $useProxyProtocol "false" }} proxy_protocol{{ end }};
-        listen 443 ssl http2{{ if ne $useProxyProtocol "false" }} proxy_protocol{{ end }};
+        listen 443{{ if ne $disableSsl "false" }} ssl{{ end }} http2{{ if ne $useProxyProtocol "false" }} proxy_protocol{{ end }};
         ssl_certificate /etc/ssl/deis/certs/{{ $app_domain }}.cert;
         ssl_certificate_key /etc/ssl/deis/keys/{{ $app_domain }}.key;
         include ssl.conf;
```

(Not tested, but I think it should work)

**Comment by krancour** [comment] 2016-01-26 14:06
> Hmm, so the issue is that when you terminate SSL on the ELB instead of on the router, by redirecting everything from port 443 -> 80, problems occur.

I tested this exact configuration and could not trigger any sort of redirect loop.

**Comment by krancour** [comment] 2016-01-26 15:33
> I have force SSL redirect implemented in the end application.

^ That is the bit I didn't test.

I'm trying that now.

**Comment by krancour** [comment] 2016-01-26 16:50
Ok.  This was likely my last try at this.

Here's my configuration from front to back:

* ELB using HTTP/S in and HTTP only out to the router(s).  No proxy protocol in play (mutually exclusive with HTTP/S listeners).  HTTPS listener on 443 is configured with a valid wildcard cert.

* Router has `enforceHTTPS` unset.

* Rails application has `config.force_ssl = true`

Still, I cannot trigger a redirect loop.

If I log all the HTTP headers received by the application, these are among them:

```
2016-01-26T16:40:33UTC foobar[web.1]: HTTP_X_FORWARDED_PORT: 443
2016-01-26T16:40:33UTC foobar[web.1]: HTTP_X_FORWARDED_PROTO: https
2016-01-26T16:40:33UTC foobar[web.1]: HTTP_X_FORWARDED_FOR: 73.68.36.13, 10.21.2.216
2016-01-26T16:40:33UTC foobar[web.1]: HTTP_X_FORWARDED_SSL: on
```

Besides being unable to reproduce the issue, these headers would seem to indicate that the ELB and router are doing precisely the correct thing with respect to SSL offloading.

The only remaining explanation for the redirect loop is that application or application framework that is enforcing the use of HTTPS is not taking the `HTTP_X_FORWARDED_*` headers into account.

Scrolling back through this issue... it's long, contains much speculation and has multiple users reporting multiple problems, reported under varying configurations.  I've tried to investigate each permutation that allegedly triggers a redirect loop and still cannot reproduce.  As we attempt to narrow down the what makes it into the LTS release and what doesn't, it's useful to us to try and close these more nebulous issues.  So... I _am_ going to close this, but I would invite anyone who is still having trouble to open up a new issue that's narrowly scoped to your specific configuration and I would be happy to investigate further.

**Closed by krancour** 2016-01-26 16:50 UTC
Labels: bug, router

**Comment by sstarcher** [comment] 2016-01-26 18:22
@krancour yes I believe their is no redirect loop.  The only issue that I know of is #4869

**Comment by januszm** [comment] 2017-05-12 21:40
Hi guys, I'm wondering if you came to a good solution for one of the cases discussed here, that is how to configure the ELB and nginx in a way that:
* TCP/SSL is used in Elastic Load Balancer
* because of the above, X-Forwarded-Proto is missing
* nginx sitting behind the load balancer should know what was the original protocol of the request (was it http or https)

**Comment by bacongobbler** [comment] 2017-05-12 21:45
couple of threads in deis/router you can give a shot:

https://github.com/deis/router/issues/294
https://github.com/deis/router/issues/167

**Comment by januszm** [comment] 2017-05-12 22:15
Thanks @bacongobbler , very interesting discussions, in my case I guess the solution is to enable PROXY protocol on TCP load balancer (AWS) (http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html)

**Comment by januszm** [comment] 2017-05-13 19:15
Nah, the problem with my intended approach is that `$proxy_protocol_port` variable stores the CLIENT_PORT not the PROXY_PORT (see the Amazon doc in my previous message).

It's useless since the `CLIENT_PORT` value is totally different that `80` or `443`, (it's something like `51505`)

A typical PROXY PROTOCOL line looks like:
```
PROXY TCP4 192.168.0.1 192.168.0.11 56324 443
```

unfortunately nginx 1.11+ does not use the last item on the list but instead reads one before.

**Comment by krancour** [comment] 2017-05-13 20:11
@januszm are you using Deis v1.x (the old platform) or Deis Workflow (v2+)?

**Comment by januszm** [comment] 2017-05-13 20:19
@krancour I'm actually not using Deis in this case, no need to continue this topic, sorry!
