### ISSUE TITLE
controller exposes all container port bindings instead of first

### ISSUE THREAD

**Issue by philhug** [deis/deis#1156] opened 2014-06-11 17:03 UTC
tested on deis revision: df1c0edd7f9f44999da5d11d5f2c674bf0b17a78  Tue Jun 10 14:00:57 2014 -0700

CoreOS 343.0.0

deis executes the following code:
 core@core1 ~ $ docker inspect -f '{{range $i, $e := .HostConfig.PortBindings }}{{$p := index $e 0}}{{$p.HostPort}}{{end}}' wp_v2.cmd.1
4915349154

the result is a concatenation of the 2 ports which obiously doesn't work.

**Comment by bacongobbler** [comment] 2015-02-03 19:50
For a temporary fix, we could just expose the first port available (in this case, that'd be the lowest port number because the docker API sorts them numerically). That way we can support more app images that expose more than one port, but the lowest port number is the HTTP port.

**Comment by eMxyzptlk** [comment] 2015-04-15 20:46
Is there a way to work with an image that has two ports? For example, Gerrit requires a web port and an ssh port for pushing the repository, how can I make that work?

**Comment by Xe** [comment] 2015-04-15 21:27
The problem is that things like Gerrit fundamentally differ from the application workflow that things like Deis assume.

**Comment by resouer** [comment] 2015-04-16 06:37
@eMxyzptlk  Deis is more like a transitional PaaS which assume its apps like 12-factor model.

Try kubernetes or mesos.

**Comment by eMxyzptlk** [comment] 2015-04-16 15:51
I'll keep Deis because in-house we are following the 12-factor model. I'll just deploy Gerrit to another server outside of Deis in this case.

**Comment by bacongobbler** [comment] 2015-04-16 19:53
Okay, that sounds like a good alternative. Unfortunately the reason why we cannot support something like Gerrit at this time is because of

a) this issue
b) no tcp support in the router for applications: #1315 

This issue with multiple ports should get resolved in the meantime, but we need to properly flesh out a design for how we can support multi-port applications... Which will probably roll out in a major release considering that it's a backwards-incompatible change.

**Closed** 2015-05-11 20:00 UTC
Labels: bug, controller
