### ISSUE TITLE
Some API calls return 404 instead of 403 when a user doesn't have permission

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#2858] opened 2015-01-07 00:48 UTC
The following CLI commands will return 404 instead of 403 (as they should):
* info
* scale
* logs
* run
* destroy

Related: #2854

**Comment by carmstrong** [comment] 2015-01-07 00:50
Note that this isn't necessarily comprehensive - these were noticed in hand-testing various commands as part of #2856.

**Comment by bacongobbler** [comment] 2015-01-15 20:43
While running through #2898, I found that this is a limitation that we brought upon ourselves with our queryset and how we model our API endpoints.

In our AppViewSet, we set `.get_queryset()` to give us only the applications that we have either created (i.e. we are the owner) or ones which we were given permission to use (`use_app` from django-guardian). This is such that when we list apps via `/v1/apps`, it will only show us that filtered viewset. However, that also limits the scope on what applications we can act upon. Since `.get_queryset()` returns a queryset of applications that we only know about, it returns a 404 when we try to "ping" an application we were not given access to.

Therefore, there are a few choices:

1. change `.get_queryset()` to be unbounded, manually patch `.list()` to show the limited queryset (ugly, but backwards-compatible)

2. change `.get_queryset()` to be unbounded, add a filter to `/v1/apps` to show apps relevant to the user, modify `deis apps:list` in the client to use this new endpoint (backwards-incompatible, but RESTful)

3. close this as a limitation and define as "working as intended".

(1) Would be the quickest solution, but ultimately means that we are manually patching one of our endpoints and cannot take advantage of future DRF fixes to `.list()`. (2) would be "the right thing" to do, but we're unable to break endpoint APIs any more now that we're considered backwards-compatible. Older clients would also break in that they'd be displaying all applications on the platform rather than the user's limited queryset of applications.

**Closed** 2015-01-22 22:19 UTC
