### ISSUE TITLE
Exception in logs on store-volume startup

### ISSUE THREAD

**Issue by chrisgeo** [deis/deis#3460] opened 2015-04-12 03:45 UTC
I saw this come up in the logs when store-gateway stalled with the ceph error, then the store-volume couldn't come up:

```shell
Apr 12 03:35:53 foobar-apps-coreos-4 sh[1027]: Waiting for ceph gateway on 8888/tcp...
Apr 12 03:35:53 foobar-apps-coreos-4 sh[1027]: curl: (56) Recv failure: Connection reset by peer
Apr 12 03:35:54 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:54Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381612/1364428]) [1382611]
Apr 12 03:35:54 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:54Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381612/1364428]) [1382611]
Apr 12 03:35:54 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:54Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381612/1364428]) [1382611]
Apr 12 03:35:54 foobar-apps-coreos-4 sh[1027]: Waiting for ceph gateway on 8888/tcp...
Apr 12 03:35:54 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:54Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381612/1364428]) [1382611]
Apr 12 03:35:54 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:54Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381612/1364428]) [1382611]
Apr 12 03:35:54 foobar-apps-coreos-4 sh[1027]: curl: (56) Recv failure: Connection reset by peer
Apr 12 03:35:54 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:54Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381612/1364428]) [1382611]
Apr 12 03:35:54 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:54Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381612/1364428]) [1382611]
Apr 12 03:35:54 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:54Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381612/1364428]) [1382611]
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: wal_e.retries WARNING  MSG: retrying after encountering exception
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: DETAIL: Exception information dump:
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: Traceback (most recent call last):
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 62, in shim
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: return f(*args, **kwargs)
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/s3/s3_deleter.py", line 27, in _delete_batch
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: bucket.delete_keys([key.name for key in page])
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 726, in delete_keys
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: while delete_keys2(headers):
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 714, in delete_keys2
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: data=data)
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: retry_handler=retry_handler
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1070, in make_request
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: retry_handler=retry_handler)
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1029, in _mexe
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: raise ex
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: error: [Errno 104] Connection reset by peer
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
Apr 12 03:35:55 foobar-apps-coreos-4 sh[5282]: STRUCTURED: time=2015-04-12T03:35:55.139649-00 pid=35200
Apr 12 03:35:55 foobar-apps-coreos-4 sh[1027]: Waiting for ceph gateway on 8888/tcp...
Apr 12 03:35:55 foobar-apps-coreos-4 sh[1027]: curl: (56) Recv failure: Connection reset by peer
Apr 12 03:35:56 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:56Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381614/1364428]) [1382613]
Apr 12 03:35:56 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:56Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381614/1364428]) [1382613]
Apr 12 03:35:56 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:56Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381614/1364428]) [1382613]
Apr 12 03:35:56 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:56Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381614/1364428]) [1382613]
Apr 12 03:35:56 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:56Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381614/1364428]) [1382613]
Apr 12 03:35:56 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:56Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381614/1364428]) [1382613]
Apr 12 03:35:56 foobar-apps-coreos-4 sh[5282]: 2015-04-12T03:35:56Z e2851c9c60ad confd[140]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [1381614/1364428]) [1382613]
```

**Comment by bacongobbler** [comment] 2015-04-12 06:35
closing as a duplicate of #3436. If you can help test #3451 that would be appreciated. Thanks!

**Closed** 2015-04-12 06:36 UTC
