### ISSUE TITLE
upgrade-fleet-091.service does not run after reboot

### ISSUE THREAD

**Issue by wenzowski** [deis/deis#3579] opened 2015-04-25 01:39 UTC
It appears situations exist (eg. on Rackspace) where [upgrade-fleet-091.service](https://github.com/deis/deis/blob/97ce4148e2967deff13887c2ffdef4b28c5d3382/contrib/coreos/user-data.example#L23) does not run correctly following a reboot because the [conf symlink](https://github.com/deis/deis/blob/97ce4148e2967deff13887c2ffdef4b28c5d3382/contrib/coreos/user-data.example#L29) gets persisted but `/run/deis/bin/fleetd-0.9.2` does not.

**Comment by wenzowski** [comment] 2015-04-25 01:41
what's the rationale of checking for the existence of the symlink instead of `/run/deis/bin/fleetd-0.9.2` directly?

**Comment by carmstrong** [comment] 2015-04-25 07:48
Dupe of #3547. 

> what's the rationale of checking for the existence of the symlink instead of /run/deis/bin/fleetd-0.9.2 directly?

I can't recall why I did that - perhaps there's no reason.

**Closed by carmstrong** 2015-04-25 07:48 UTC
