### ISSUE TITLE
Deis git push fails

### ISSUE THREAD

**Issue by mooyah** [deis/deis#4921] opened 2016-02-17 00:19 UTC
Hello,

When I try to push my git repo to the deis remote, I'm getting an ssh failure. We recently had to rebuild our coreos cluster due to a power failure. We deleted all of the store components, deleted the btrfs, and then reinstalled the platform.

`[05:13 PM] ~/repositories/spotxvm [master] > git remote show deis
debug2: ssh_connect: needpriv 0
debug1: Connecting to deis.lod [192.168.184.104] port 2222.
debug1: Connection established.
debug1: identity file /home/joel/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/joel/.ssh/id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9p1 Ubuntu-2ubuntu0.1
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

[05:14 PM] ~/repositories/spotxvm [master] > deis keys
=== joel Keys
joel@jo....com ssh-rsa AAAAB3Nz...works.com

Looking at the journal for the builder, it seems to have some errors...
[05:26 PM] ~/repositories/spotxvm [master] > deisctl --tunnel=deis.lod journal builder
-- Logs begin at Sun 2016-01-17 20:59:36 UTC. --
Feb 12 17:44:21 coreos001 systemd[1]: Started deis-builder.
Feb 12 18:10:30 coreos001 sh[13661]: [info] Checking closer.
Feb 12 18:10:30 coreos001 sh[13661]: [info] Accepted connection.
Feb 12 18:10:30 coreos001 sh[13661]: [error] Failed handshake: ssh: server has no host keys (&{{0xc82045fa40}})

Let me know if you need more information!

On another note, looking at the registry, it looks like a few of the old apps are still running, even though they are no longer registered!

[05:29 PM] ~/repositories/spotxvm [master] > deis apps:list
=== Apps
[05:28 PM] ~/repositories/spotxvm [master] > deisctl --tunnel=deis.lod journal registry
Feb 17 00:28:44 coreos003 sh[19524]: 17/Feb/2016:00:28:44 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Feb 17 00:28:44 coreos003 sh[19524]: 192.168.184.104 - - [17/Feb/2016:00:28:44 +0000] "GET /v1/repositories/spotx-web-advtools-flightsegments/images HTTP/1.1" 404 29 "-" "docker/1.8.3 go/go1.4.2 git-commit/cedd534-dirty kernel/4.2.2-coreos-r1 os/linux arch/amd64"
.. etc ..

TYIA for your help.

**Comment by olalonde** [comment] 2016-02-17 02:51
Does `deisctl config platform get sshPrivateKey` return something?

**Comment by mooyah** [comment] 2016-02-17 02:57
Hi @olalonde, 

Yes, that command does return the private key associated with the sysadmin account that setup this cluster.

**Comment by olalonde** [comment] 2016-02-17 03:47
I had a problem similar to yours recently and eventually fixed it though I'm not sure I recall what I did exactly: https://github.com/deis/deis/issues/4893#issuecomment-177783472

Maybe try `etcdctl rm /sshHostKey` and restart the platform.

**Comment by mooyah** [comment] 2016-02-17 04:25
That fixed it! Thanks for your help @olalonde!

**Comment by bacongobbler** [comment] 2016-02-17 04:38
awesome. Thanks for chiming in, @olalonde :) closing as a duplicate of #4893.

**Closed by bacongobbler** 2016-02-17 04:38 UTC
